### ISSUE TITLE
Cannot create a new board

### ISSUE THREAD

**Issue by Moini** [stefan-niedermann/nextcloud-deck#100]
Very similar to https://github.com/stefan-niedermann/nextcloud-deck/issues/87, but my error message is longer:

* open app
* open hamburger menu
* click on '+ Add Board' (or is it deck in the English version?)
* select a color and enter a title
* click to create

**Smartphone:**
 - Device: Moto X4
 - Android-Version: Lineage OS 16 (Based on Android 9)
-  System language: German

**Version of Deck:**
- from FDroid: 0.0.3

**Stacktrace**

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.User.getLocalId()' on a null object reference
at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$createBoard$2$SyncManager(SyncManager.java:170)
at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$3P2D-7BtdnPRYG9owpMOaZIALHA.run(Unknown Source:8)
at java.lang.Thread.run(Thread.java:764)
```

What is this local id that it cannot find?

**Comment by desperateCoder** [comment]
Hi @Moini,
Thanks for your report! The locals is the ID of the user as it is saved on your device. Since we support multiple accounts, the IDs may collide, therefore we need something unique per device, the localId.

The problem isn't the ID itself, we are reading a user, but the app doesn't find what it's looking for, so there is no ID where we expect one.

I'll have a look at this as soon as I find some free time.

**Comment by Moini** [comment]
Thank you! Please let me know if there's any additional info you need.

**Comment by stefan-niedermann** [comment]
Hi @Moini can you please retest with the latest version (0.0.6 - should be on F-Droid in a few days) or with the latest master?

Everything should work fine right now - if the issue still persists, please reopen this or create a new issue.

Thanks for reporting!

**Comment by Moini** [comment]
Yep, I will, as soon as I have updated the app.

**Comment by Moini** [comment]
Just updated to 0.0.8 - works :) Thanks a lot , @stefan-niedermann !

**Comment by stefan-niedermann** [comment]
You're welcome :)
