### ISSUE TITLE
Incorrect behavior in enhanced view mode

### ISSUE THREAD

**Issue by neerro** [stefan-niedermann/nextcloud-deck#1012]
**Describe the bug and steps to reproduce the behavior:**
What we have:
I've created a new card in some deck in browser version of Deck. Then I put some date for to-do and set-up task owner. After that, a new card will appear in pending for to-do directory in which I am coming in. Then I wanna to review a new created card in enhanced view mode, for which purpose I clicked on settings (in left lower corner) and toggled on the enhanced view mode. After all mentioned above I clicked on cad for review and change nothing but all UI were breezed. And there is no recourse but to refreshed page. After that card has appeared. In non-enhanced view mode the same scenarios works well.

**Expected behavior**
I want to see a correct behavior.

**Versions**
Nextcloud: latest
Nextcloud Deck: latest
Nextcloud Android: latest
Nextcloud Android Deck: latest

**Comment by stefan-niedermann** [comment]
So you are talking about the Web UI? In the Browser? Or the Android app?

**Comment by neerro** [comment]
> 
> 
> So you are talking about the Web UI? In the Browser? Or the Android app?

In the browser (I use Firefox developer edition) latest update

**Comment by stefan-niedermann** [comment]
This is the **Deck Android** repo.
Open your issue here: https://github.com/nextcloud/deck/issues/new?assignees=&labels=&template=Bug_report.md

**Comment by neerro** [comment]
Ok. Thanks.

**Comment by stefan-niedermann** [comment]
Tell me, is this a funny thing for you to not only ignore the issue template again but fill it partially and then remove the information again? I really would like to understand this kind of provocation after telling you more than 3 times how important this is to *help you* in *our freetime*.

![Screenshot_20210612-095336_Fennec](https://user-images.githubusercontent.com/4741199/121769558-94e2ed00-cb64-11eb-982d-ec2622540d29.png)

![Screenshot_20210612-095645_Fennec](https://user-images.githubusercontent.com/4741199/121769568-990f0a80-cb64-11eb-83c5-f2a94435d023.png)

**Comment by neerro** [comment]
Definitely no nether funny non provocation. I'm a little bit tired and I'm angry as I found many bugs in android deck app which prevent me to work with app smoothly. It seems I paid for app and may get a pleasure for it but not, I need to spend my time for reporting to each bug I found, because it makes impossible works for me. Now I found three another bugs for deck android and forced to spend time once again for reporting this as it makes impossible works well.

**Comment by stefan-niedermann** [comment]
You are welcome to send me your Play Store order ID to info@niedermann.it so i can refund your money.

Without proper bug reports we can't fix them and without any bug reports we can't be aware of them. Obviously. @desperateCoder [explained this already](https://github.com/stefan-niedermann/nextcloud-deck/issues/977#issuecomment-840515046).

So ask yourself: How should we fix your three bugs if we aren't aware of them? #977 has been fixed within a few days - something which wouldn't have been possible without a proper bug report.
