### ISSUE TITLE
Unexpected behavior when bold or italic format applied in text field

### ISSUE THREAD

**Issue by neerro** [stefan-niedermann/nextcloud-deck#1014]
**Describe the bug and Steps to reproduce the behavior:**
You will find all steps and behavior on added [video link](https://youtu.be/fy7jIf1Li_k)

**Expected behavior**
Both bold and italic formats should work properly and together, excluding effects to each other.

**Screenshots**
Video file on the link above

**Versions**
 - Nextcloud: latest
 - Nextcloud Deck: latest
 - Nextcloud Android: latest
 - Nextcloud Android Deck: latest

**Smartphone (please complete the following information):**
- Device: Honor 10 lite
- Android-Version: 10
- App-Store:
  - [x] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

**Comment by desperateCoder** [comment]
@neerro thanks for the well explained report, the video was really helpful! I looked into this and came to the conclusion that we need a full rewrite of the current logic here. Today I was already working on this for a couple of hours and will continue, but I guess this will take some more time. 

I know, the feature seems very cheap and easy to build, but in fact it's quite complex and a hell of a brain-fuck. Just give me some time to fix this properly. 

Sorry for the inconveniences!

**Comment by stefan-niedermann** [comment]
@desperateCoder thanks for rewriting this code part!

@neerro Those improvements will be shipped with Deck Android `1.19.0` and should allow to apply styling via the context menu in a more straight forward, reliable and expected way.

If you find unexpected behavior in the editor with Deck `1.19.0` or higher, please report an issue with a sample again. As @desperateCoder mentioned, applying styles based on a selection is a shitload of complexity, so it is likely that there are further constellations which do not behave as expected 😉
