### ISSUE TITLE
List headers in Deck has not refreshed/synchronized properly

### ISSUE THREAD

**Issue by neerro** [stefan-niedermann/nextcloud-deck#1016]
**Describe the bug**
For example I have a deck with some numbers of lists and suddenly I wanna change the name in one of it. So I did it in web UI interface. After some time is passed I decided to check the changes in Android app but I was surprised as there are were change nothing. When I repeated the same situation but only with one difference, I've just added some text in text field inside card (I that time I didn't change header of list) and after that have checked an Android app I've seen that text is appeared but header of list not.
The same issue observed when I try moving lists inside card (in web UI), then I do not see any refreshed or changes in Android app.
It seems that synchronization from android app to server work normal. As I see of my observation the issue is for synchronization from server to android app.

**Steps to reproduce the behavior:**
It's so long write/read steps... Maybe is enough description in "Describe the bug" section above, what do you think about it? 

**Expected behavior**
Proper synchronization to both sides server--app--server.

**Screenshots**
No

**Versions**
 - Nextcloud: latest
 - Nextcloud Deck: latest
 - Nextcloud Android: latest
 - Nextcloud Android Deck: latest

**Smartphone (please complete the following information):**
- Device: Honor 10 lite
- Android-Version: 10
- App-Store: Google Play Store

**Stacktrace**
No

**Comment by stefan-niedermann** [comment]
This is a known bug of the **server app** (which we already [reported here](https://github.com/nextcloud/deck/issues/2866)). I recommend you to upvote the linked issue.

As a workaround you can disable the `ETags` in the android apps settings to force a full synchronization. This takes way longer than the usual synchronization, but you can reenable `ETags` again after the list has been updated.

**Comment by neerro** [comment]
Ok. Done. Thank you.

**Comment by desperateCoder** [comment]
@neerro you're very welcome! Thanks for the filled out issue report, buddy! 😉

**Comment by desperateCoder** [comment]
did disabeling the etags work tho?

**Comment by neerro** [comment]
Yes I did, but met long loading with freeze status rounded animation on aprx. 20 sec. And quick enabled Etags again.
