### ISSUE TITLE
Handle OfflineException

### ISSUE THREAD

**Issue by desperateCoder** [stefan-niedermann/nextcloud-deck#103]
As the `SyncManager` throws an `OfflineException` when the device has no internet connection, the ExceptionHandler should catch this one seperately and display a toast or anything similar to inform the user. Right now the app crashes for no (valid) reason.

I don't know, if the ExceptionHandler is the right place to catch the Exceptions, but something should be done here...

Not throwing an `OfflineException` is not an option for me, since technically the task isn't done and the user should know that.

**Comment by stefan-niedermann** [comment]
Makes sense for online-only features like activities - everything that is offline capable should not throw it (and currently does not).
