### ISSUE TITLE
No boards displayed in app after login

### ISSUE THREAD

**Issue by mithodin** [stefan-niedermann/nextcloud-deck#104]
**Describe the bug**
After installing the nextcloud files and deck android app and setting both up, no boards are show in deck, even though there are plenty in the web app.

**To Reproduce**
1. Install Nextcloud files and deck android app
2. Add account in nextcloud files
3. Select account in deck app
4. Restart deck app

**Expected behavior**
Show existing online boards

**Smartphone:**
 - Device: Wileyfox Swift
 - Android-Version: Lineage OS 16.0

When I try to add a new board from the app, it crashes with this log:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.User.getLocalId()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$createBoard$2$SyncManager(SyncManager.java:170)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$3P2D-7BtdnPRYG9owpMOaZIALHA.run(Unknown Source:8)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by desperateCoder** [comment]
@mithodin, thanks for your report!
Can you tell the server app version? If it is not the latest, please update it and try again. I'd  also recommend to reinstall the Android app after the server app update.

**Comment by mithodin** [comment]
Server version of deck is 0.6.4, nextcloud 16.0.2

**Comment by juliushaertl** [comment]
Hm, maybe this was caused by my change in deck 0.6.4: https://github.com/nextcloud/deck/issues/1107

@desperateCoder The response format of the acl list in boards was changed to be an array (which was already the case for an empty entry). Any chance you adjust that in the app, as the reported issue was right imo, since we should keep the format consistent.

**Comment by desperateCoder** [comment]
@juliushaertl i actually faced this on Friday, I already fixed that in the upsync branch... But I did not get this problem at sync time... Odd, but I'll investigate this with the latest master, no problem at all, just too few time right now 😅 

Any more API changes I should know about?

**Comment by desperateCoder** [comment]
@juliushaertl, @mithodin,
i just checked Julius' suggestion, and it pretty much sums it up. 
Hold on, fix incoming in 3... 2.. 1...

**Comment by desperateCoder** [comment]
@mithodin this fix will be available within the next release. @stefan-niedermann we should update the minimum deck version to 0.6.4, i'll implement the NC-API for reading the capabilities, hopefully we are safe from outdated server-app versions then.

**Comment by desperateCoder** [comment]
oh and thanks for your suggestion @juliushaertl, you saved me a bunch of time! :+1:
