### ISSUE TITLE
l10n: Transifex sync is not working as expected

### ISSUE THREAD

**Issue by rakekniven** [stefan-niedermann/nextcloud-deck#1062]
Today it was reported that sync from Transifex to GitHub is not working.

Just checked Transifex regarding activity:

<img width="1028" alt="Bildschirmfoto 2021-07-23 um 19 50 40" src="https://user-images.githubusercontent.com/2069590/126821862-c4cf0e12-0e7f-44bd-8cfd-8def47d4a777.png">

Link: https://www.transifex.com/nextcloud/nextcloud/android-deck/

Checked GitHub afterwards:
<img width="1286" alt="Bildschirmfoto 2021-07-23 um 19 52 01" src="https://user-images.githubusercontent.com/2069590/126821915-7cbec523-518d-461b-a64a-30139f6c36a8.png">

Link: https://github.com/stefan-niedermann/nextcloud-deck/tree/master/app/src/main/res

@MorrisJobke  Can you please check?

**Comment by tobiasKaminsky** [comment]
https://github.com/stefan-niedermann/nextcloud-deck/commit/54c0e576a36b6f7f6f81cd751c5d073c1ce92f7b

Now it works again.
Reason was that we switched docker container from docker hub to github docker repo, but failed to generate all needed containers.
