### ISSUE TITLE
Wrong last-board-handling

### ISSUE THREAD

**Issue by desperateCoder** [stefan-niedermann/nextcloud-deck#107]
**Describe the bug**
After the first sync there is a random board selected, maybe the first being created at sync time. 
After the sync the boards have a different order, so selecting a card and pressing back leads the user to a different board, since the indices are diffrent now.
(tested on **upsync branch**)

**To Reproduce**
![error](https://user-images.githubusercontent.com/6911132/61182525-c9766300-a634-11e9-8a70-c93341be0f4d.gif)

**Expected behavior**

**Comment by stefan-niedermann** [comment]
Not reproducable on current master.
