### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by selfisekai** [stefan-niedermann/nextcloud-deck#108]
**Is your feature request related to a problem? Please describe.**
my eyes are getting burnt

**Describe the solution you'd like**
a dark mode available to switch on in app settings/hamburger menu

**Describe alternatives you've considered**
- dark mode by default
- only dark interface (like Spotify)

**Comment by desperateCoder** [comment]
Hi, thanks for your request!
We will consider this after the key features are complete!
I also like to have a dark mode, so the chances are good 😉

**Comment by nr458h** [comment]
In addition to a dark theme please consider also a true black theme for AMOLED displays. Thanks in advance

**Comment by desperateCoder** [comment]
@nr458h shure Thing! But first things first! 😝

**Comment by nr458h** [comment]
thanks for the implementation of the dark mode!

As you closed the thread, may I ask if you would like to add also an AMOLED-true black theme? Would be highly appreciated.

Thanks anyway

**Comment by stefan-niedermann** [comment]
It's currently not planned because we have much more important features to imement and we want to focus first on making this app reliable and stable.

We can have a look afterwards but i cannot promise anything at this point of time, sorry.
