### ISSUE TITLE
Upcoming cards view differs from main Deck App

### ISSUE THREAD

**Issue by q-wertz** [stefan-niedermann/nextcloud-deck#1081]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
In the Android app upcoming card which don't have an assignee but a due date are shown in my list of upcoming cards (as it is intended according to https://upcoming-analyzer.niedermann.it/).
In the official web app I don't see these…

Don't know if it is of importance: The behavior only differs when the cards are from a shared board. When I have an overdue card in my own it is shown in both (Android Deck and Deck) in the Upcoming cards section.

1. Go to 'Upcoming cards' in browser
2. Go to 'Upcoming cards' in android app
3. List differs

**Expected behavior**
On the android app I also see only upcoming cards that are assigned to me

**Screenshots**
![Screenshot_20210815-235142](https://user-images.githubusercontent.com/20948931/129493955-7fab28c6-d12d-42c6-9d60-a8e899b71390.png)

**Versions**

 - Nextcloud: 21.0.4
 - Nextcloud Deck: 1.4.3
 - Nextcloud Android: 3.16.1
 - Nextcloud Android Deck: 1.19.3

**Smartphone (please complete the following information):**
- Device: Nokia 7 plus
- Android-Version: 10
- App-Store:
  - [x] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Comment by desperateCoder** [comment]
Hi @q-wertz, thank you for your report!

Indeed, our current logic is as stated here:

https://github.com/stefan-niedermann/nextcloud-deck/blob/0b1c03f839095dae9508ea088464f9a3f922aa15/app/src/main/java/it/niedermann/nextcloud/deck/persistence/sync/adapters/db/dao/CardDao.java#L23

If I get you right, it is the last part, that isn't as intended: `OR (hasDueDate AND noAssignees))`
Right?

**Comment by q-wertz** [comment]
As I understand stefan-niedermanns comment https://github.com/stefan-niedermann/nextcloud-deck/issues/986#issuecomment-898385572 the Android App should act like the Server App.

In my opinion it currently differs.

**Comment by desperateCoder** [comment]
@jakobroehrl did all the testing for the current logic. What' your opinion on this  @jakobroehrl? I mean - it's quite a minor change to just throw away the last portion of logic, but I think you were involved in the server logic as well, right? Did it change lately or something?

**Comment by stefan-niedermann** [comment]
@q-wertz Nextcloud Deck server changed its logic in version `1.5` - we decided to not maintain multiple different logics but only the latest Deck server version (because user can have multiple accounts in different versions and this would result in a huge maintenance hell).

@jakobroehrl can you confirm that this *is* the change between Deck `1.4` and `1.5`?

**Comment by jakobroehrl** [comment]
Hi, 
there was a litte change in the 1.5.:
https://github.com/nextcloud/deck/commit/45a10f084043d311aee8b2e089f357e7637e39dc
https://github.com/nextcloud/deck/pull/3078

**Comment by q-wertz** [comment]
> Show on shared boards unassigned cards to all users

I'm still on 1.4.3 so that's the reason they differ. With 1.5 (only available for NC22) the Server and Android App will then have the same behavior.
