### ISSUE TITLE
`CTRL` + `ENTER` to Save Changes on Card Description

### ISSUE THREAD

**Issue by SethFalco** [stefan-niedermann/nextcloud-deck#1087]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**

In many apps doing `CTRL` + `ENTER` acts as a "finished" action to either send, post, or save whatever the user is typing.

For example:
* To send an email in Tutanota.
* Submitting issues, pull requests, and comments on GitHub.
* Commenting on Reddit.
* Tweeting on Twitter.

**Describe the solution you'd like**

After clicking "Edit description" the user can type to edit the description of a card.
I think if a user does `CTRL` + `ENTER` it should act as if the user clicked "View description". (Save and return to the non-edit view.)

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by desperateCoder** [comment]
Hi @SethFalco, thanks for your request. Are you sure you want to request that feature for the android App? Or have you maybe mistaken it for the server app in the browser?

**Comment by SethFalco** [comment]
Ah whoops. ^-^' Yeah this was intended for the server app.
Sorry about that! That's what I get for rushing instead of thoroughly checking the repo I was on.

**Comment by desperateCoder** [comment]
Your not the first one mistaking it and you won't be the last one, no oroblem
