### ISSUE TITLE
Rename a list

### ISSUE THREAD

**Issue by Valdnet** [stefan-niedermann/nextcloud-deck#1106]
1. Synchronize your tasks.
2. Rename the list in "Deck" from the Nextcloud instance.
3. Synchronize your tasks.

The list name does not change in the "Deck" app for Android.

**Versions**
 - Nextcloud: 21.1.1
 - Nextcloud Deck: 1.5.2
 - Nextcloud Android: 10
 - Nextcloud Android Deck: 1.19.3

**Smartphone:**
- Android-Version: 10
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Comment by stefan-niedermann** [comment]
This is a bug of the server app (https://github.com/nextcloud/deck/issues/2866)

As a workaround you can disable the `ETags` in the Deck Android apps settings, sync one time (this will take much longer than usual) and reenable the `Etags` again...
