### ISSUE TITLE
App "incompatible" with Onyx Boox running Android 10

### ISSUE THREAD

**Issue by cptMikky** [stefan-niedermann/nextcloud-deck#1110]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

F-Droid says the app is "incompatible with your device". When force-installed, the app apparently works but there is no icon in the launcher (neither the custom Boox launcher, nor the generic Simple App Launcher).

The device is an e-ink Android 10-based tablet/book reader. There is no apparent reason as to why the app should be incompatible with the device and there is also no apparent problem running the app when force-installed (using `pm install deck-from-fdroid.apk`) except the missing launcher icon. The app can be launched from F-Droid.

I was unable to find the reason why F-Droid says the app is incompatible.

1. Open App's "profile" in F-Droid
2. F-Droid says "Incompatible"

**Expected behavior**

App should be installable, launcher icon should be present.

**Versions**
 - Nextcloud Android: 3.17.0
 - Nextcloud Android Deck: 1.19.3

**Smartphone (please complete the following information):**
- Device: Onyx Boox Nova 3 Color
- Android-Version: 10
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Comment by stefan-niedermann** [comment]
Well, we did not explicitly mark the app as i compatible, so i do 't know what caused F-Droid to do so.

@Bubu can you spread some light on this?

**Comment by cptMikky** [comment]
@stefan-niedermann I didn't want to spam with tons of irrelevant information about the device but if there is something specific I can give you, I'm happy to do so.

There is _something_ wrong there because there is no launcher icon but I don't know if the two (F-Droid saying it's incompatible and the missing icon) are related or not.

**Comment by desperateCoder** [comment]
A quick search on this lead me to this: https://developer.android.com/guide/practices/compatibility

Don't know if it's relevant, I'm not too deep into android internals, but sounds reasonable. 

Maybe there's a missing device feature?

**Comment by cptMikky** [comment]
The app uses camera and camera SDK:
```
    <uses-feature android:name="android.hardware.camera.any" />

    <uses-sdk tools:overrideLibrary="androidx.camera.core, androidx.camera.camera2, androidx.camera.lifecycle, androidx.camera.view" />
```
However, the manifest doesn't say it's required as per the link above. Maybe F-Droid doesn't interpret the manifest correctly? I don't have Google Play on the device but Aurora store shows the "buy" button. I can't buy the app via the anonymous account though.

The device **does not** have camera hardware. Not sure about the SDK though, it's a custom-built Android so maybe that SDK is missing as well. Still, this doesn't explain the missing icon.

**Comment by desperateCoder** [comment]
> Still, this doesn't explain the missing icon.

My link above also mentions drawables with different pixel densities and resolutions. Maybe we just didn't provide the icon in the right resolution for your device or something. I guess we need to do some research here and see what we can do about all this. I guess we need a bit more research here...

**Comment by cptMikky** [comment]
Could be. Anything I can help with?

Just to clarify: by _missing icon_ I mean there is no entry for `Deck` in the launchers at all. That is the app is "hidden" and cannot be launched from the launcher(s).

The app can be started via F-Droid (the "Open" button) and it listed in _Settings/Apps_.

**Comment by desperateCoder** [comment]
Oh! Ok, thanks, i indeed git that wrong. Is the icon shown in the app settings list?

If so, I guess all will be resolved, as soon as fdroid or your device are convinced of the compatibility.

**Comment by desperateCoder** [comment]
@stefan-niedermann maybe marking the camera as optional (`required="false"`) already resolves that? Additionally we should query the support where the camera is used and we are good to go?

**Comment by cptMikky** [comment]
In the application list under `Settings/Apps & notifications/See all apps`  _Nextcloud Deck_ sits happily right above _Nextcloud_ app. There is an actual (and correct) icon next to the app name.

**Comment by stefan-niedermann** [comment]
Ping @cptMikky ⇑

**Comment by stefan-niedermann** [comment]
Awesome. I'll push those changes into the next release (`1.19.6`) :slightly_smiling_face: Thanks for reporting and testing.
