### ISSUE TITLE
Fdroid install not working

### ISSUE THREAD

**Issue by jfreak53** [stefan-niedermann/nextcloud-deck#1139]
Installing from fdroid says can't find apk on fdroid servers. Tried 3 versions.

**Comment by stefan-niedermann** [comment]
The `apk` is there: https://f-droid.org/repo/it.niedermann.owncloud.notes_3004016.apk

Check your F-Droid installation, nothing we can do on our side...

**Comment by desperateCoder** [comment]
Here the link to the right app (@stefan-niedermann is maintaining both of them): 

https://f-droid.org/repo/it.niedermann.nextcloud.deck_1019006.apk
