### ISSUE TITLE
Read Nextcloud Notes attachment on the android app like on the web nextcloud version

### ISSUE THREAD

**Issue by Simthem** [stefan-niedermann/nextcloud-deck#1140]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by stefan-niedermann** [comment]
This is the **Deck** Android app, not the **Notes** Android app. What do you mean with "Read"? Just download the attachment and read it with any app of your choice?

Honestly, skipping the complete issue template and barely write a single sentence is not understandable for me. I have no idea what you are talking about. Why not just add a screenshot of "like on the web nextcloud version" so everyone can understand what you are talking about?

[Closing this issue as not understandable](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed). Feel free to open an issue with a **clear and precise request** and **explain detailed** what you want.
