### ISSUE TITLE
Add support for ISRG Root X1 for Android <= 7.0

### ISSUE THREAD

**Issue by ipoupaille** [stefan-niedermann/nextcloud-deck#1164]
If a server is using a Lets Encrypt certificat, and is not sending cross signed root certificat (ISRG Root X1) by DST (during hello), it will not work on the app with android 7.0, even if the certificat has been added to user certificats.

My request is to add this certificat (ISRG Root XB) in network_security_config.xml, or allow user certificats (which is not the case by default starting with android 7.0).
See https://developer.android.com/training/articles/security-config

**Comment by stefan-niedermann** [comment]
Hi @ipoupaille,

the Nextcloud Deck Android app does not perform *any* network requests on it's own. For security purposes it uses the [Nextcloud Single Sign On mechanism](https://github.com/nextcloud/Android-SingleSignOn/), which basically means, the Deck app "asks" the Nextcloud Android app to perform the actual network requests.

Therefore my question: Does the Nextcloud Android app work in your environment without any issues?

**Comment by ipoupaille** [comment]
Hi stefan-niedermann
sorry to bother you.
I just had the problem with another app, and checked in all others apps I have on my phone how is configured the network.
I do not have actually a problem with this app as my nextcloud server is sending the cross signed ISRG Root certificat.

**Comment by stefan-niedermann** [comment]
So your Nextcloud Android app works fine but your Deck Android app doesn't work?
Can you share the error message you are seeing in the Deck Android app please?

**Comment by ipoupaille** [comment]
Oh I am so sorry. My English seem not so good.
My deck app is actually working **fine**. I just have in mind the day were the same thing that append to me with another app today will append with deck: my nextcloud server with a ISRG Root certificat not cross signed by dst. When this day will come, it will not work anymore.

**Comment by stefan-niedermann** [comment]
So, to summarize:

1. Your Deck Android app is working fine now
2. Your certificate will change in the future to ISRG
3. You think the Deck Android app won't work then anymore

Okay, i think i can calm you:

1. The Deck Android app does not do any network requests
2. As long as the Nextcloud Android app keeps working, Deck Android will work, too
3. The Nextcloud Android app allows to manually confirm also self signed certificates, your ISRG thingy should work therefore, too

Feel free to open an issue in the [Nextcloud Android app repository](https://github.com/nextcloud/android/issues/new?assignees=&labels=bug&template=bug_report.md) if you actually experience any issues 🙂.
