### ISSUE TITLE
Error when opening the Deck App from time to time at Samsung Note10+

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [stefan-niedermann/nextcloud-deck#1194]
Hello!
On Samsung Note 10+ with NC 22.2.3, Ubuntu LTS and PHP 8.0 I receive this error from time to time.
It happens without creating or deleting cards. The app just needs to be opened and it happens already.
Also in the local network.
This issue is not creating logs on the server.

```
Full Crash:

App Version: 1.19.4
App Version Code: 1019004
App Flavor: play

Files App Version Code: 30180190

---

OS Version: 4.14.113-22340613(N975FXXS7FUJ1)
OS API Level: 30
Device: d2s
Manufacturer: samsung
Model (and Product): SM-N975F (d2seea)

---

java.lang.IllegalStateException: Fragment NewCardDialog{8c650bd} (1a544995-504c-4b88-95e1-fe16911e7e63) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
	at it.niedermann.nextcloud.deck.ui.card.NewCardDialog$2.lambda$onResponse$0$NewCardDialog$2(NewCardDialog.java:170)
	at it.niedermann.nextcloud.deck.ui.card.NewCardDialog$2$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

**Comment by stefan-niedermann** [comment]
Hello there 👋,

yeah, it's a "known issue" (https://github.com/stefan-niedermann/nextcloud-deck/issues/478) which we unfortunately haven't found a final solution yet.

I got some new ideas recently while reading Android developer documentations and maybe they are capable of fixing this issue... Until the you'll need to be patient unfortunately. As you noticrd yourself, just restarting the app should do the trick as a workaround for now, and since no data is affected, there shouldn't be any risc of data loss or similar painful issues.

Let's track this in the linked issue and already: Have a nice new year!

**Comment by MrLoverLoverMMMM** [comment]
Thank you
-------- Ursprüngliche Nachricht --------Von: Niedermann IT-Dienstleistungen ***@***.***> Datum: 28.12.21  17:26  (GMT+01:00) An: stefan-niedermann/nextcloud-deck ***@***.***> Cc: MrLoverLoverMMMM ***@***.***>, Author ***@***.***> Betreff: Re: [stefan-niedermann/nextcloud-deck] Error when opening the Deck
  App from time to time at Samsung Note10+ (Issue #1194) 

Hello there 👋,

yeah, it's a "known issue" (#478) which we unfortunately haven't found a final solution yet.

I got some new ideas recently while reading Android developer documentations and maybe they are capable of fixing this issue... Until the you'll need to be patient unfortunately. As you noticrd yourself, just restarting the app should do the trick as a workaround for now, and since no data is affected, there shouldn't be any risc of data loss or similar painful issues.

Let's track this in the linked issue and already: Have a nice new year!
