### ISSUE TITLE
+ Button hides action menu of last card in non-scrollable lists

### ISSUE THREAD

**Issue by eliasp** [stefan-niedermann/nextcloud-deck#1196]
**Describe the bug**
When the number of items in a list fills the view to the very bottom of the screen without causing the view to be scrollable, the action menu (3 dots) of the last card in the list is hidden by the + button for creating new items.

Usually, the + button is automatically hidden when scrolling to the very bottom of a list, but in this case this won't have any effect, as the list is not scrollable.

1. Create multiple items until a list's view is filled to the bottom of the screen
2. Modify items (e.g. add/remove a tag or assignee) to increase/decrease their rendered size of the items so the action menu of the last card will be hidden by the + button, while the list is not scrollable yet
3. Try to use the action menu (3 dots) of the last card in the list

**Expected behavior**
It is possible to use the action menu of an item in such a scenario as well, e.g. by one of the following changes to prevent this issue:
- the list becomes earlier scrollable to activate the auto-hide behaviour of the + button.
- the action menu is placed further to the left
- long pressing a card also shows the action menu
- the + button is placed on the left

**Screenshots**
![Screenshot_20220101-231818](https://user-images.githubusercontent.com/48491/147861394-72213e3a-3042-47c8-96c2-d1e720f45b2e.jpg)

**Versions**

 - Nextcloud: 23.0.0
 - Nextcloud Deck: 1.6.0
 - Nextcloud Android: 3.18.1
 - Nextcloud Android Deck: 1.19.6

**Smartphone (please complete the following information):**
- Device: OnePlus Nord (AC2003)
- Android-Version: 11
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**
N/A

**Comment by stefan-niedermann** [comment]
Closing in favor of #1419
