### ISSUE TITLE
No notifications on Android 12

### ISSUE THREAD

**Issue by Kanten** [stefan-niedermann/nextcloud-deck#1206]
I don't see any notifications of current events after updating to Android 12. 
Reinstalling the app and deleting old data did not bring any changes. 
Also, I removed the app from Android's power saving list. Is this an issue related to Android 12?
Did I miss any setting options?

**Comment by stefan-niedermann** [comment]
Dear @Kanten,

as @desperateCoder (and [our FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#how-to-receive-notifications-when-a-due-date-is-reached)) correctly explained, the Deck Android app does not receive or display any push notification itself.

Push notifications are fetched and displayed by the Nextcloud Android app, tapping on them will hand over the information to the Deck Android app. As you see, the issue must be *before* the Deck Android app (probably in the Nextcloud Android app or even on your infrastructure / server if other users are experiencing the same problem). Please check therefore whether you receive any Nextcloud push notifications at all and open an issue in [the repository of the Nextcloud Android app](https://github.com/nextcloud/android/issues/new?assignees=&labels=bug&template=bug_report.md) in case you don't.

Please also do not ignore and delete the issue template next time, it is there [for a reason](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed).
