### ISSUE TITLE
Donate a coffee

### ISSUE THREAD

**Issue by R7JANV1** [stefan-niedermann/nextcloud-deck#1213]
Our team has been using the Nextcloud Deck app for quite a while, but unfortunately the app is not free on the Google Play Store, so users always have to install Fdroid and download the app from there. We offer to cover the cost of the app but it is a big administrative burden because the members of our organization change frequently and with many organization members it is very time consuming. We would rather donate an amount or donate a coffee.

**Comment by stefan-niedermann** [comment]
@R7JANV1 could you please contact me via eMail at info@niedermann.it ? 🙂
