### ISSUE TITLE
Make the +-botton smarter

### ISSUE THREAD

**Issue by christianlupus** [stefan-niedermann/nextcloud-deck#1274]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**

Typically, I need to add multiple cards to the stack at once. So, I  click on the +-button and type the first card's name. To avoid forgetting the other topics, I just want to enter the next and the next etc.
When I click on _save_, the +-button has vanished. I have to scroll up and down in order to make it visible again. Honestly, I have not found a clear solution _where_ I have to scroll exactly, it is just some up and down.

**Describe the solution you'd like**

I have multiple ideas to tackle this:

- Add a button _save & new_ in the dialog asking for the task title
- Make the button sticky (configurable to prevent other users to be disturbed) and do not hide it even when scrolling, allow scrolling a bit below the last entry
- Add a fixed footer to the list like the list of stacks is a header

**Comment by stefan-niedermann** [comment]
Closing in favor of #1419
