### ISSUE TITLE
timeline missing information/update when items are shared with the board

### ISSUE THREAD

**Issue by ilippert** [stefan-niedermann/nextcloud-deck#1291]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

1. add a card to another project/board
2. Open that board's timeline
3. See that the timeline does not report the Sharing information

**Expected behavior**

If I check the timeline for what happend on the board, I expect sharing information to be part of it, and sorted into the timeline at the respective chronological point.

**Versions**

 - Nextcloud Deck: 1.6.3

**Comment by stefan-niedermann** [comment]
Dear @ilippert 

the information in the `Activity` tab is not collected by the Deck Android app but by the (not by us developed) Deck server app. The Deck Android app fetches and displays the information.

Therefore I'd kindly ask you to reopen your ticket in the [repository of the Deck server app](https://github.com/nextcloud/deck/issues/new?assignees=&labels=&template=Feature_request.md) - once your issue has been fixed there, the Deck Android app will also show the currently missing information.

Regards

**Comment by ilippert** [comment]
Dear Stefan Niedermann,
thank you for your kind response. I have now reported this at https://github.com/nextcloud/deck/issues/3874
Regards
