### ISSUE TITLE
Feature Request: Default Board on Startup

### ISSUE THREAD

**Issue by aljawaid** [stefan-niedermann/nextcloud-deck#1298]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**
Some users only work on certain 'daily' boards whilst having access to a few.

**Describe the solution you'd like**
1. Allow option to select a default board, or the upcoming cards on startup, or the last used board

**Describe alternatives you've considered**
None

**Additional context**
[Some General Feedback on Deck for Android #1290](https://github.com/stefan-niedermann/nextcloud-deck/issues/1290#)

**Comment by stefan-niedermann** [comment]
Given the lifecycle of an Android app is quite complex, I personally think implementing this feature is more confusing than helpful.
- "on startup" can mean anything here from "always when I press the launcher" to "when I open the app, go back to homescreen and return via recent apps".
- Not to mention various other use cases like "ending via home button" vs. "ending via back arrow".
- What if Android killed the app while it was in background?
- What if the app was relaunched while another app was in foreground and multitask mode was started?

As you see, it ain't that easy and while it was quite much work to define all possible states, it won't be possible to find satisfying solutions for each user and each use case.

In my opinion the only reliable and expected way is to persist and keep the current state as stable as possible (which is what we are currently doing).
