### ISSUE TITLE
Feature Request: Allow Multi Line Comments

### ISSUE THREAD

**Issue by aljawaid** [stefan-niedermann/nextcloud-deck#1299]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**
The web allows multiline comments in cards but not in the mobile deck client.

**Describe the solution you'd like**
Allow the mobile to insert new lines in comments

**Describe alternatives you've considered**
Web version for serious comments where readibility is important

**Additional context**
[Some General Feedback on Deck for Android #1290](https://github.com/stefan-niedermann/nextcloud-deck/issues/1290#)

**Comment by stefan-niedermann** [comment]
Will be featured in version `1.20.2`
