### ISSUE TITLE
Open Deck App via Nextcloud App

### ISSUE THREAD

**Issue by NorVoi** [stefan-niedermann/nextcloud-deck#1323]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**

Hi,

I'm not sure if I'm in the right place with my query.  I have the Deck app on my smartphone.  Likewise the Nextcloud app.  When I search for an entry in Deck via the Nextcloud app, Nextcloud opens the browser.  I would prefer if the Deck app could be opened.  Is such an attitude possible?  

Thanks and best regards

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by stefan-niedermann** [comment]
This is already tracked [here](https://github.com/nextcloud/android/issues/8279) and can not be solved (only) in this repository. We are aware of this issue though 🙂
