### ISSUE TITLE
Update to The Material Design 3

### ISSUE THREAD

**Issue by JanOstrowka** [stefan-niedermann/nextcloud-deck#1330]
I am a big fan of this app, and I use it for organizing my thoughts, tasks, ideas and more. It is one of my favorites. At the same time, I am mesmerized by the newly released `Material Design 3`. It's gorgeous!

Would it be possible, to update outdated components inside of the Deck, to the new design system?
e.g. date & time picker, top bar, cards etc.

I am not an Android developer, but maybe this will help:
https://material.io/blog/migrating-material-3

**Comment by stefan-niedermann** [comment]
Will be part of `1.21.0` :slightly_smiling_face:

**Comment by JanOstrowka** [comment]
I love it!
Thank you
