### ISSUE TITLE
Markdown Check-Boxes in Darkmode almost invisible

### ISSUE THREAD

**Issue by Oleoleee** [stefan-niedermann/nextcloud-deck#1331]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Markdown Check-boxes in Darkmode are almost invisible due to not inverting the color of the boxes

**Expected behavior**

Color of Check-boxes also inverted (white)

**Screenshots**

![Screenshot_2022-08-31-17-02-16-552_it niedermann nextcloud deck](https://user-images.githubusercontent.com/112564758/187712779-55765ab7-0fa1-4d61-9b7c-179fe14bd482.jpg)
![Screenshot_2022-08-31-17-02-23-624_it niedermann nextcloud deck](https://user-images.githubusercontent.com/112564758/187712783-f778e8d5-2874-4ac3-8dae-da2c99f13446.jpg)
![Screenshot_2022-08-31-17-03-20-436_it niedermann nextcloud deck](https://user-images.githubusercontent.com/112564758/187712786-c5f1d903-3618-435a-8cfd-1f7291cff4ca.jpg)
![Screenshot_2022-08-31-17-03-33-821_it niedermann nextcloud deck](https://user-images.githubusercontent.com/112564758/187712789-5c3a7f11-5141-4fd5-ab6e-3705ccf5b5aa.jpg)

**Comment by stefan-niedermann** [comment]
Neither reproducable on my physical Pocophone F1 device nor on an emulated device.

Given you [not only ignored but actually deleted parts of the issue template](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed), we can only assume local environment related issues like manufacturer or custom rom depending theming stuff.

![grafik](https://user-images.githubusercontent.com/4741199/193446100-aa17d80b-3c19-4523-afaa-df6ae82a38af.png)
