### ISSUE TITLE
Support Android notifications

### ISSUE THREAD

**Issue by Bassmann** [stefan-niedermann/nextcloud-deck#1333]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

There are no android notifications for cards where a due date is set

1. Go to a card
2. Set a due date a few minutes in the future 
3. Wait for the due date time 
4. Nothing happens

**Expected behavior**

I expect an android notification to occur once a due date is reached. Also it would be nice to have an indication in the app icon how many due dates have been missed

**Screenshots**

**Versions**

 - Nextcloud: 24.0.4
 - Nextcloud Deck: 1.7.1
 - Nextcloud Android: 3.21.2
 - Nextcloud Android Deck: 1.20.2

**Smartphone (please complete the following information):**
- Device: Samsung S20FE
- Android-Version: 12
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**
N/A

**Comment by stefan-niedermann** [comment]
Please check out our FAQ as stated in the issue template:
https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#how-to-receive-notifications-when-a-due-date-is-reached
