### ISSUE TITLE
Crash while syncing

### ISSUE THREAD

**Issue by farfromrefug** [stefan-niedermann/nextcloud-deck#1351]
I get this crash now while.syncing with my nextcloud self hosted
```
App Version: 1.20.3
App Version Code: 1020003
Server App Version: 1.6.1
App Flavor: fdroid

Files App Version Code: 30200190

---

OS Version: 3.18.140-SIMPLE-KERNEL_V1.3_ZRAM(eng.wistan.20220513.173651)
OS API Level: 29
Device: a3y17lte
Manufacturer: samsung
Model (and Product): SM-A320FL (a3y17ltexc)

---

com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Nextcloud Files app API is not responding. This is most likely due to battery optimizations on your phone. Try to disable the battery optimization for both apps (Nextcloud Android and this app). In all other cases please try to clear the storage of both apps.
	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:162)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:298)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:180)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by stefan-niedermann** [comment]
For sure you already tried the suggested steps from the [FAQ regarding this topic](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#i-have-experienced-an-error) before [ignoring and deleting the issue template](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed)? 😉

**Comment by farfromrefug** [comment]
@stefan-niedermann I am sorry i actually removed the template because i thought (and still think) the crash report from the app was having everything necessary (and i checked, maybe i missed some) to report the issue.
I also realise now i had 2 different crashes and this is not the one i thought i copied. MY real issue was with coordinate layout crashing. And it was a crash. I did not read the FAQ but as a dev myself if i see a clear crash il like coordinate layout i dont expect to have to clear storage. Glad i dont have to do that in all my apps.
I ll close this issue i will also say that if you think the report from the app is not enough to report an issue (as replacing the template) you should update the report from the app to be "compatible" with the template. Would be better for everyone.
I apologise for wasting your time

**Comment by stefan-niedermann** [comment]
> I apologise for wasting your time

No reason to feel offended! Well, Saturday evening, I got some minutes for a discussion :smile: 

> i thought (and still think) the crash report from the app was having everything necessary (and i checked, maybe i missed some) to report the issue.

A crash report is simply by nature not able to provide all necessary information for a proper issue report. Being able to reproduce a bug is usually way more important than knowing the exact line in the source code where the actual crash happens.

A crash report is helpful to learn about the symptoms, but only in very rare cases the actual origin or reason for the bad behaviour can be read from a stack trace. While some information might look redundant, it is absolutely possible that for example the "detected" Deck server version differs from the actual used Deck server version, which gives us further hints. Not everybody is a tech expert and users tend to make assumptions or think they know better what is relevant to solve an issue.

Asking each and every missing information about the varying specific environments of users leads to complicated crowded and confusing issue histories, making it hard for other contributors to follow the discussion. And, to be honest, we usually simply do not have the time to ask the same questions over and over again. It's a free time project and we therefore simply *expect* users to read the FAQs and fill in the issue template in exchange for the support we are trying to give.

> I also realise now i had 2 different crashes and this is not the one i thought i copied.

Which is a good example for assumptions and / or misinterpretations of terms: You had one dialog with an synchronization issue (the one you posted). This wasn't an actual crash, the app continued to work except the sync. The other one might have been an actual crash, where the application stopped working and got closed - looking forward to another issue if it occurs again.

> i dont expect to have to clear storage.

Clearing the storage is the most easiest way to regain a clear state of the app, when no information about the steps that led a user into a specific state is available.
In most cases it is simply enough - there are way too many environmental related problems, server hickups(, ...) which can *not* be fixed on our side, for example if the Deck server app pushes yet another breaking change without announcing it (*sigh*).

> Glad i dont have to do that in all my apps.

Well, how many of your apps are using a [local Single Sign On mechanism](https://github.com/nextcloud/Android-SingleSignOn/) like the Nextcloud apps do? It is technically a good solution, well shot by battery "optimizations" of some manufacturers but considering all pros and cons a trade off we are willing to take.

> as a dev myself

... you are welcome to contribute to the open source projects [Deck Android](https://github.com/stefan-niedermann/nextcloud-deck), [Nextcloud Android](https://github.com/nextcloud/android), [Nextcloud Single Sign On](https://github.com/nextcloud/Android-SingleSignOn/), [Nextcloud Deck](https://github.com/nextcloud/deck/) and contribute better solutions :rocket:

**Comment by farfromrefug** [comment]
Thanks for answering me! 
For reference here is the true crash I wanted to report.  As I said I think it is enough on its own. Plus I actually don't have a context cause it happened randomly. 
I ll let you do what you want with it.
Thanks
```
Full Crash:

App Version: 1.20.3
App Version Code: 1020003
App Flavor: fdroid

Files App Version Code: 30200190

---

OS Version: 3.18.140-SIMPLE-KERNEL_V1.3_ZRAM(eng.wistan.20220513.173651)
OS API Level: 29
Device: a3y17lte
Manufacturer: samsung
Model (and Product): SM-A320FL (a3y17ltexc)

---

java.lang.NullPointerException: Attempt to read from field 'androidx.coordinatorlayout.widget.CoordinatorLayout it.niedermann.nextcloud.deck.databinding.ActivityMainBinding.coordinatorLayout' on a null object reference
	at it.niedermann.nextcloud.deck.ui.MainActivity.lambda$showSyncFailedSnackbar$34$it-niedermann-nextcloud-deck-ui-MainActivity(MainActivity.java:1115)
	at it.niedermann.nextcloud.deck.ui.MainActivity$$ExternalSyntheticLambda9.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
