### ISSUE TITLE
Using existing nextcloud account not possible

### ISSUE THREAD

**Issue by elumbella** [stefan-niedermann/nextcloud-deck#1359]
When starting the app and selecting the already existing nextcloud account on this device, login fails with a message about missing single sign on (see attached screenshot) This was not the case on my old device (Android 10), but is now (Android 12).
![Screenshot_20221015-112614](https://user-images.githubusercontent.com/2538681/195979391-f7208d5a-e105-4f63-bd20-c44708042fa5.png)

**Comment by desperateCoder** [comment]
Hi @elumbella, thanks for your report!

I'm using Android 12.1 and don't have any issues with that ("works on my machine" :sweat_smile:)

I think this is not a problem with the Deck app. What version of the Nextcloud Files app do you use? Make sure to use the latest version of both apps.

Maybe reinstalling the Files app could also fix it. Sorry for "im trüben fischen", this really isn't a commonly seen problem here...

**Comment by elumbella** [comment]
I was using the development version 20221008. I just installed the current version from the google play store and it is working now. I'll stick to that then. Thanks for the hint!

**Comment by stefan-niedermann** [comment]
Please read https://github.com/stefan-niedermann/nextcloud-deck/issues/1243#issuecomment-1200100084
