### ISSUE TITLE
Account name not displayed correctly when it contains space character

### ISSUE THREAD

**Issue by Nils160988** [stefan-niedermann/nextcloud-deck#136]
**Describe the bug**
Only the part of the username before a space character occurs is displayed.

**To Reproduce**
1. Create at least one user with space character in it
2. Add accounts to nextcloud deck
3. See the panel where you can choose between different account

**Expected behavior**
The accounts' names are displayed completely.

**Smartphone (please complete the following information):**
 - Device: BQ Aquaris X
 - Android-Version: 8.1.0

Deck-Version 0.6.6 (Server) and 0.0.8 (Android)

**Comment by desperateCoder** [comment]
Could you tell us the name of the board or at least how many characters are the first word has? Maybe there is simply no more space to display it, so it's cut off?

**Comment by stefan-niedermann** [comment]
I guess so, we definitely should ellipsize the account name proberly, but in the first place we need whether or not the account name is simply too long.

**Comment by Nils160988** [comment]
See following screenshot:

![Screenshot](https://user-images.githubusercontent.com/29654384/65306155-086ceb80-db85-11e9-8f5d-9387dd71e111.png)

For the account with firstname@domain it works (just cutoff because too long), for the account with "FirstName Lastname"@domain it does not.

**Comment by stefan-niedermann** [comment]
Possiblr solution after some research: Use an `actionLayout` for the menuItems to define an own Layout which is capable of correct ellipsizing. This might be also useful for the boards menuItems which currently also are simply cut off at a space character.

**Comment by stefan-niedermann** [comment]
We are using ellipsize now for the accounts.
On modern android it will look like this

![grafik](https://user-images.githubusercontent.com/4741199/65821184-7e7eeb80-e232-11e9-8d4d-4a037041cc9b.png)

and on old Android versions (This is Android 4):

![grafik](https://user-images.githubusercontent.com/4741199/65821190-876fbd00-e232-11e9-9353-d7aff04493f6.png)

So basically we try to ellpisize the middle part, so one could assume the username and the server

**Comment by Nils160988** [comment]
Thanks for fixing, works as expected now!

**Comment by stefan-niedermann** [comment]
You're welcome, thanks for reporting :)
