### ISSUE TITLE
Text in border in card detail view is "00:00" instead of "Time".

### ISSUE THREAD

**Issue by cloud2018** [stefan-niedermann/nextcloud-deck#1375]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
Text in border in card detail view is "00:00" instead of "Time"
Date is "due date" in the frame as expected, so the expectation is that time is "time" in the frame.

1. Go to card detail view
2. Choos a due date
3. See "00:00" instead "time" (text) of border around time-Box

**Expected behavior**
Date is "due date" in the frame as expected, so the expectation is that "time" in the border around the time-box.

**Screenshots**
![IMG_20221108_195205](https://user-images.githubusercontent.com/34692335/200652788-dd5e2fa8-30dd-4617-96f5-7f32b8579603.jpg)

**Versions**

 - Nextcloud:  24.0.7.1
 - Nextcloud Deck: 1.2.11
 - Nextcloud Android: 3.22.2
 - Nextcloud Android Deck: 1.21.1

**Comment by stefan-niedermann** [comment]
Will be fixed in `1.21.2`, thanks for the hint!
