### ISSUE TITLE
No access to file system possible on Android 13

### ISSUE THREAD

**Issue by Plobli** [stefan-niedermann/nextcloud-deck#1379]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
It is not possible to select photos or other attachments from my smartphone as there is no query for permission to access the data system.
Only access to the camera is possible.

**Screenshots**

![Screenshot_20221109-172415](https://user-images.githubusercontent.com/4347582/200885003-c4eb3b39-147b-4942-bb8b-fdc79a493f0f.png)
![Screenshot_20221109-172429](https://user-images.githubusercontent.com/4347582/200885009-6da0367c-6b13-47ab-bf10-5f28eb144ba5.png)

**Versions**

 - Nextcloud: 23.0.4
 - Nextcloud Deck: 1.6.4
 - Nextcloud Android: 3.22.2
 - Nextcloud Android Deck: 1.20.3

**Smartphone (please complete the following information):**
- Device: Pixel 4XL
- Android-Version: calyxOS 4.2.7 (Android 13)
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

**Comment by Plobli** [comment]
The issue appears only in Version 1.20.3. Version 1.20.2 ask for the right permission. 
![Screenshot_20221112-100849](https://user-images.githubusercontent.com/4347582/201467385-42ec2b36-bb31-4ada-b992-a4b5f1abd171.png)

**Comment by stefan-niedermann** [comment]
Yup, I assume [setting the `compileSdk` to `33`](https://github.com/stefan-niedermann/nextcloud-deck/commit/ccf9fedc616361bdacc7b645d2e61a1577f80e0e#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9) caused this. I'll have a look.

**Comment by stefan-niedermann** [comment]
I think I found a solution, some testing would be awesome. This debug build can be installed safely next to the released version, you will be able to distinguish them by their launcher logo: https://github.com/stefan-niedermann/nextcloud-deck/suites/10099557906/artifacts/492386098

Looking forward to some feedback 🙂

**Comment by stefan-niedermann** [comment]
Should be fixed in `1.21.7`
