### ISSUE TITLE
Not loose content on screen rotate or app change

### ISSUE THREAD

**Issue by Thomas131** [stefan-niedermann/nextcloud-deck#1394]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
While creating/modifying a card, the modification is gone:
* on screen rotation
* when switching to another app eg. to research stuff if Android automatically closes NextCloud Deck during research
* (?) probably on app crash
I would like that the app auto-saves the temporary data and restores it when the app comes into focus again (ideally even if the app restarts - but here I also see some points against).

The difference to #747 is that my problem edits are lost when I don't intend to close the app. I don't think of my card to be saved & synced to NextCloud, but my changes to be stored in a temporary location (in RAM or as a file/database) so that I can continue where I have finished.

Steps to reproduce the behavior: (one example)
1. write a card
2. rotate the screen - text seems still there
4. rotate the screen back - your edits are gone
OR
1. write your card
2. switch to the another app to select text to copy (so that the RAM is exhauted and NextCloud Deck is closed)
3. go back to the Deck - the unsaved content is gone

**Expected behavior**

I would like that the app auto-saves the temporary data and restores it when the app comes into focus again (ideally even if the app restarts - but here I also see some points against).

**Screenshots**

Step 1:
![Step 1](https://t13.one/tmp/20221222_1.png)
Step 2:
![Step 2](https://t13.one/tmp/20221222_2.png)
Step 3:
![Step 3](https://t13.one/tmp/20221222_3.png)

**Versions**

 - Nextcloud: 24.0.4
 - Nextcloud Deck: 1.7.2
 - Nextcloud Android: 3.21.0
 - Nextcloud Android Deck: 1.21.6

**Smartphone (please complete the following information):**
- Device: Samsung Galaxy J5 with a custom LineageOS
- Android-Version: 10
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [X] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

Thanks for all the work you do!!
Thomas131

**Comment by Latechneuse** [comment]
+1 – This is indeed one of the most annoying bugs of the app, making it at times very frustrating to use.

**Comment by Thomas131** [comment]
Oh, I realized that this is a duplicate from #1357 - sorry for not seeing that when I created the issue.

**Comment by digitalrevisor** [comment]
We usen version 27.1.8. And autosave card is unstable or does not work properly. We have many cards in Deck.
