### ISSUE TITLE
Error: Network is unreachable at the login state

### ISSUE THREAD

**Issue by bitsnaps** [stefan-niedermann/nextcloud-deck#1399]
Hi,

I get an error at the first login attempt, right after the message `Importing boards` I get the `Network is unreachable`, and I'm not using any Nextcloud app except the official release on F-Droid.

1. Go to open the app on Android
2. Click on 'choose account'
3. Select existing account server (already working using the official Nextcloud on F-Droid)
4. See the error `Network is unreachable` (with a bug report dialog `Oh no - What now?`) after the message `Importing boards`

**Expected behavior**
Open Deck app.

**Versions**
 - Nextcloud: latest
 - Nextcloud Deck: latest
 - Nextcloud Android: 7.1.2
 - Nextcloud Android Deck: latest

**Smartphone (please complete the following information):**
- Device: Android (Asus Zenfone 2)
- Android-Version: 7.1.2
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [X] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**
```
App Version: 1.21.7
App Version Code: 1021007
Server App Version: 0.6.4
App Flavor: fdroid
 
Files App Version Code: 30230190
 
---
 
OS Version: 3.10.72BORETS_ROM_zf4-x86_64_moor(e40bddc983)
OS API Level: 25
Device: Z00A
Manufacturer: asus
Model (and Product): ASUS_Z00A (WW_Z00A)
 
---
 
com.nextcloud.android.sso.exceptions.UnknownErrorException: Network is unreachable
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(D8$$SyntheticClass)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
 
```

P.S. The official [Nexcloud client](https://f-droid.org/en/packages/com.nextcloud.client/) v3.23.1 app is working properly.

**Comment by stefan-niedermann** [comment]
Please be more specific regarding the versions you are using. "latest" is isually invalid at the time writing and does not give any hint about which version exactly might have introduce misbehavior.

I am especially interested in the Deck server app version you are using.

Further interesting information would be:
1. Is the Deck app reachable via web browser?
2. Are you able to connect to your instance with another device (for example a friends)

**Comment by bitsnaps** [comment]
I'm using v24.0.6 of the server, I'm not sure how to get the version of a specific app (Deck...), the server is hosting at [spryservers.net](spryservers) they just mention `Nextcloud Latest` at the hosting page.

> 1. Is the Deck app reachable via web browser?

Yes, I'm able to connect via a browser.

> 2. Are you able to connect to your instance with another device (for example a friends)

I don't have another smartphone, except an old LG with Android 4.4.2, so the current Deck app is not compatible with this device.

Are you relying on any Google Services? (because I don't use these services)

**Comment by stefan-niedermann** [comment]
No, we don't rely (or use) any proprietary services, especially no Google Play Services and no Google Firebase.

The issue sounds quite strange. Can you provide credentials to a (temporary) test account so I can debug the issue?

**Comment by bitsnaps** [comment]
Sorry, I couldn't find a way to create a temporary account on this server. However, I solved the issue by first opening the `Nexcloutd client` (wait for login and keep it running in the background) then open `Nextcloud-Deck` and connect/allow to the server, finally it starts importing boards...

There are two things I can suggest to detect this type of error in the future:
1- Try to raise more specific error message when starting the app (e.g. `Network is unreachable: while connecting`, `Network is unreachable: while importing boards...`)
2- Add a dialog prompt whether user wants to import boards right after connecting (e.g. `Connected to server successfully, would you like to start importing boards ?`)

This may help you detect which phase the error raised and probably the reason.
