### ISSUE TITLE
allow copying card link

### ISSUE THREAD

**Issue by KiaraGrouwstra** [stefan-niedermann/nextcloud-deck#1406]
I have assigned cards to a co-worker, but they don't often check Deck. as such, I would like to call their attention to one such card.

however, it seems the app now does not offer a share option to allow me to link such a card.

it would be nice if it did.

**Comment by stefan-niedermann** [comment]
![IMG_20230116_112501_166](https://user-images.githubusercontent.com/4741199/212656024-640d9483-642f-4e66-9aeb-7eb17c1e360a.jpg)
