### ISSUE TITLE
dialogue "choose account" collapses instantly on Deck Android App 1.21.8 - no sign in possible

### ISSUE THREAD

**Issue by pete-at-future-campus-ruhr** [stefan-niedermann/nextcloud-deck#1434]
After installation of the current Version 1.21.8 on the welcome screen the dialogue box immediately disappears when tapping the button to "choose account" making it so I cannot login. App is installed through F-Droid

Phone is a Samsung S22 Ultra, running Android 12, One-Ui 4.1

**Comment by pete-at-future-campus-ruhr** [comment]
System Update of the Phone solved the problem

**Comment by desperateCoder** [comment]
@pete-at-future-campus-ruhr thanks for the update! Good to know!
