### ISSUE TITLE
Present Comments in LIFO order (like in Nextcloud Deck app)

### ISSUE THREAD

**Issue by filipesaraiva** [stefan-niedermann/nextcloud-deck#1460]
**Is your feature request related to a problem? Please describe.**

The Nextcloud Deck app presents the comments of a card in LIFO (Last-In, First-Out) order - the last comment is in the top of the comments stack.

But Android Deck app presents the comments in a FIFO (First-In, First-Out) order - the last comment is in the bottom of the comments stack.

I think the way as comments are presented in both Nextcloud Deck and Android Deck must be in the same order.

**Describe the solution you'd like**

Present the comments in both Nextcloud Deck and Android Deck in the same order.

I think LIFO (last comment is in the top of the comments stack) is the best way to present the comments in the context of a card.

**Comment by stefan-niedermann** [comment]
Considering the differen input mechanism, I disagree.
On a desktop, the position of the inout field does not matter as it can be reached with mouse and keyboard at the top as good as at the bottom.

On a (usually) touch interface with a (usually used)

**Comment by filipesaraiva** [comment]
Thank you @stefan-niedermann, I got your point. In fact, the local where input text is allocated guides the comments flow of the card - if the input text is on top, the comments flow is from bottom to top; if the input text is on bottom, the comments flow is from top to bottom.

However, I feel strange accessing a same "service" (a card on deck) in different devices I must read the comments flow in different directions to understand the entire conversation related to that card. It is not a problem when the card has just few comments, but think about a card with several comments - in web I need to scroll down, in Android I need to scroll up the comment box. For me it is a kind of design break.

Anyway it is just an idea and suggestion, feel free if you disagree this point. :)

Thank you for your work on Deck and Notes!

**Comment by stefan-niedermann** [comment]
Thanks for your suggestion :slightly_smiling_face: 

However I do currently not plan to change the layout for the mentioned reasons (which are for sure debatable).
