### ISSUE TITLE
Gadget problem on Android

### ISSUE THREAD

**Issue by gtavoalva** [stefan-niedermann/nextcloud-deck#1465]
Versions:
Nextcloud: 26
Deck: 1.9.0
Android Deck: 1.21.7

When the gadget is added to android desktop, is only showing a blank gadget.
![Screenshot_20230408115309_1_1](https://user-images.githubusercontent.com/4118340/230743705-87c9d818-ae94-4f57-a808-d275a990c81c.png)
![Screenshot_20230408115314_1](https://user-images.githubusercontent.com/4118340/230743716-a93867c2-98c3-48d1-8527-151ad413e9d1.png)

**Comment by desperateCoder** [comment]
Do you have cards with due dates set?

**Comment by gtavoalva** [comment]
My fault then. This gadget only show cards with due dates.
![Screenshot_20230408190437_1](https://user-images.githubusercontent.com/4118340/230746083-15309002-d398-4916-8d3f-d4020afe7acf.png)
 Thank you for this.

**Comment by desperateCoder** [comment]
Yep, it is so you can see what's due soon so you know how to prioritize your tasks. 

You're welcome, always glad to help!
