### ISSUE TITLE
New searchbar: not possible to move card to different list

### ISSUE THREAD

**Issue by modules** [stefan-niedermann/nextcloud-deck#1467]
With the new search (1.22.1) it seems to be impossible to move a card directly to another list.

Old search
![signal-2023-04-11-18-11-30-623](https://user-images.githubusercontent.com/84223/231224412-283fea81-3d54-4db8-a735-374c1133923f.png)

You can see all lists and move a searched card directly to list.

New search
![Screenshot_20230411-181156_Nextcloud Deck](https://user-images.githubusercontent.com/84223/231224490-812b023b-3caa-4dad-8b6c-7a9f33a39e30.png)

You can see only the list as headline of the searched card but its not possible to move it directly to another list.

Is this a bug or a feature?

**Comment by stefan-niedermann** [comment]
Fixed in 1.23.3

![Screenshot](https://user-images.githubusercontent.com/4741199/246072523-82bb36ae-1038-4b04-b73a-58e71ff33de3.png)
