### ISSUE TITLE
Cards show up in 'Upcoming cards' although there are in the 'Done' column

### ISSUE THREAD

**Issue by owzim** [stefan-niedermann/nextcloud-deck#1474]
**Describe the bug**

Cards show up in 'Upcoming cards' although there are in the 'Done' column

1. Go to 'upcoming cards'
3. See cards that are in the Done column

**Expected behavior**

Those cards should not show up

**Versions**

 - Nextcloud: 25.0.6
 - Nextcloud Deck: 1.8.3
 - Nextcloud Android: 3.24.1
 - Nextcloud Android Deck: 1.21.8

**Smartphone (please complete the following information):**
- Device: Pixel 4a
- Android-Version: 13
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Comment by stefan-niedermann** [comment]
The Deck server app does not [support a `Done` state](https://github.com/nextcloud/deck/issues/534) yet. The last column does not have any special meaning or behavior. Please *read* and continue the discussion in the linked issue.

The Deck Android app will support this feature once the Deck server app provides a proper API for it. We do not have plans to change the current behavior to a different one from the Deck server app.
