### ISSUE TITLE
[Feature request] Add a true black theme.

### ISSUE THREAD

**Issue by Pouncingkitten** [stefan-niedermann/nextcloud-deck#1479]
I would appreciate a true black theme (e.g. current dark theme but with true black background colour). This is quite common as a third addition to the default white/dark themes and quite useful on amoled screens.

**Comment by stefan-niedermann** [comment]
We are orientating on the main Nextcloud Android app design wise to reduce maintenance. When there is a black theme available, we will adapt it to the Deck Android app
