### ISSUE TITLE
No "move" action from detail view

### ISSUE THREAD

**Issue by eliasp** [stefan-niedermann/nextcloud-deck#1484]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**
When opening a notification for a card that reached its due date, I often would like to move this card (e.g. to "Done").
The notification opens the card details, which provide no "Move" action.

To actually move the card, I have to explicitly open Nextcloud Deck, open the corresponding board/column, [scroll to find the card](https://github.com/stefan-niedermann/nextcloud-deck/issues/1467) and then move it.

**Describe the solution you'd like**
I'd like to be able to move a card directly from the details view (e.g. via a 3-dots menu or so), as in many cases I don't want to lose the context of the card details, but move it at the same time to another column without having to do it from the corresponding column overview.

**Describe alternatives you've considered**
The notifications for cards could provide "quick actions" (I don't know what the correct Android terminology is), such as "Archive" or "Move".

**Additional context**
Using the currently latest version of the Nextcloud Deck App (1.23.2) on Android 11.

**Comment by stefan-niedermann** [comment]
Will be possible with `1.23.3`:

![image](https://github.com/stefan-niedermann/nextcloud-deck/assets/4741199/82bb36ae-1038-4b04-b73a-58e71ff33de3)
