### ISSUE TITLE
Callouts within card descriptions don't display correctly

### ISSUE THREAD

**Issue by will6789** [stefan-niedermann/nextcloud-deck#1501]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Callouts (Info/Success/Warning/Danger) added to cards via the Deck web interface are not shown correctly in the Deck Android app. It appears the underlying formatting symbols are shown instead (see screenshots)

1. Go to the Nextcloud Deck web interface
2. Create a new card and enter some text in the description
3. Highlight the text, click the "Callouts" button and choose any option
4. Observe how the callout is displayed
5. Open the same card in the Deck Android app
6. Observe that the callout is not displayed correctly

**Expected behavior**

The Deck Android app should show the callout in the same style as the Deck web interface. Including an appropriate coloured bar and icon.

**Screenshots**

Web interface view:
![image](https://github.com/stefan-niedermann/nextcloud-deck/assets/1783065/b8a7bc41-e8a7-4c4c-9dd2-e032bc14c290)

Android app view of the same card:
![Screenshot_20230621-230414](https://github.com/stefan-niedermann/nextcloud-deck/assets/1783065/26ddefb1-05d0-460a-bbbe-16d87dc664fe)

**Versions**

 - Nextcloud: 26.0.2
 - Nextcloud Deck: 1.9.2
 - Nextcloud Android: 3.25.0
 - Nextcloud Android Deck: 1.23.3

**Smartphone (please complete the following information):**
- Device: Google Pixel 7 Pro
- Android-Version: 13
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**
N/A

**Comment by stefan-niedermann** [comment]
Hello @will6789  👋

Our markdown editor is based on [Markwon](https://github.com/noties/Markwon/issues) so you will need to ask there for supporting this feature. If it get's implemented upstream, it will eventually published with one of the next Deck Android versions.

However, given this feature is AFAIK not standardized in the [`CommonMark` markdown language specification](https://spec.commonmark.org/0.30/), i doubt that `Markwon` will implement it (just my guess).

Also referring to [some reasons](https://github.com/stefan-niedermann/nextcloud-deck/issues/452#issuecomment-1600342701) why we do *not* have any plans to switch to the `Nextcloud Text` editor used by the Web UI.

Kind regards,
Stefan
