### ISSUE TITLE
How are you calling the 'assigned cards' view?

### ISSUE THREAD

**Issue by morgannunan** [stefan-niedermann/nextcloud-deck#1506]
This isn't even so much a feature request as a curious question. I have forked the main Deck app because I'm trying to add functionality where you can view all cards, across all boards, that are assigned to you.

I installed this android app and saw that the default view is exactly that. I would like to replicate this on desktop, but I'm not familiar enough with Android apps to be able to locate the code that calls cards in this way.

My ultimate goal is to have all assigned cards end up in a user's personal calendar. That way, when they subscribe with a client like Lightning (Thunderbird), and someone assigns a task to them from any board, they see it in their native calendar as either a to-do or an event.

This already works on a per-deck basis, but it's not realistic to ask a user to subscribe to a new calendar for each board. My hope is that I can figure out what call you're using to return all cards assigned to your user, and than parlay this into a custom CalDAV call that will return the results as a CalDAV calendar. Any help would be appreciated.

**Comment by stefan-niedermann** [comment]
Are you talking about the "Upcoming cards" view? (First item in the sidebar of the Deck Android App)

It works as described here: https://upcoming-analyzer.niedermann.it/ and it is also available in the Deck server app.

Be aware though that the CalDAV implementation of Deck is still missing write capabilities, there exist various issues in the repo of the Deck server app regarding this topic...

**Comment by stefan-niedermann** [comment]
Closing due to missing feedback.

**Comment by morgannunan** [comment]
So sorry for the slow reply, and thanks for creating this interactive page to explain the way upcoming cards work. I think you answered my real question when you pointed out that CalDAV has no write capabilities for the Deck app. I would be willing to use Deck, and just keep all tasks on a single, large deck, and share this with others—but if they can't remove or change those tasks in their client, then this isn't going to work.

The alternative would be to use the normal Tasks app, and assign tasks to others. From what I can see, this isn't possible. You can share the calendar, but you can't share individual tasks and you can't assign them, either. I thought I was seeing that maybe this is possible with Circles, but it's not clear to me.

I think Tasks and Deck could potentially become a single app, with either a kanban view or a list view. That's easy for me to say from my armchair, though. It might be overly complicated, or undesirable.
