### ISSUE TITLE
Feature Request: Kanban board view

### ISSUE THREAD

**Issue by almereyda** [stefan-niedermann/nextcloud-deck#1544]
**Is your feature request related to a problem? Please describe.**

As a user of the Deck app, I need to organise my workflow on a Kanban view, in order to benefit from encoding flow information in the visual arrangement.

**Describe the solution you'd like**

The Android app also has an overview Kanban view, which allows to display columns, filter and rearrange cards side by side.

**Comment by stefan-niedermann** [comment]
Well. We have columns, filters and one can rearrange cards by drag and drop to other lists. To be honest, not sure what exactly you are missing, so please add a screenshot or mockup about what you are missing.

**Comment by stefan-niedermann** [comment]
Closing due to missing response. Please feel free to reopen the issue, otherwise referencing to my [last comment](https://github.com/stefan-niedermann/nextcloud-deck/issues/1544#issuecomment-1890930448).
