### ISSUE TITLE
Feature request: alphabetise list

### ISSUE THREAD

**Issue by 31337-4554551n** [stefan-niedermann/nextcloud-deck#1545]
A request for an option to alphabetise the cards in a list by title.
ideally in the add list/move list/etc drop down menu.

Handy for things like shopping lists.
I use a board with a have and need list, with photos, expiry dates etc and move cards between.
would be really handy to be able to alphabetise the have list to easier find things instead of moving the cards back into the right place each time.

**Comment by stefan-niedermann** [comment]
Unfortunately we currently have no plans to implement another sorting order for lists. However, you can open feature request in the [Deck Server app repository](https://github.com/nextcloud/deck/issues/new?assignees=&labels=&projects=&template=Feature_request.md) - if it will get implemented there, it is likely, that we also add this feature to the Deck Android app.

**Comment by 31337-4554551n** [comment]
I'm sorry, what do you mean by "another" sorting order?
There's no sorting at all, only filtering out specific cards-am I missing something?

**Comment by stefan-niedermann** [comment]
Each card has an `order` property (which can not be set manually, but via drag and drop). Cards in each list are sorted by this `order` property.
