### ISSUE TITLE
Export / Backup Data 

### ISSUE THREAD

**Issue by Detzi88** [stefan-niedermann/nextcloud-deck#1555]
Hey,
I lost access to my server and have all my cards synced to my phone. It would be really nice if i just could export all my cards via the android app and transfer it to my new Account.

Thanks for reading
Detzi

**Comment by stefan-niedermann** [comment]
Thank you for your suggestion.

However: The Deck Android App is **not** a proper backup or recovery tool for various reasons¹. Also an export / import feature is not on our roadmap as it simply does not belong into a client. We have no plans to integrate such a feature at the moment. There *are* `occ` commands for your server, they should be used for exporting stuff, and I even think the Web UI offer some similar export feature.

You should contact your server admin and ask him to reset your instance to the last backup. If no backups are available, you should switch to a hoster that handles user data reasonable and more carefully. If you are hosting your instance yourself: Sorry, but it is not the job of each and every client app to include backup mechanisms. This is clearly a job of the administrator and only this way it is possible to restore a complete instance, not only partial data.

However, if you have root access to your smartphone: Everything is stored in a `sqlite` database, maybe you can extract some really important data this way.

Kind regards,
Stefan

¹ For example only partial data is available, attachments are not synchronized, other data from your account was not included in this backup
