### ISSUE TITLE
Implement new "mark as done"

### ISSUE THREAD

**Issue by pschopen** [stefan-niedermann/nextcloud-deck#1556]
In the web version (1.12.0) now cards can be marked as done. Would be good if the android app had that, too.

**Comment by stefan-niedermann** [comment]
Will be published with Deck Android `1.24.0`

**Comment by rogercreagh** [comment]
Err - I'm using v1.24.1 but I can't find any way to mark a card as Done. Where is it hidden?

**Comment by stefan-niedermann** [comment]
![Screenshot_20240904-125355_Nextcloud Deck](https://github.com/user-attachments/assets/a2b2efec-53ff-4bf9-b01b-904c9ef8310b)

The big fat purple button was too obvious, wasn't it? 😆

**Comment by rogercreagh** [comment]
I'm sure it would be blindingly obvious if it wasn't invisible 8-(
![image](https://github.com/user-attachments/assets/86d7e63e-1b26-4ea8-a27d-9d80fc436ab7)

**Comment by stefan-niedermann** [comment]
Well, in this case: Which version exactly are you using on Deck Android and on Deck server?

**Comment by rogercreagh** [comment]
Ah, maybe that's the problem - android app version 1.24.1 and NC Deck app 1.8.8 - but it says that version is up to date.

I see that the OP in this thread refers to web version 1.12.0 but that doesn't appear to exist on my system and it reports 1.8.8 as being the current version.

I wonder how I'm supposed to update it (and whether any other apps are also missing updates)

NC server version is 25.0.13 - I wonder if that is the problem. I seldom visit the NC server interface (if it ain't broke don't fix it) as I never use it - NC is just a file and data store for me and I can do without all the online apps. I guess I'll do some maintenance and see if that enablles the Done facility.

Sorry for wasting your time, and thanks for the prompt.

**Comment by stefan-niedermann** [comment]
No problem, but as you guessed yourself: The server has to support it (and Deck Android recognizes this feature and en/disables it accordingly on Android)
