### ISSUE TITLE
Share to card as todo item

### ISSUE THREAD

**Issue by jurgenhaas** [stefan-niedermann/nextcloud-deck#1558]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the solution you'd like**

Sharing ftom other apps is wirking great and currently allows to add to an existing card either by adding as a comment ir adding to the description.

A third option to add to the description as a todo item would be great.

**Comment by stefan-niedermann** [comment]
This has been implemented and will be part of Deck Android `1.24.0` :slightly_smiling_face:

**Comment by jurgenhaas** [comment]
Oh, wow. This is super cool. Thank you so much.
