### ISSUE TITLE
due date not properly updated

### ISSUE THREAD

**Issue by desperateCoder** [stefan-niedermann/nextcloud-deck#156]
**Describe the bug**
On creating a card the due date isn't saved on server, so it disappears, but we have known that.
But then setting a date with time, the time somehow changes and can't be updated anymore.

**To Reproduce**
1. Change due date and save

**Expected behavior**
Due date is set

**Comment by stefan-niedermann** [comment]
Hint for myself: Maybe `c.getTime()` should be passed here:

https://github.com/stefan-niedermann/nextcloud-deck/blob/master/app/src/main/java/it/niedermann/nextcloud/deck/ui/card/CardDetailsFragment.java#L407

**Comment by stefan-niedermann** [comment]
Hint for myself: `activity.setDueDate(...)` should be called on `onTimeSet()` analog to `onDateSet()` too:

https://github.com/stefan-niedermann/nextcloud-deck/blob/master/app/src/main/java/it/niedermann/nextcloud/deck/ui/card/CardDetailsFragment.java#L417

@desperateCoder can you confirm, that the issue only is about the `time` and not about the `date`?

**Comment by desperateCoder** [comment]
Yes. Setting the date works fine, even a changed time is persisted. The issue only occurres  when you don't change the date
