### ISSUE TITLE
Card attachments do not open with the app due to incorrect links generated

### ISSUE THREAD

**Issue by user8446** [stefan-niedermann/nextcloud-deck#1577]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Deck Android app, neither the [Deck server app](https://github.com/nextcloud/deck/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

Hi,

When opening an attachment from a card (PDF file for example), the link generated from the app is as follows:

`https://<server>/f/226`

This generates a "Not Found - The requested URL was not found on this server" page.

When opening the same attachment either from desktop or a mobile browser using the Nextcloud deck web page, the link generated is as follows:

`https://<server>/index.php/f/226`

and the PDF opens as expected.

Using the app is not including the `index.php` in the URL.

Thank you

### Deck Android version

1.23.4

### Deck server version

1.11.3

### Nextcloud Android version

3.27.0

### Nextcloud version

27.1.4

### Device

Pixel 6a

### Android Version

14

### App Store

- [ ] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

**Comment by stefan-niedermann** [comment]
Thanks, this will be fixed in `1.24.0`, in fact it is already fixed on the `master`.:)

**Comment by user8446** [comment]
Great thank you!!
