### ISSUE TITLE
Filenames are not shown for jpg attachments

### ISSUE THREAD

**Issue by user8446** [stefan-niedermann/nextcloud-deck#1579]
Hi,

When there is a jpg attachment to a card, the filename is not shown in the app like they are with pdf attachments. I have image previews turned off, so there is no way of knowing which is which:

![Screenshot_20240205-140102](https://github.com/stefan-niedermann/nextcloud-deck/assets/18019245/e4d3fffa-e885-4159-95a4-e3581fba646c)

---

In the browser view, the filenames are shown:

![Screenshot 2024-02-05 140942](https://github.com/stefan-niedermann/nextcloud-deck/assets/18019245/b0d82d0e-04c2-4917-959b-6326cff3508e)

Showing the filenames could also somewhat solve https://github.com/stefan-niedermann/nextcloud-deck/issues/1222

Thank you for the development!

### Deck Android version

1.23.4

### Deck server version

1.11.3

### Nextcloud Android version

3.27.0

### Nextcloud version

27.1.4

### Device

Pixel 6a

### Android Version

14

### App Store

- [ ] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

**Comment by stefan-niedermann** [comment]
Click on the attachment, it's in the toolbar.

![Screenshot_20240205-232211_Nextcloud Deck](https://github.com/stefan-niedermann/nextcloud-deck/assets/4741199/4e56236e-d141-4c7d-9d5c-1b5587a230a3)

**Comment by user8446** [comment]
Ah ha, thanks Stefan, thanks for pointing that out - I completely overlooked that!

Certainly not an issue to click each one with one or two attachments, but with a long list of attachments the only way to find the one being searched for would be to click on each one until found.

**Comment by stefan-niedermann** [comment]
Thank you for your proposal. We currently do not have any plans to implement this. The use case seems uncommon for me, Deck is for managing cards, not for files. Balancing the need to see the (quite technical) file name directly everywhere with cluttering the UI for everywhere seems not reasonable in my opinion. I hope you are able to deal with opening your image attachments and read the file name there.

**Comment by user8446** [comment]
Thanks, I understand it's not on the roadmap now. 

However, in the future if it ever is the use case is quite common. 

For project management attachments can be an integral part of a card. For example, a card can be "design ideas" and the attachments are design1.jpg, design2.jpg, etc. 

Also, PDF's display the file name already in deck for android. 

It's an extra step but for now I will convert the jpg to pdf and then attach to the card. 

Thank you
