### ISSUE TITLE
URLs for attachments are wrong

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#158]
...and result in an `403`-error.

When opening an attachment from the web view, the `cardId`-property in the URL is different from opening the same attachment from the android app.

Maybe the error is caused by using `localId` instead of `remoteId` of the card.

**Comment by stefan-niedermann** [comment]
@desperateCoder please change `cardId`-property in `Attachments.java` to remote card id or add another property like `remoteCardId`.

**Comment by desperateCoder** [comment]
You are in the detail view of the card. Any more questions?

**Comment by stefan-niedermann** [comment]
![grafik](https://user-images.githubusercontent.com/4741199/65700911-bb0ae580-e080-11e9-831e-5493571d580a.png)
