### ISSUE TITLE
Nextcloud Deck App

### ISSUE THREAD

**Issue by iprogrammar** [stefan-niedermann/nextcloud-deck#1589]
### Is your feature request related to a problem? Please describe.

I think it's a shame that the 1.24.0 update has not yet been released. In how many days can I expect it? 

### Describe the solution you'd like

 Among other things, the "mark as done" function has now become essential for me.

**Comment by stefan-niedermann** [comment]
1.24.0 has been tagged and released yesterday, including the "mark as done" feature. It will be available on F-Droid in a few days, it is available at the Play Store beta channel today and the rollout for all Play Store users will approximately take a 2 weeks. We are doing a staged rollout to avoid negative effects on all users in case of a bug.

Loving your engagement and motivation (you apparently just created a GitHub account just to ask for the next release), but please refrain from further asking about any release dates. We are doing this in our freetime and guess what I am *not* doing every time I have to answer this kind of questions? Right.
