### ISSUE TITLE
Double-clicking card opens EditActivity twice

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#159]
Remove click listener after first click

**Comment by desperateCoder** [comment]
still occurs!

**Comment by stefan-niedermann** [comment]
I will look for each `new Intent` and set the flags `intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_SINGLE_TOP | Intent.FLAG_ACTIVITY_NEW_TASK);`.

This should solve the problems.
