### ISSUE TITLE
It says a different version of the app thhan what i have? i dont know whats going on

### ISSUE THREAD

**Issue by Mrs-Feathers** [stefan-niedermann/nextcloud-deck#1646]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Deck Android app, neither the [Deck server app](https://github.com/nextcloud/deck/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

1. open the app
2. sign into nextcloud account
3. see error

### Expected behavior

1. open app
2. sign into nextcloud
3. no error

### Deck Android version

1.24.1

### Deck server version

1.13.0

### Nextcloud Android version

3.29.0

### Nextcloud version

28

### Device

galaxy flip 3 5g

### Android Version

14

### App Store

- [X] Google Play Store
- [ ] Google Play Store (Beta channel)
- [ ] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

App Version: 1.24.1
App Version Code: 1024001
Server App Version: 0.6.4
App Flavor: play

Files App Version Code: 30290090 (PROD)

---

OS Version: 5.4.254-qgki-28575149-abF711U1UES7IXF1(F711U1UES7IXF1)
OS API Level: 34
Device: b2q
Manufacturer: samsung
Model (and Product): SM-F711U1 (b2quew)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP-Anfrage ist fehlgeschlagen mit HTTP-Statuscode: 401
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown Source:0)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.RuntimeException: HTTP StatusCode wasn't 2xx:
Got [HTTP 401] for Call [GET http://localhost//ocs/v2.php/cloud/capabilities] with Message:
[<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>997</statuscode>
  <message>Unauthorised</message>
 </meta>
 <data/>
</ocs>
]
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.buildCause(RequestHelper.java:87)
	... 5 more

**Comment by stefan-niedermann** [comment]
Hmmm 🤔 

> http://localhost//ocs/v2.php/cloud/capabilities

Where are you hosting your cloud? Any public server? Only in your LAN? (Maybe via VPN?) Only locally on your PC/Notebook?
This seems to be off, not even the capabilities endpoint cna be reached (at this stage Deck itself doesn't even matter, it's a core Nextcloud endpoint).

Have you any access logs to see whether your server actually received a request?

Are you using any other app using Single Sign On, for example Notes Android or News Android?

**Comment by stefan-niedermann** [comment]
Out of curiosity: Do you have a <kbd>Space</kbd> or a <kbd>@</kbd> character in your username and / or password? This might worth some investigation given I read it a few times in the past. Did you also try to clear the storage of both, Deck Android and Nextcloud Android as described in the FAQ? Even if the mentioned encoding issues with some special characters are fixed now, it is totally possible that you set up your Nextcloud Android app before the fix was shipped.

**Comment by stefan-niedermann** [comment]
Closing due to missing feedback.
