### ISSUE TITLE
Transparent Widget Background?

### ISSUE THREAD

**Issue by trash-it** [stefan-niedermann/nextcloud-deck#1707]
### Is your feature request related to a problem? Please describe.

The Widget Background is pure black. 

### Describe the solution you'd like

Would be nice if it could set to be transparent :)

**Comment by stefan-niedermann** [comment]
Thank you for your proposal.
However, we have currently no plans to implement a transparent background for widgets, which not only would require [additional settings](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-dont-you-make-an-option-for) but also has accessibility issues give one does not know the background and which font color should be used (light or dark), and on noisy wallpapers both will be wrong.
