### ISSUE TITLE
Description not saved

### ISSUE THREAD

**Issue by kai11** [stefan-niedermann/nextcloud-deck#173]
**Describe the bug**
Descruption of new card is not saved

**To Reproduce**
1. Go to any board with columns
2. Click on + floating button.
3. Fill card and description
4. Save
5. Card title is saved, description is not

**Expected behavior**
Description must be saved - like it is for exsiting cards.

**Smartphone (please complete the following information):**
 - Device: Moto Z Play
 - Android-Version: 8
- Android Nextcloud Deck version 0.0.10 (compiled, not fdroid)

**Comment by kai11** [comment]
Randomly description not saved for old cards as well sometimes - but no exception and I was not able reliably reproduce this problem

**Comment by desperateCoder** [comment]
Hi @kai11,
thanks for your report! This is a known issue at the server side: https://github.com/nextcloud/deck/issues/1138

It is already fixed, but not released yet afaik. As soon you update the server app with a version including the fix, it should start to work.

Regarding to the updates: this schouldn't happen, so please keep an eye on this. If you figure out what exact constellation leads to this issue, just write it here. I couldn't reproduce it yet.

**Comment by stefan-niedermann** [comment]
So basically the issue is already resolved.

@kai11 please test this as soon as the next server app version has been released an reopen this issue in case it still occurs.

Also:

> Regarding to the updates: this schouldn't happen, so please keep an eye on this. If you figure out what exact constellation leads to this issue, just write it here. I couldn't reproduce it yet.

Thanks for reporting :)
