### ISSUE TITLE
Rename column dialog title says Add column

### ISSUE THREAD

**Issue by kai11** [stefan-niedermann/nextcloud-deck#174]
**Describe the bug**
in title.

**To Reproduce**
1. Go to any board wuth columns
2. Click on 3 dots
3. Select Rename column
4. See dialog with title Add column

**Expected behavior**
Must be Rebame column

**Smartphone (please complete the following information):**
 - Device: Moto Z Play
 - Android-Version: 8
 - Android Nextcloud Deck: 0.0.10

**Comment by stefan-niedermann** [comment]
This has already been fixed on master in bad7522 :) Thanks for reporting.
