### ISSUE TITLE
Make user and label assignments cancelable

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#180]
When one edits a card and assigns/unassigns a label or user, then the current behavior does execute a network request directly, without saving the card.

Pressing "cancel" does therefore not really "cancel" the edition, because the (un)assignments are already performed and synchronized.

@desperateCoder can i simply fill up the `List<Label/User>` of the card instead just as we are currently doing it in the "Create"-Mode? So that the changes are only synced up as soon as i press "Save"?

Note: This only affects "Editing" cards. We still need to keep direct (un)assignments e.g. if we are displaying a column and directly (un)assign ourself from the three-dot-menu of a card.

**Comment by desperateCoder** [comment]
@stefan-niedermann not out of the box, but we can make this work on Saturday of course.
