### ISSUE TITLE
Enhance modified detection for pressing back button in edit mode

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#181]
# Current behavior

In `EditActivity` is a boolean flag `modified` which is set to `true` whenever a user makes changes.

This has two drawbacks:

1. It is set unnecessary every time a change is made
2. If one changes e.g. the `title` from `A` to `B` and back to `A`, the flag is currently `true`, even if there are no changes

# Proposal

- [ ] Implement copy constructor in all needed places (@desperateCoder)
- [ ] Wheb going into `EditCardActivity`, clone the `FullCard` after fetching it
- [ ] When exit the `EditCardActivity`, compare current `FullCard` with cloned `FullCard` via `.equals()`
- [ ] Remove oitdated `modified`-flag

(Original proposal was to use `hashCode`, but this idea was abonded because of the risc of dataloss in case of a collition.)

**Comment by desperateCoder** [comment]
@stefan-niedermann Short answer is no. The hash code can collide, even if the objects differ. That's not how hash code works. What you need is a deep copy and equals.

**Comment by stefan-niedermann** [comment]
So i guess Android Studio easily allows one to generate a `@Overide clone()`-method? If we do this on all our models, at least in `FullCard` and all it's children, this should be enough, shouldn't it?

**Comment by desperateCoder** [comment]
I'd prefer a copy constructor, since clone has some pitfalls, afaik intellij would help you here, too. But yeah, that should make it work. 

But we have to be aware, that the equals method won't do what we need out of the box, when it comes to comparing lists. But i'd say we'll handle that.
