### ISSUE TITLE
Title field should have focus when creating a new card

### ISSUE THREAD

**Issue by juliushaertl** [stefan-niedermann/nextcloud-deck#191]
Since the title is the most important part of a new card, the input field should be focused automatically.

**Comment by stefan-niedermann** [comment]
![grafik](https://user-images.githubusercontent.com/4741199/67147962-3172c000-f29a-11e9-8673-47a1585c6da3.png)

**Comment by juliushaertl** [comment]
Wow that was fast :heart:
