### ISSUE TITLE
Show more characters for the label text

### ISSUE THREAD

**Issue by juliushaertl** [stefan-niedermann/nextcloud-deck#192]
I know this was discussed at some point but after using the Android app for a while I think the two character limited labels on cards do not give enough context. Especially when using multiple labels with the same color, e.g. for representing state or categorization the text is kind of crucial to get an overview. I would propose to go back to the original version and show the full label text. Maybe we can show them more compact when they exceed one line?

**Comment by stefan-niedermann** [comment]
Fixed in version `0.7.0`.
