### ISSUE TITLE
Can't create new card

### ISSUE THREAD

**Issue by loicvh** [stefan-niedermann/nextcloud-deck#195]
**Bug description**
When creating a new card, it is not possible to edit any field. If I let it blank, the card is created but yields to an error if I want to edit it.

Note that if I create the card from the web UI, the modification via nextcloud-deck works as a charm.

**To Reproduce**
1. Create a card from android nextcloud-deck
2. Try to modify any fields, they are locked
3. Exit with the fields empty
4. Try to edit the untitled card
5. Get the following error

```
Version: 0.0.11

java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.ActivityDataProvider.getAllFromServer(ActivityDataProvider.java:24)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doSyncFor(SyncHelper.java:33)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$syncActivitiesForCard$3$SyncManager(SyncManager.java:216)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$e-OqJalvFBpByNw7Yobk6JhjZH8.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:764)

```

**Expected behavior**
Possibility to create a new card from the android app.

**Smartphone**
 - Device: Samsung A3 2016
 - Android-Version: 9 (Lineage OS)

**Comment by desperateCoder** [comment]
hi @loicvh thanks for your report! we had already found this issue, too, it is already fixed in version 0.0.12, i think the update is already available on F-Droid.

Yesterday we released 0.0.13 with a whole bunch of fixes and features, i guess it will be available these days on F-Droid. So stay tuned! 

Feel free to close this issue, if the update fixes it for you!

**Comment by loicvh** [comment]
@desperateCoder Indeed, I just updated via F-droid and everything works. Thank you for the (incredibly fast) answer.

**Comment by desperateCoder** [comment]
You're welcome! Thank you for using our app, even if it's broken sometimes and thanks for reporting any issue, that helps us a lot!
