### ISSUE TITLE
Due date is black in dark mode

### ISSUE THREAD

**Issue by nickvergessen** [stefan-niedermann/nextcloud-deck#201]
**Describe the bug**
Have a card with a due date.
Enable dark mode.
Try to read the due date.

![IMG_20191031_094709](https://user-images.githubusercontent.com/4741199/67932087-8e884300-fbc3-11e9-8d30-c2c5cc6516ec.jpg)

**Comment by stefan-niedermann** [comment]
Confirmed, this happens if the due date is in the future and not marked yellow nor red.
