### ISSUE TITLE
Moving cards to another column sets the due time to 0:00

### ISSUE THREAD

**Issue by cddf** [stefan-niedermann/nextcloud-deck#204]
**Describe the bug**
When moving a card with due date to another column the time is changed to 0:00

**To Reproduce**
1. Create or choose a card with due date and time > 0
2. Move it to another column
3. See the time is now 0:00

**Expected behavior**
The time should not change.

**Smartphone:**
 - Device: LG G5
 - Android-Version: 8

**App version**
0.0.12 (F-Droid)

**Comment by desperateCoder** [comment]
Hi @cddf!
Thanks for your report! 
I guess this is still a server-issue. It is already fixed afaik, but not released, right @juliushaertl? 

But i'll have a look at it anyways!

**Comment by cddf** [comment]
By the way, thanks for the nice and fast improving app!

**Comment by desperateCoder** [comment]
@juliushaertl @cddf just dug into this, i think it's kind of our fault. I am sending a wrong timestamp as it seems, yet no idea why. Sorry for falsely accusing the server! :smile:

**Comment by desperateCoder** [comment]
> By the way, thanks for the nice and fast improving app!

You're welcome! We are proud that so many people are interested in our work, so stay tuned and tell us anytime, when something is wrong!
