### ISSUE TITLE
Comments 💬

### ISSUE THREAD

**Issue by kai11** [stefan-niedermann/nextcloud-deck#207]
**!! Branch: comments !!**

**Is your feature request related to a problem? Please describe.**
Right now Activity tab on Edit card screen have readonly activities only.
On Deck web app I can add comments there.

**Describe the solution you'd like**
Ability to add comments to Card Activities.

**Describe alternatives you've considered**
ATM I add comments via web interface, it's cumbersome.

**Comment by desperateCoder** [comment]
@stefan-niedermann please implement the UI and the `SyncManager` stub, then I'll fill the `SyncManager` part

**Comment by stefan-niedermann** [comment]
@desperateCoder UI part is done, just toggle `CardActivityFragment::101` and implement `SyncManager::addCommentToCard()`

**Comment by ImaCrea** [comment]
Just tested it today, and excited this issue is a work in progress. Most of the work on our side is happening in the comments. Thank you very much for porting this app, soon we'll be able to totaly jump off Trello! <3

**Comment by desperateCoder** [comment]
For further implementation: The web-UI makes the following request:
* POST
* https://my.fancy.nextcloud-domain.com/remote.php/dav/comments/deckCard/338/
* Content-Type: application/json
* response: 201
* Body:
``` Javascript
{
"actorType":"users",
"objectType":"deckCard",
"actorId":"my-user-name",
"actorDisplayName":"my-display-user-name",
"verb":"comment",
"message":"fancy comment\n",
"creationDateTime":"Mon, 16 Dec 2019 18:14:10 GMT"
}
```

**Comment by desperateCoder** [comment]
Development in Branch: feature/comments

This feature may take some time, since the server endpoint is very inconsistent, e.g. an update has the http method "PROPPATCH" and needs a huge, creepy XML body for a simple update task.

Also it's gonna be hard getting this to work offline as well, since i have to post the stuff above, but i get it back from the server as an activity. 

The feature itself sounds really easy to implement, but i'm afraid this is going to be a mess. 

So: sorry, hang on, there **is** work in progress!

**Comment by desperateCoder** [comment]
So, after further investigation, I decided to ask our server-friend @juliushaertl, if he could give me a hand with this: https://github.com/nextcloud/deck/issues/1473

This would make things much easier, not only for us but anyone using the Deck-REST-API.

**Comment by desperateCoder** [comment]
For anyone waiting for this: Our friend @juliushaertl has already built the server part for us (not released yet, i'm working on a nightly build).

As you can see above, here is happening a lot now. Sorry for the delay!

Note: we only can release this feature, as soon as the server-app is released, too. This might also take a while, but be sure, we didn't forget you guys!

**Comment by desperateCoder** [comment]
Yeah, that`s pretty much it from my perspective for now. 

@stefan-niedermann i think you can start making the UI nice and shiny. I bet there are some methods missing, but i think the basic stuff should be there.

**Comment by stefan-niedermann** [comment]
So, basically one can read and write comments now.

There are a few things left, which i will fix in the next few days, but it's mainly some visual & fancy stuff.

**Comment by stefan-niedermann** [comment]
`0.5.0` will feature support for comments.
To be able to use this feature, the server app needs to be at least version `1.0.0-alpha1`. So just be patient until the new major version of the server app has been released and then you will be able to use comments :)

**Comment by kai11** [comment]
Perfect. Waiting for server app

**Comment by stefan-niedermann** [comment]
# Sneak preview

![Screenshot_20200328-090322_Nextcloud_Deck](https://user-images.githubusercontent.com/4741199/77818485-0e62fc80-70d3-11ea-9c55-fec3a6d72fd6.png)

**Comment by kai11** [comment]
Server app v 1.0.0 released and comments work fine in Android app. Thanks for this huge effort.

**Comment by stefan-niedermann** [comment]
Great to hear that everything works as expected.

We will enhance the comments area as soon as we ironed out some basty remaining bugs :)

**Comment by desperateCoder** [comment]
@kai11 you're welcome, buddy! Glad to hear nice words here and then, not only bug reports 😀
