### ISSUE TITLE
No mark of the selected column

### ISSUE THREAD

**Issue by Ricomanda** [stefan-niedermann/nextcloud-deck#209]
There is no mark (the white line under the column name) when pushing a card from one column to another.
Swiping through the columns doesn't change the position of the line so I can't see where I drop the card.

**Comment by desperateCoder** [comment]
Holy cow... Never recognized that... You're right!

**Comment by Ricomanda** [comment]
**Describe the bug**
Moving a card does not change the column marker (white line under column name).

**To Reproduce**
Steps to reproduce the behavior:

- hold and push a card to a screen corner
- the column is switched

**Expected behavior**
The mark should hit the right column.

**Hard- and Software**

- Deck v0.0.14 (v0.6.6 server version)
- Lineage OS 16.0
- BQ Aquaris X
- NextCloudPi 16.0.5
- Raspberry pi 3 B.

**Comment by stefan-niedermann** [comment]
Thanks for the report! This issue has been fixed, please wait for the next release :)
