### ISSUE TITLE
Implement proper due date coloring 

### ISSUE THREAD

**Issue by AndyScherzinger** [stefan-niedermann/nextcloud-deck#21]
@juliushaertl can you point me to the code part of the server app where you set the different colors on the due date?
Highly appreciate your feedback :)

**Comment by juliushaertl** [comment]
It is defined here: https://github.com/nextcloud/deck/blob/master/css/style.scss#L511 but the variables used are some from the server and some calculated. Those result in the following:

The state can be found in the card data provided by the server as value of overdue in the cards json:

| value of overdue | description | color |
|---|---|---|
| 0 | future: greater then 1 day until duedate  | `no color` |
| 1 | due soon: 1 day until duedate (due tomorrow) |`#ffc53a`|
| 2 | due now: 0 days until duedate (due today) |`#eca700`|
| 3 | overdue |`#e9322d`|

**Comment by AndyScherzinger** [comment]
I am fine calculating them on the client which is what I was planning to do.

One question regarding the calculation: Are you doing this wit a day precision or on the timestamp itself, e.g.
Due Date: 2.1.2019 8:00am
* client time 1.1.2019 7:00am
* client time 1.1.2019 9:00am

So with day precision both would be overdue->1 using the timestamp 7am would be 25hrs so overdue->0 and 9am would be 23hrs so overdue->2
Same scenarios can be created within the same day for overdue->2 or overdue->3

**Comment by AndyScherzinger** [comment]
Foudn it miyself, day-precision, implemented via #26 :)
