### ISSUE TITLE
Wrong reminder time

### ISSUE THREAD

**Issue by Ricomanda** [stefan-niedermann/nextcloud-deck#210]
Entering a reminder, e.g. 16:15 leads to a 05:15 reminder.

**Comment by Ricomanda** [comment]
**Describe the bug**
Entering a reminder, e.g. 16:15 leads to a 05:15 reminder.

**To Reproduce**
Steps to reproduce the behavior:

- create a new card
- enter a reminder time, e.g. 16:15
- close the card
- reopen it
- now the time is set to 05:15

**Expected behavior**
The time should not change.

**Hard- and Software**

- Deck v0.0.14 (v0.6.6 server version)
- Lineage OS 16.0
- BQ Aquaris X
- NextCloudPi 16.0.5
- Raspberry pi 3 B.

**Comment by desperateCoder** [comment]
Yep, Time-Handling is already on the menu: #205
