### ISSUE TITLE
Attachments 📎

### ISSUE THREAD

**Issue by Ricomanda** [stefan-niedermann/nextcloud-deck#211]
There should be a FAB to load up files in the attachments tab of a card.

**Comment by desperateCoder** [comment]
State of Development:

Today i got file uploads via SSO working. I needed to fork the SSO-library and now have submitted a pull request: https://github.com/nextcloud/Android-SingleSignOn/pull/166

The state right now is that a file can be attached to a card and the attachment is deleted, when it is deleted on server side.

Next steps:
- [ ] Add UI to delete an attachment (@stefan-niedermann)
- [ ] Instantly show freshly uploaded attachment (@stefan-niedermann)
- [ ] Add UI to update an attachment (@stefan-niedermann)
- [ ] Get deletes and updates working (me)
- [ ] Ensure offline capabilities (me) 
- [ ] Talk about "undo delete". Is this desired? Now? (@stefan-niedermann, @Ricomanda, me)
- [ ] Do we need to store attachment-files locally on demand? (@stefan-niedermann, @Ricomanda, me)

**Comment by stefan-niedermann** [comment]
Undo is not needed at this time. we can add support for it later.

I just noticed if you pick the same file 2, the server responds with

`java.lang.IllegalStateException: {"status":500,"message":"File already exists."}`

This is not a good reaction, @juliushaertl you should go for a `409 Conflict` so we can handle this case appropriately.
