### ISSUE TITLE
Push Updates

### ISSUE THREAD

**Issue by jakobroehrl** [stefan-niedermann/nextcloud-deck#215]
It would be great to see changes from other users without reloading. 
On the Browser App we need this get it working: https://github.com/nextcloud/deck/issues/1186

**Describe alternatives you've considered**
Reload the data manually

**Comment by stefan-niedermann** [comment]
This is a problem due keeping a service alive. Especially without Play Services (and we aim to support devices without Play Services and have no plans of creating another flavor for Play Services users).

We'll see what we can dk, but i think Pull to Refresh will be the best thing we can offer under this circumstates.

**Comment by nr458h** [comment]
probably handling it like the news app could be a way: there you can set the option to update when you launch the app.

**Comment by stefan-niedermann** [comment]
This should already be the case, if not i'm definitely for this implementation :) can you double checkt if this is the case yet, please?

**Comment by desperateCoder** [comment]
I think it's synchronizing, but not showing the loading indicator

**Comment by jakobroehrl** [comment]
@stefan-niedermann 
I understand you. But I think an auto update is really important for a collaborative app like Deck.

**Comment by jancborchardt** [comment]
Couldn't it simply use auto-update when the device has Play Services, and when it doesn't there's still pull to refresh? :) Basically progressive enhancement based on what the device supports.

(An option for this seems unnecessary, especially on launch it would be confusing.)

**Comment by qoheniac** [comment]
Could Tutanota's [solution](https://github.com/tutao/tutanota/commit/449c36eac5755571f4c5d28a74dfdc13c3cdc6df) be an option?

**Comment by desperateCoder** [comment]
I just fount this one: https://github.com/nextcloud/deck/issues/256

Feel free to take part in this discussion, since one day we are affected by this as well

**Comment by stefan-niedermann** [comment]
> Couldn't it simply use auto-update when the device has Play Services, and when it doesn't there's still pull to refresh? :) Basically progressive enhancement based on what the device supports.

This would technically be possible but this is straight against my philosophy. Sorry, but i will not include any proprietary libraries in this project.

We already have the background sync (each 15 minutes), this has to be sufficient until a greater solution for all open source apps can be found.

Also: If someone mentions you in a comment, you will get notified via the Files app which supports push notifications (and you *have* the Files app installed since it is a requirement to run Deck :slightly_smiling_face:
