### ISSUE TITLE
widget for the homscreen

### ISSUE THREAD

**Issue by jakobroehrl** [stefan-niedermann/nextcloud-deck#217]
Some homescreen widgets maybe would be helpful:
 - my assigned cards
 - due cards
 - all cards from project X

**Comment by stefan-niedermann** [comment]
Yes. I suggest to split this issue down into one separate issue per widget.

Maybe you can scribble down how you imagine each widget design wise? Like a list? Which information would you consider to be important?

Please describe the widgets as detailled as possible, for example: What does "due dates" display? Cards where due dates have been exceeted or also cards where the due date is very close? What does very close mean?

As i do not use widget by myself, i need as many infos as possible how you would expect it :)

Thanks

**Comment by jakobroehrl** [comment]
Thought about it and tested a lot of apps. I would start with one configurable widget.
List view with Add Card possibility. 
The list view is filterable: 
 - All boards, special board
 - All tags, special tags
 - All, assigned to me

Some screenshots:
![grafik](https://user-images.githubusercontent.com/24530680/70301669-4fb95e80-17fb-11ea-9aeb-ca5721b12063.png)
![grafik](https://user-images.githubusercontent.com/24530680/70301686-59db5d00-17fb-11ea-89b7-8f1a99b2847b.png)
![grafik](https://user-images.githubusercontent.com/24530680/70301713-68297900-17fb-11ea-8ef0-1d9913dc8e57.png)

**Comment by stefan-niedermann** [comment]
Nice research, thank you.

So i see two widgets:

# Cards

The configuration screen should allow (multiple) choices for

- account
- boards
- columns
- labels
- assignees

Then one could filter for the issues one wants to see.

# Overdue

Displays all cards with overdue sorted by overdue (first the ones which are already overdue, then the ones which will overdue in near future)

**Comment by dan0xii** [comment]
I'm putting together a widget that shows the cards in a specified stack. I should have a working prototype in the next week or so and maybe then I could tweak it to meet some of the above criteria.

**Comment by desperateCoder** [comment]
@dan0xii awesome! Thanks in advance, we're looking forward to see it!
If you need any help, let us know!

**Comment by stefan-niedermann** [comment]
woohoo, great to have you here at Deck, too, @dan0xii ! 🎉

**Comment by stefan-niedermann** [comment]
@dan0xii any news? maybe i can offer some help?

**Comment by stefan-niedermann** [comment]
I made a first little step with a simple card widget (mostly to learn something about how android widgets work).

![widget](https://user-images.githubusercontent.com/4741199/81734102-4c558d80-9493-11ea-9674-038d9c2bae8c.png)

I think the most important features for further widget are

- A `BoardWidget` which displays one board (the stacks below each other). We should reuse the existing filter dialog in the configuration screen and should additionally provide an option to select the columns to display
- An `DueDateWidget` widget, which should provide a configuration screen to choose one or multiple accounts, boards and stacks as source for overdue (or "near overdue" cards

If this is okay for everyone, i will close this issue here and open new separate issues for the both planned widgets. Then we can focus on mockups and implementing as those tasks are too big for being handeled all within this issue.

**Comment by dan0xii** [comment]
Sounds good. I have the framework for a stack widget which I'll upload tomorrow.

I'm busy working on the configuration activity but the whole thing needs some work.

-------- Original Message --------

**Comment by stefan-niedermann** [comment]
@dan0xii just invited you as a contributor to this repository. I think this will make collaboration easier, and you can directly work on a branch here instead of a fork if you want :slightly_smiling_face: :rocket:

**Comment by dan0xii** [comment]
Sounds good, thanks. I've created the `stack-widget` branch and it's little more than a framework at the moment. I'm working on the configuration activity and then it should be styling work to do after that.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by The-Ludwig** [comment]
Any News? Already implemented? Is there a beta-app?

**Comment by stefan-niedermann** [comment]
It is currently developed on a branch. You can contribute at anytime if you want, let me know if you are interested 🙂.

We will release it as soon as it is usable 😉

**Comment by stefan-niedermann** [comment]
List widget will be shipped with `1.9.0` - thanks @dan0xii !
For all other wishes please read https://github.com/stefan-niedermann/nextcloud-deck/issues/597 (Filter widget) or open new issues if your idea isn't cover by the Filter widget.
