### ISSUE TITLE
Offline capabilities

### ISSUE THREAD

**Issue by willsALMANJ** [stefan-niedermann/nextcloud-deck#22]
I am very much looking forward to the release of this app. The readme mentions "offline capabilties". What offline capabilties are you planning? A viewer capable of viewing all data from the time of the last sync? I imagine resolving conflicts between changes to two offline instances would get very messy -- will the app be read-only when offline?

**Comment by stefan-niedermann** [comment]
It is planned to be capable of editing when one is offline, and yes, merging might get tricky ;-)

**Comment by desperateCoder** [comment]
Hi @willsALMANJ,
It is planned to have a fully functional offline app, with a bidirectional synchronization function. No worries, I think you'll get what you are looking for.

As you mentioned, there is still a lot of work to do, the merging will get tricky, but we are on it. Just be patient and keep track. If you have more requests, just do it as you already did and tell us.

Best regards!

**Comment by willsALMANJ** [comment]
Thanks for the information. I look forward to seeing how the bidirectional synchronization works.
