### ISSUE TITLE
User avatars not updated on modification

### ISSUE THREAD

**Issue by bpcurse** [stefan-niedermann/nextcloud-deck#231]
If a user's avatar is changed in nextcloud the deck app keeps displaying the old one.

**Comment by stefan-niedermann** [comment]
Yes, only solutuon for now: 

1. Perform a full synchronisation
2. Delete app data
3. Configure the accounts again

We could invalidate the `Glide`-cache after soms time, e.g. one week...? I have not found a perfrct solution yet, ideas are welcome.

**Comment by bpcurse** [comment]
Nextcloud Android Files App handles this quite well. Not only avatar changes, even login screen background modifications.
Could it possibly be of any help to look into the code over there?
Sorry if this is too shortsighted as I'm not into java and the server/deck APIs.

**Comment by stefan-niedermann** [comment]
@tobiasKaminsky do you use `Glide` too for fetching the avatars in the files app? How do you handle caching?

**Comment by mario** [comment]
I use Coil. Glide is not well suited to etags based caching.

**Comment by tobiasKaminsky** [comment]
I created a test branch for switching to glide.
There I used my own ObjectKey, which is a prefix + etag. 
Thus I can easily use glides validation mechanism.

**Comment by tobiasKaminsky** [comment]
At a quick glance I did not see how coil uses etags?

**Comment by stefan-niedermann** [comment]
Looks good. Does the `etag` support work out of the box or do i have to implement this myself? In other words: Will `coil` itself recognize that there is a new avatar automaticall?

**Comment by stefan-niedermann** [comment]
Sorry @tobiasKaminsky i read your comments too late. Can you post a link to your branch here so i can have a look?

**Comment by mario** [comment]
@tobiasKaminsky simply through okhttp caching, IMHO much simpler than any custom stuff that needs to be done with Glide.

**Comment by stefan-niedermann** [comment]
We will stay with Glide for now. Manually Pull Down 2 refresh will clear the Glide cache. This will load the new avatar on the next app start.

This is a workaround until we have proper `ETag`-handling implemented.
