### ISSUE TITLE
Add "Move to" menu

### ISSUE THREAD

**Issue by bk1285** [stefan-niedermann/nextcloud-deck#237]
Assuming a deck with e.g five stacks (1...5), I often end up moving multiple cards from e.g. 2 to 4. Currently, this involves navigating back and forth between column 2 and 4 for each card.

To simplify this task, I'd like to propose a "Move to" drop-down menu, attached to each card, which allows to move a card directly from stack 2 to any other stack. The user still sees the original stack (2 in this case) and can directly repeat this task with the next card.

@stefan-niedermann, what do you think about this approach? For me, it would reduce workload significantly ;)

I really appreciate your work, like the app and look constantly forward for any update :)
Keep up the great work!

Best,
Bernd

**Comment by stefan-niedermann** [comment]
Yes, this is already implemented on master and will be shipped with the next release :)

https://github.com/stefan-niedermann/nextcloud-deck/issues/175

Thanm you for your interest :)

**Comment by bk1285** [comment]
Great! That was quick! ;)
