### ISSUE TITLE
Creating boards not possible

### ISSUE THREAD

**Issue by desperateCoder** [stefan-niedermann/nextcloud-deck#243]
@randy-jr-olive found following behaviour:

[video no board created issue](https://www.youtube.com/watch?v=QSrKwoYb8BM)

@randy-jr-olive can you reproduce this and tell us the steps?

_Originally posted by @randy-jr-olive in https://github.com/stefan-niedermann/nextcloud-deck/issues/239#issuecomment-568769349_

**Comment by randy-jr-olive** [comment]
I've tried to reproduce this issue, but I've had no luck. I'm not sure what was causing this, but it hasn't happened since then. I think if this was just a problem for me then it's probable safe to close this issue. If it happens again I can create a new issue at that point.

**Comment by desperateCoder** [comment]
... or just reopen it 🤷‍♂
