### ISSUE TITLE
Add Deck as a "share to" location

### ISSUE THREAD

**Issue by mentalinc** [stefan-niedermann/nextcloud-deck#248]
**Is your feature request related to a problem? Please describe.**
No issues, just improved usability

**Describe the solution you'd like**
When sharing an item, e.g. a url from chrome, having Deck as an option.
It would be great to then select the board and card (or create a new card) related to the URL.

example:
Have a great idea, search on phone to find a way to do it(it's at hand PC is not).
Find a great article/link etc that could solve something on a card so adding it as a reference would be useful.
Currently I either do the below (slow, or i just email it to myself to later move into a card (which is less than ideal workflow))

**Describe alternatives you've considered**
Sharing to the clipboard, opening the app, finding the board and then the card the share relates to. then pasting the content into the description

**Comment by desperateCoder** [comment]
Hi, thanks for your report! This is something, we also have considered, but we didn't come to a really smooth workflow. We can't imagine how to make it nice and easy, maybe you have an idea? The point is:
* We could have multiple accounts
* We could have multiple boards
* We most probably will have multiple stacks in a board
* We most probably will have multiple cards in a stack
* As you mentioned, maybe we could create a whole new card

We have no idea how to let the user select all these steps without ending up with an absolute UX overkill. Would be almost the same, as opening the app and do it manually, just as now.

Please, if you have any good idea about that, tell us! By now we are concentrated on more basic functionality, so we procrastinated this question 😅

**Comment by Tonus1** [comment]
I'd suggest to add a new card. 

Choose account, board and stack with drop-down menus. 

That's 3 clicks away, best we can have (if I had to share via email it would be account, dest, object for instance).

**Comment by mentalinc** [comment]
Agree, and can all be prepopulated based on the boards and stacks that
exist already.

**Comment by desperateCoder** [comment]
And we always should assume it is a new card? Should it be created at first or at last stack rank?

**Comment by mentalinc** [comment]
Fiar assumption I think for new card, otherwise ends up in a logic
nightmare of which card, and where in the description to add the shared
content...

I'd say add to the bottom of the stack, but could add a toggle to select if
it should be the top or bottom? (but just more UX clutter).

It's almost no effort to put in the correct place once created

**Comment by desperateCoder** [comment]
@stefan-niedermann? Any thoughts? I'd be totally ok with this, but in the end you are going to implement this

**Comment by stefan-niedermann** [comment]
I think i have a better idea:

`CardChooserActivity extends MainActivity`. Then set the title to something like "Send to card" in the `onCreate`-callback. This way the user has the familiar interface and we have way less work. The user can do everything like switching boards, stacks and even add accounts with little important differences:

- Drag 'n' Drop should be deactivated by overwriting `onLongClick`
- Clicking on a card should actuallye *choose* it instead of *open* it
- Clicking in a card needs to set an activity result
- Creation should be disabled for now, this can be added in a later version (let's keep the steps small)

**Comment by stefan-niedermann** [comment]
I added this feature.

It is now possible, to share content (text **and** images) from a 3rd-party app to any card of any stack of any board of any account (lol) you have configured.

Text is currently attached to the description

We will improve the behavior in the future. For example, i plan to let the user decide where text should be placed (above or below description or as a comment) in the future.

If you have any concrete ideas or you are missing anything, just open a new issue :)

**Comment by stefan-niedermann** [comment]
(This feature will be in the next version released **after** `0.3.0`)

**Comment by desperateCoder** [comment]
Woah, didn't know you're working on this! Nice, gj Stefan!

**Comment by stefan-niedermann** [comment]
- Use any share provider (Gallery, Notes, ...)
- Pick "Share to"
- Pick "Deck"
- Browse all boards and stacks, one could even add a new account with this approach
- Clicking on a card will attach the text to the description (or upload the image as an attachment)

| Share | Select |
| --- | --- |
| ![grafik](https://user-images.githubusercontent.com/4741199/76707358-d335f600-66ee-11ea-9458-aa41a8c72c70.png) | ![grafik](https://user-images.githubusercontent.com/4741199/76707361-e2b53f00-66ee-11ea-9ff4-142b64915bb2.png) |

**Comment by mentalinc** [comment]
Excellent thanks so much for implementing this feature look forward to
seeing it released!

**Comment by stefan-niedermann** [comment]
There's another limitation i just noticed. Sendijg data from telegram or from an email-app is not possible at the moment. I think this is because the sent file is not yet physically stored on the phone. We will analyse and enhance this behavior in a future release.
