### ISSUE TITLE
Keyboard doesn't auto pop up when creating new card

### ISSUE THREAD

**Issue by mentalinc** [stefan-niedermann/nextcloud-deck#249]
**Describe the bug**

**To Reproduce**
1. Go to ' any board'
2. Click on ' the plus button to create a new card'
3. new card opens with cursor blinking in the title.
4. See error - keyboard doesn't auto open.
5. need to then click (where the cursor already is) to bring up keyboard

**Expected behavior**
as above, but without having to click on the title to bring up keyboard.

1. Go to ' any board'
2. Click on ' the plus button to create a new card'
3. new card opens bring up keyboard to start typing straight away.

**Smartphone (please complete the following information):**
 - Device: e.g. Samsung Galaxy S9
 - Android-Version: 9
 - Switftkey as keyboard (works as expected in gmail). create new email. to field is highlighted keyboard auto opens.

**Comment by armaccloud** [comment]
We might want to add that, together with the keyboard to pop up, the shift key to be pressed by default since in most cases you'd start a line with a capital letter.

**Comment by desperateCoder** [comment]
Yep, good point!

**Comment by desperateCoder** [comment]
@stefan-niedermann: https://github.com/stefan-niedermann/nextcloud-deck/blob/dea65019e73719acdd962bb2c5adf36e30caff0c/app/src/main/java/it/niedermann/nextcloud/deck/ui/EditActivity.java#L251 

Very annoying, easy to fix, please fix this next!
