### ISSUE TITLE
EmptyContentView is not inflateable on API level 14

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#254]

**Comment by desperateCoder** [comment]
isn't this quite obsolete now? https://github.com/stefan-niedermann/nextcloud-deck/pull/247#discussion_r361801114

**Comment by stefan-niedermann** [comment]
Nope, i guess we have to Switch to `androix.fragment`, i think (not tested) that it crashes up to Android 5
