### ISSUE TITLE
Switch stacks earlier with card drag n drop

### ISSUE THREAD

**Issue by armaccloud** [stefan-niedermann/nextcloud-deck#257]
**Is your feature request related to a problem? Please describe.**
Whenever I switch a card from one stack to another (drag n drop), I have to push quite hard against my phone protector at the edge of the screen before deck switches stacks. This will happen with most phone protector for mine is a pretty general one. 

**Describe the solution you'd like**
Deck should switch stacks a little earlier than right at the outer edge of the screen when dragging a card left or right.

**Comment by desperateCoder** [comment]
But... Why? This is a good point!

**Comment by armaccloud** [comment]
I must have accidentally closed this issue, because for all I knew I just opened it :)

**Comment by desperateCoder** [comment]
@armaccloud what value would you suggest? 
```JAVA
@BindInt(R.integer.drag_n_drop_dp_to_react) // currently this is 20 dp
 int dragAndDropDPtoReact;
```
Should we make it 30 for now? 40? @stefan-niedermann your opinion?

**Comment by armaccloud** [comment]
@desperateCoder I would go with 30, as I think there's just a slight increase necessary.

**Comment by stefan-niedermann** [comment]
Yes, let's increase it to `30` for the next release to get some feedback. We can always increase it in future versions with no effort.
