### ISSUE TITLE
After deletion of board, title of first board is shown empty

### ISSUE THREAD

**Issue by armaccloud** [stefan-niedermann/nextcloud-deck#259]
**Description**
After the deletion of a board, the title of the first (top) board is shown as empty (even though it isn't).

**To Reproduce**
1. Verify the first board in your board list has  an active stack & card
2. Create a new board with a stack
3. Delete the newly created board
4. Verify the name of the top board is now shown as an empty board (even though it's not empty)

**Expected behavior**
Deck to either:
* Default to top board, but showing the boards contents, or
* To show a static page with info, such as (open a board, or create a new board, with arrows pointing the user in the right direction)

**Screenshots**
_Top level (existing) board_
![Screenshot_20200104-070350_Nextcloud_Deck](https://user-images.githubusercontent.com/9272078/71760685-bb0d5380-2ec1-11ea-9d45-9c3f9cf5c7af.png)

_Create new board_
![Screenshot_20200104-070404_Nextcloud_Deck](https://user-images.githubusercontent.com/9272078/71760695-e2642080-2ec1-11ea-8a22-77679294f60c.png)

_New board with stack_
![Screenshot_20200104-070418_Nextcloud_Deck](https://user-images.githubusercontent.com/9272078/71760698-ebed8880-2ec1-11ea-8dd4-c839f94bb873.png)

_Delete newly created board_
![Screenshot_20200104-070430_Nextcloud_Deck](https://user-images.githubusercontent.com/9272078/71760700-f0b23c80-2ec1-11ea-8473-ef19ee6d26e3.png)

_Top board shown without content_
![Screenshot_20200104-070436_Nextcloud_Deck](https://user-images.githubusercontent.com/9272078/71760702-f740b400-2ec1-11ea-80b9-e22a58ebaf0a.png)

**Smartphone:**
 - Device: Oneplus 5T
 - Android-Version: 9

**Comment by stefan-niedermann** [comment]
Will be fixed in `0.7.0` (not yet released).

Thank you.
