### ISSUE TITLE
Max card title length is not enforced correctly

### ISSUE THREAD

**Issue by kbeerepoot** [stefan-niedermann/nextcloud-deck#262]
**Describe the bug**
When an new card is created, it seems that the accepted lable length is indefinite because one can keep entering text. If the entered length of the label exceeds the enforced maximum length in the web interface, though, the card can not be saved.

**Expected behavior**
I expected that the field would refuse any more character entries at the moment that the enforced maximum length in the web interface would be reached, and that the attempt to save the card would then be succesful.

**Smartphone (please complete the following information):**
 - Device: Motorola moto g(6) play
 - Android-Version: 9

**Comment by stefan-niedermann** [comment]
We were not aware of a max length (at least there is nothing in the REST docu).

The limit should be enforced by the backend or removed from the web interface imho.

Maybe you can open a new issue at the deck server repository?

**Comment by desperateCoder** [comment]
@juliushaertl could you please clarify this? I had no idea there was a limit? What are the rules for label creation?

**Comment by kbeerepoot** [comment]
> @juliushaertl could you please clarify this? I had no idea there was a limit? What are the rules for label creation?

In my personal experience, if I am in the Deck app in the web environment and I create a new card, the card label will stop accepting input after a 100 characters but the card can be saved.

If I do the same in the Android Deck app, the field will keep accepting input after a 100 characters but this will create problems saving and/or syncing the card.

**Comment by kbeerepoot** [comment]
> @juliushaertl could you please clarify this? I had no idea there was a limit? What are the rules for label creation?

In my personal experience, if I am in the Deck app in the web environment and I create a new card, the card label will stop accepting input after a 100 characters but the card can be saved.

If I do the same in the Android Deck app, the field will keep accepting input after a 100 characters but this will create problems saving and/or syncing the card.

**Comment by kbeerepoot** [comment]
Sorry, did not mean to close
