### ISSUE TITLE
An empty card can be created, which stays in sync state forever

### ISSUE THREAD

**Issue by armaccloud** [stefan-niedermann/nextcloud-deck#264]
**Description**
An empty card (no content whatsoever) can be created, then the card remains in a sync state.

**To Reproduce**
1. Open a new card by clicking the + button
2. Without entering any information, click the creation button
3. Verify an empty card has been created, with a persistent sync indicator

**Expected behavior**
The card name field should be a mandatory field.

**Screenshots**
![image](https://user-images.githubusercontent.com/9272078/72201537-7f403400-3455-11ea-92a9-d70aae2cb10f.png)

**Smartphone:**
 - Device: Oneplus 5T
 - Android-Version: 9

**Comment by desperateCoder** [comment]
@stefan-niedermann: the reason why this happens is because the server responds with this:
```json
{"status":400,"message":"title must be provided"} 
```

The UI should handle this rather than the transport layer (-> SyncManager)

@armaccloud changing the title to anything non-empty would make it work again.
