### ISSUE TITLE
Adding task

### ISSUE THREAD

**Issue by sh2515** [stefan-niedermann/nextcloud-deck#271]
**Describe the bug**

Creating a task this error came up

**To Reproduce**
1. Go to '.the plus sign..'
2. Click on '..the tick..'

**Expected behavior**

Should see another task added
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [m10
 - Android-Version: [e.g. 8]

**Stacktrace**
```
App Version: 0.0.17
App Version Code: 17
Files App Version Code: 30100090

---

OS Version: 3.18.35+(vXA00000G)
OS API Level: 24
Device: M10
Model (and Product): M10 (M10)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.full.FullStack.getLocalId()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$createFullCard$17$SyncManager(SyncManager.java:502)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$7UomFrsDF0d9oANwwzsN12JJGYM.run(lambda)
	at java.lang.Thread.run(Thread.java:761)

```

**Comment by Bondarz** [comment]
Same.
OnePlus6T - LineageOS 16 - NextCloud (Storageshare by Hetzner)

````
App Version: 0.0.17
App Version Code: 17
Files App Version Code: 30090290

---

OS Version: 4.9.112-g9e3b121(72aad27385)
OS API Level: 28
Device: OnePlus6T
Model (and Product): ONEPLUS A6013 (OnePlus6T)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.full.FullStack.getLocalId()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$createFullCard$17$SyncManager(SyncManager.java:502)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$7UomFrsDF0d9oANwwzsN12JJGYM.run(Unknown Source:12)
	at java.lang.Thread.run(Thread.java:764)

````

**Comment by desperateCoder** [comment]
Hi,
well, thats quite weird. You didn't mention adding a title, in version 17 it should prevent creating a card with empty title.

In case you entered one: can anyone (@sh2515 @Bondarz) provide a video of what exactly you did? I can't reproduce it. 

Did you rotate the phone while testing? If you reinstall the app, does this still happen? What server app version you are working on (you can also find it in the about-page in our app)? 

@stefan-niedermann: we also should include the server-app version in the crash report

**Comment by stefan-niedermann** [comment]
ping @sh2515 @Bondarz please see https://github.com/stefan-niedermann/nextcloud-deck/issues/271#issuecomment-583750700

**Comment by sh2515** [comment]
Hi
Sorry I didn't see your previous message. Since the update I haven't had the issue anymore.

**Comment by stefan-niedermann** [comment]
Thank you for the feedback.

@Bondarz please feel free to open a new issue if you are still getting an error message

**Comment by Chluz** [comment]
Hi, I seem to be getting the same issue,  also on a OnePlus device (3T)
Thanks for developing this great app by the way

**Comment by desperateCoder** [comment]
Hi @Chluz! 
Thanks, we're glad you like it!

What app version do you use? I'm using a OnePlus 3 (no T) and don't get any error here.aybe a update might help out? If not: please tell us the exact steps to reproduce this issue, anything (like rotating the device etc.) May help! If the issue persists, please feel free to open a new issue for this.
