### ISSUE TITLE
due date+time set back to none after creation

### ISSUE THREAD

**Issue by rms-joe** [stefan-niedermann/nextcloud-deck#274]
**Describe the bug**
after creating new card mostly (seen otherwise/working seldomly):
new card shows up with a sync sign (due date+time shown)
sync sign disappears 
card gets shifted to the end
due date and time set back to none

**To Reproduce**
setup: existing board with several cards / colums
1) go to "create new card"
2) name it and set due date + time
3) acknowledge
4) described behavior from above

**Expected behavior**
due date+time persist

**work around**
1) create card
2) don't set due date+time
3) acknowledge
4) set date and time afterwards
5) it persist

**tested with**
 - V 0.0.17
 - Sony XZ1c
 - Android-Version: 9

**Comment by stefan-niedermann** [comment]
Thank you for reporting this issue. This is a known bug on the server and will be fixed in a future release of the server app.

Unfortunately there is nothing we can do on the android client side.

**Comment by stefan-niedermann** [comment]
See https://github.com/nextcloud/deck/issues/1430
