### ISSUE TITLE
After adding label: tap on label-searchbar won't show recommendations

### ISSUE THREAD

**Issue by desperateCoder** [stefan-niedermann/nextcloud-deck#277]
**Describe the bug**
when assigning a label, the recommendations won't show up again

**To Reproduce**
1. Go to edit mode
2. Click on label field
3. Add a label
4. click on label field

**Expected behavior**
recommend me something

**Comment by stefan-niedermann** [comment]
dup of https://github.com/stefan-niedermann/nextcloud-deck/issues/256 ?

**Comment by desperateCoder** [comment]
Dup
