### ISSUE TITLE
Description rendering

### ISSUE THREAD

**Issue by juliushaertl** [stefan-niedermann/nextcloud-deck#28]
Right now, the description is shown directly on the card. I would expect it to be 
- [x] visible in the cards detail view only. 
- [x] Markdown should also be supported when viewing the description.

**Comment by AndyScherzinger** [comment]
At the moment there is no details view actually. But we might be able to implement this via #25.
While there we would like to get some input from designers on how to design the flow and screens. 

cc @stefan-niedermann since he is working on the editing part.

**Comment by AndyScherzinger** [comment]
@stefan-niedermann Sweet! 👍

**Comment by juliushaertl** [comment]
@stefan-niedermann Yes, good idea :+1:

**Comment by AndyScherzinger** [comment]
description visible in details view and not on board/stack has been pushed to master

**Comment by kai11** [comment]
Its more than markdown - checklists / subtasks are very useful too,
https://github.com/nextcloud/deck/issues/53

I think there must be two views - detail view (rendered markdown, checkable checklists) and edit view (raw text).
Right now edit screen have only second view.

**Comment by stefan-niedermann** [comment]
The current implementation will not allow image embedding, but i am pretty sure, we will replace the imementation since the  `RxMarkdow `-library is not maintained anymore.

It's more like a quickwin to render some markdown :)

**Comment by skeal** [comment]
I use version 1.8.2 from fdroid and the markup is shown as text only. Not rendered markup for checkboxes. Am I missing something here?

**Comment by stefan-niedermann** [comment]
@skeal Checkboxes are not yet supported, markdown support is currently rudimentary.

We [plan to use Nextcloud Text for markdown rendering](https://github.com/stefan-niedermann/nextcloud-deck/issues/452) in the long term, which supports checkboxes.
