### ISSUE TITLE
Show an info if server is in maintenance mode

### ISSUE THREAD

**Issue by jakobroehrl** [stefan-niedermann/nextcloud-deck#283]
The files App is showing this:
![grafik](https://user-images.githubusercontent.com/24530680/75430620-df2e6380-594b-11ea-814c-857ae8b8cd2a.png)

**Comment by desperateCoder** [comment]
@tobiasKaminsky how does this work in the files app? Via capabilities endpoint? How can I recognize that?

**Comment by stefan-niedermann** [comment]
yes, capabilities endpoint has a booleam property `maintenance`.

**Comment by desperateCoder** [comment]
@stefan-niedermann what would you need to get this work? We already have this endpoint, maybe I have to parse the flag as well and this would be done, but afaik you don't really call this endpoint that often? Should I add a dedicated endpoint for this?

**Comment by stefan-niedermann** [comment]
We are currently only calling the endpoint if we want to know the server version - this happens only on adding an account and when opening the about activity.

We should fetch the maintenance state every time we open the app **and** if we have an internet connection. In this case it would make sense to check the server version, too on every startup since are already doing the request 🤷‍♂ 

Therefore a single endpoint in the `SyncManager` would make sense. It should also explicitely throw an `OfflineException`, so i can catch it and proceed "offline".

**Comment by tobiasKaminsky** [comment]
If you do any(?) call to a server which is in maintenance mode, you will get back a 503, which you then can use for showing such an info.

**Comment by stefan-niedermann** [comment]
@tobiasKaminsky does this also cover calls to 3rd party apis like deck?

**Comment by tobiasKaminsky** [comment]
Via "channel" is this? OCS? 
I am only sure for webdav.

@juliushaertl heeeeeeelp :-)

**Comment by juliushaertl** [comment]
Yes, all endpoints will return a 503 response in that case.

**Comment by stefan-niedermann** [comment]
@desperateCoder In this case we should think about whether we really want to query the `maintenance`-endpoint each time on app start or if it wouldn't be better to check the response codes on usual syncs to broadcast an event that triggers the UI state (like in the screenshot).

This way we could save an unnecessairy request.

**Comment by desperateCoder** [comment]
✔️ I'll see, if I can handle this somewhere central and then throw a dedicated exception

**Comment by stefan-niedermann** [comment]
That won't be enough because i need to get notified as soon as the next sync works normal again.

Guess we will have to deal with Android Broadcasts.

**Comment by tobiasKaminsky** [comment]
On Files I do it this way:
- if sync/operation fails: show maintenance info (it is only an info)
- upon next sync/operation/app start (which includes a regular refresh=sync) -> either still show info or operation works and thus remove the info

**Comment by stefan-niedermann** [comment]
I added a visible information in form of a snackbar (in case a sync failed) as a quickfix. This issue stays open, because this is not a permanent solution.

**Comment by stefan-niedermann** [comment]
Fixed, will be in `0.7.0` as requested.
