### ISSUE TITLE
📎 Add more sources to upload attachments

### ISSUE THREAD

**Issue by jakobroehrl** [stefan-niedermann/nextcloud-deck#289]
**Is your feature request related to a problem? Please describe.**
new button "camara" within the attachment section to make a photo and upload it directly as new attachment

**Describe alternatives you've considered**
Start the camara App manually, take a pic, open deck go to attachments, click the upload Button, search for the photo, add it

**Comment by desperateCoder** [comment]
Yep, that's a good one!

**Comment by stefan-niedermann** [comment]
Sure, makes sense. I guess we will have either a!expandable floating action button or a bottom sheet like in whatsapo/telegram in the future.

**Comment by stefan-niedermann** [comment]
I have some troubles when receiving files which are not physically on the device yet.

I guess we have to store a local copy of the files in the app-directory and upload it from there, but i do not yet fully understand the concept of the `DocumentProvider`. Knowledge input or a Pull Request is welcome 🙂.

**Comment by q-wertz** [comment]
Maybe this is also related https://github.com/nextcloud/deck/issues/564 and https://github.com/nextcloud/server/issues/10292

**Comment by stefan-niedermann** [comment]
@jakobroehrl @q-wertz please have a look at [this PR](https://github.com/stefan-niedermann/nextcloud-deck/pull/555#issue-439167467) - It would be awesome if you could help testing the new stuff :rocket:  :slightly_smiling_face:

**Comment by stefan-niedermann** [comment]
@jakobroehrl @q-wertz @splitt3r since you were interested in this issue, i'd like to ask you whether you are interested in testing some more improvements we've done before i release it as a beta? :slightly_smiling_face: 

Here is the [`APK`](https://github.com/stefan-niedermann/nextcloud-deck/suites/1474431761/artifacts/25408191) to download and test - feedback is very welcome here.

**Comment by jakobroehrl** [comment]
wow! This is working awesome!

**Comment by q-wertz** [comment]
Looks amazing :tada: 
My only problem was that on first sight I had trouble to find the camera. Might be more intuitive to not have it in the Gallery tab but in a separate one with own symbol?
![Screenshot_20201110-134918~3](https://user-images.githubusercontent.com/20948931/98676841-0bf89e80-2354-11eb-9fb7-94ab96298494.png)

**Comment by stefan-niedermann** [comment]
Hmm, did the upper left item (with the camera symbol) not display a live preview of the camera for you? (because it is black but it *should* display a live cam)

I orientated pretty much at the attachments picker of Telegram and it seemed to be pretty intuitive (for me at least 😆 )

**Comment by q-wertz** [comment]
It is black because it was covered :laughing: 
So everything fine. Maybe just also had the wrong expectations from the previous version/other apps. :+1:

**Comment by stefan-niedermann** [comment]
According to the material guidelines the bottom navigation (which we use) should only host up to 5 items - i planned to add one for audio one for video.

The concept idea is to have one picker per media type and each of the pickers shows a "primary / native" action + previews for quick access.

- camera + images
- native contact picker + direct contacts
- native file picker + downloaded files

and maybe in the future something like
- audio recorder + audio files
- video capturing + videos

But we for sure can still discuss this, maybe you have screenshots of some apps to compare with?

**Comment by stefan-niedermann** [comment]
The current state will be in version `1.12.0` (which is already tagged for F-Droid and available on Play Store beta channel).

Feel free to still discuss this feature in this or a new issue, but it "works as expected" and noone reported any bugs so far, so i thought: "let's get some more feedback from the community" :slightly_smiling_face:

**Comment by aproposnix** [comment]
I don't mean to seem so pedantic but the rounded corners don't feel right when the menu is fully loaded with the round corners. Other than that, this is an awesome new feature. 

![signal-2020-11-10-223042](https://user-images.githubusercontent.com/6204273/98762384-856cad00-23a5-11eb-9d5b-20afa0dee5ff.jpeg)

**Comment by stefan-niedermann** [comment]
Indeed, i will have a look whether we can animate those corners :).

**Comment by q-wertz** [comment]
> According to the material guidelines the bottom navigation (which we use) should only host up to 5 items - i planned to add one for audio one for video.
> 
> The concept idea is to have one picker per media type and each of the pickers shows a "primary / native" action + previews for quick access.
> 
>     * camera + images
> 
>     * native contact picker + direct contacts
> 
>     * native file picker + downloaded files
> 
> 
> and maybe in the future something like
> 
>     * audio recorder + audio files
> 
>     * video capturing + videos
> 
> 
> But we for sure can still discuss this, maybe you have screenshots of some apps to compare with?

I think it makes sense to design it the way you said:+1:

Nevertheless, here are some screenshots how different messengers handle this (if you need some inspiration one day and maybe you don't have one of these :wink:):
![Threema](https://user-images.githubusercontent.com/20948931/98991709-22555480-2524-11eb-9efa-4950e0d26141.png)
![Whatsapp](https://user-images.githubusercontent.com/20948931/98991713-241f1800-2524-11eb-94aa-fcc8d80e8ac6.png)
![Element](https://user-images.githubusercontent.com/20948931/98991719-25504500-2524-11eb-844f-50f1e08ba0af.png)
![Slack](https://user-images.githubusercontent.com/20948931/98991723-26817200-2524-11eb-8d29-d3bd01669bfd.png)

**Comment by jakobroehrl** [comment]
@stefan-niedermann
This is so awesome implemented.
Is there a change to implement this function in Android-talk, too?

**Comment by stefan-niedermann** [comment]
I am not aware of one, but i happily will have a talk with @AndyScherzinger and @tobiasKaminsky if they are interested to adapt the implementation 😉 It should be pretty portable and easy to adapt I think...

Merry christmas and stay well!
