### ISSUE TITLE
Wording of column and stack confusing

### ISSUE THREAD

**Issue by ilippert** [stefan-niedermann/nextcloud-deck#292]
**To Reproduce**
1. Go to a board
2. Click on the three points on the right (context menu)
3. See that the stack is called column

**Expected behavior**
The stack should be called stack.

**Comment by desperateCoder** [comment]
@juliushaertl what is it now? Didn't you mention you wanted to rename stacks to columns?

**Comment by ilippert** [comment]
it currently is column

it should be stack, to be consistent (and specific to the logic of the app's design, in my perception)

**Comment by putt1ck** [comment]
I thought it was planned to change it to list

**Comment by ilippert** [comment]
I would value 
a) consistency within the app (i.e. both times the same word)
b) consistency with the app on the server (there it is called stack)

**Comment by putt1ck** [comment]
Going to be "list" on web app: https://github.com/nextcloud/deck/issues/1088

**Comment by ilippert** [comment]
cheers

**Comment by stefan-niedermann** [comment]
@ilippert maybe you want to open a PR to adjust the `strings.xml`-file? (only the default file is required, all other files will be translated via transifex) 🙂

**Comment by stefan-niedermann** [comment]
I renamed "Stack" to "List" at all appearances (Of course it might take some time, until all languages are updated by Transifex).
