### ISSUE TITLE
Allow to move card to different deck

### ISSUE THREAD

**Issue by ilippert** [stefan-niedermann/nextcloud-deck#293]
I am frustrated when I want to move a card to a different stack. I cannot easily find a context menu or a drag and drop possibility to move something, e.g. from stack "todo" to stack "doing", in my case...

I propose a drag and drop possibility: when dragging a card above a different stack, that stack should (might) give some visual feedback (maybe with a _ _ _ underline of the stack's name?) that it is recognised as the selected stack onto which the deck would be dropped, if drag is released.

**Comment by desperateCoder** [comment]
Just tap a card and hold it for a second

**Comment by stefan-niedermann** [comment]
Please clarify the terminology:

Do you want to move card between two different stacks (aka columns aka list - yes we will unify this here)

**or** do you want to move card to a different board (aka deck) like the title of the issue says?

**Comment by ilippert** [comment]
hm, ok, then this might be a bug - when I tap and hold, a drag operations seems to begin, but I cannot drop it on the stack name.

**Comment by ilippert** [comment]
but, I just see: i can drag it onto the left/right of the screen - and then it gets moved into the neighboring stack. ok - that was not obvious to me.

**Comment by stefan-niedermann** [comment]
Aah, you habe to drag it to the right or left end, the active stack will switch then automatically.

**Comment by stefan-niedermann** [comment]
Yep, i will open a new issue for that, so newcomers won't to read this thread ;-)

**Comment by stefan-niedermann** [comment]
see https://github.com/stefan-niedermann/nextcloud-deck/issues/294
