### ISSUE TITLE
Right and left swiping is intolerant to tremulant swiping.

### ISSUE THREAD

**Issue by vadiof** [stefan-niedermann/nextcloud-deck#299]
I commented in #250 but didn't find the way to reanable that issue. Gif is also there
I faced this issue on 0.0.18 and it is still exist on 0.1.0 from F-droid. Looks like some input handler is absolutely intolerant to down swipe. I've uploaded video of this flaw.
Also I would suggest devs have a look how similar input situation is handled in SkyTube, for example. It is smooth and tolerant to little irregularities of swiping.

**Comment by desperateCoder** [comment]
see #295 
@vadiof you are not alone, i'll get @stefan-niedermann make this happen :wink:

**Comment by stefan-niedermann** [comment]
Possible solution: https://stackoverflow.com/a/29946734
