### ISSUE TITLE
Provide new DBStatus for unimportant changes

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#306]
When currently drag a card to the bottom all cards above it have the status `LOCAL_EDITED`.

While this is technically true, i don't want to display a sync icon to 20 cards only because one card has been moved.

A new `DBStatus`-entry could solve this issue, e.g. `DBStatus.LOCAL_EDITED_NOT_IMPORTANT_FOR_UI`. This status will be used if **only** the order has been changed (for now). Future fields might follow.

**Comment by desperateCoder** [comment]
new status: 
``` java
/**
* LOCAL_EDITED_SILENT means the same as LOCAL_EDITED, but doesn't need to be shown as changed in the UI
*/
LOCAL_EDITED_SILENT(5);
```

**Comment by stefan-niedermann** [comment]
Much better, nice idea!
