### ISSUE TITLE
🏷️ Manage tags per board

### ISSUE THREAD

**Issue by jakobroehrl** [stefan-niedermann/nextcloud-deck#309]
Is there a way to show/edit the board tags? 
Did not find them, thanks. 
PS: Great job so far... :)

**Comment by stefan-niedermann** [comment]
Not yet, thanks for the feedback!

**Comment by stefan-niedermann** [comment]
Will be released on version `1.1.0`.

![grafik](https://user-images.githubusercontent.com/4741199/80868043-43e1a380-8c98-11ea-8dc0-b96fb1b63ee5.png)
