### ISSUE TITLE
Encoding trouble with string results in bad string at Transifex

### ISSUE THREAD

**Issue by rakekniven** [stefan-niedermann/nextcloud-deck#31]
https://github.com/stefan-niedermann/nextcloud-deck/blob/c0be6d634dd4fa49ddc96230e43acd0ec240d491/app/src/main/res/values/strings.xml#L37

See https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/157711546?q=issue%3Aopen

Cannot add any image here, sorry.

**Comment by rakekniven** [comment]
Another one:

https://github.com/stefan-niedermann/nextcloud-deck/blob/c0be6d634dd4fa49ddc96230e43acd0ec240d491/app/src/main/res/values/strings.xml#L23

**Comment by rakekniven** [comment]
One more:
https://github.com/stefan-niedermann/nextcloud-deck/blob/c0be6d634dd4fa49ddc96230e43acd0ec240d491/app/src/main/res/values/strings.xml#L29

**Comment by rakekniven** [comment]
Next:

https://github.com/stefan-niedermann/nextcloud-deck/blob/c0be6d634dd4fa49ddc96230e43acd0ec240d491/app/src/main/res/values/strings.xml#L31

**Comment by stefan-niedermann** [comment]
Thank you for the hint, i will fix asap :)

**Comment by tobiasKaminsky** [comment]
@stefan-niedermann to have links correctly and clickable displayed, you can have a look how we do it in our "participate view":

https://github.com/nextcloud/android/blob/59cf6b9ba4965f38f2749f0624013daf0b83c946/src/main/java/com/owncloud/android/ui/activity/ParticipateActivity.java#L72-L77

This is "forum": 
![2019-01-04-131242](https://user-images.githubusercontent.com/5836855/50687650-720e8f00-1022-11e9-8cac-fe6f0be73f59.png)

**Comment by rakekniven** [comment]
Any update on here?

**Comment by stefan-niedermann** [comment]
@rakekniven yes, @tobiasKaminsky fixed today the bad translations on transifex (there have been some spaces where they shouldn't have been)

The encoding you mentioned in the first few posts ist fine, because it is HTML embedded in the XML - therefore the `<`-characters in the HTML-tags have to be encoded.

**Comment by rakekniven** [comment]
To be honest I am not satisfied with the answer.
The encoding looks bad at Transifex. See 
![2019-03-16_08h54_35](https://user-images.githubusercontent.com/2069590/54472471-308c2400-47c9-11e9-8887-8bf9160cdf68.png)

There should be another way to handle URLs. I cannot judge the comment by @tobiasKaminsky from technical side. Currently we only have such strange strings for this app at Transifex.

I am unable to open this issue again.

**Comment by stefan-niedermann** [comment]
Well that's the same way, we are handling for Nextcloud Notes (android) which works pretty good with transifx.

Pull Requests for changing this behavior are welcome :)

**Comment by tobiasKaminsky** [comment]
We could think about splitting this up:
text + &lt;href=" + url + ">Name + &lt;/a>

where
- text, name is in transifex
- url is in setup.xml (as an example) with translatable=false
- both &lt… are also with translatable=false and constants, e.g. link_start _link_end

This way no one could do any error again (like we saw on japanese)

**Comment by stefan-niedermann** [comment]
Okay, i agree.

**Comment by stefan-niedermann** [comment]
tracked in #68

**Comment by tobiasKaminsky** [comment]
Ha, I see now that this was my idea :rofl:

**Comment by stefan-niedermann** [comment]
i was just about to write exactly this :D

**Comment by rakekniven** [comment]
Nice catch. Happy to get this solved.
