### ISSUE TITLE
Move cards between stacks using the 'details' tab

### ISSUE THREAD

**Issue by kbeerepoot** [stefan-niedermann/nextcloud-deck#316]
**Is your feature request related to a problem? Please describe.**
Moving cards between stacks by dragging them to the right or left can be a bit confusing. It is easy to 'overshoot' the right stack, and lose the overview of wether you're in the right position to drop the card.

**Describe the solution you'd like**
When a card is tapped, the details tab will open and display the properties of the card. Right now the name of the stack that the card is in will not be shown there. It would be great if the name of the stack would be shown there, and if it would be possible to select that stack name en change it by choosing a different stack name from a drop-down list of all the stack names.

I would appreciate the above mentioned solution to be implemented because it makes for a 'less restless view for the eye', because I think **all** properties of the card should be **in view** when using the details tab, and because I think it should be possible to edit **all** properties of the card there ...

**Describe alternatives you've considered**
None

**Comment by stefan-niedermann** [comment]
cc @jancborchardt

I don't think this i a good idea.

First of all, we woulf have to display

- Account
- Board
- Stack

and so on, too.

We have very limited space on mobile phones and we plan to display the comments of  card below the details in the future. It will be very crouded. Dropdowns aren't a good idea neither, there could be many stacks, especially when we would introduce nested and depending dropdown menus (Accounts > Boards > Stacks).

What else could be more intuitive than dragging and dropping cards on a kanban-like board? Especially when https://github.com/stefan-niedermann/nextcloud-deck/issues/294 has been implemented.

Also, the Webapp does not display those details in a card.

The context of the edit mode is to actually *edit* the contents of a card, for actually *organizing* and *managing* a card, the column-view of the main activity is responsible.

**Comment by kbeerepoot** [comment]
> I don't think this i a good idea.
> First of all, we woulf have to display
> 
> * Account
> * Board
> * Stack
> 
> and so on, too.
> 
> We have very limited space on mobile phones and we plan to display the comments of card below the details in the future. It will be very crouded. Dropdowns aren't a good idea neither, there could be many stacks, especially when we would introduce nested and depending dropdown menus (Accounts > Boards > Stacks).
> 
> What else could be more intuitive than dragging and dropping cards on a kanban-like board? Especially when #294 has been implemented.
> 
> Also, the Webapp does not display those details in a card.
> 
> The context of the edit mode is to actually _edit_ the contents of a card, for actually _organizing_ and _managing_ a card, the column-view of the main activity is responsible.

OK, so all properties of a card is maybe overstating it, but I still think that at least just adding stack name would be very beneficial in easily managing a card. I assume there is not something as 'nested stacks' coming up ? And I am not actually asking for the 'Board' and 'Account' being visible on the Details tab (that would be overdoing it). 

Yes, dragging and dropping is intuitive on a kanban board, but that is mostly true on a desktop screen where you have plenty of overview. It is not as true on a small mobile screen, where you can not see the target stack beforehand, or the relative position of the target stack.

I have actually suggested this same solution in the Webapp repository, and the preliminary reaction there is positive ...

**Comment by stefan-niedermann** [comment]
Can you please link the issue you opened in the server repo here?

Adding the stack would only make sense if it is editable, otherwise it is a really useless information. Where would you place the stack dropdown?

**Comment by kbeerepoot** [comment]
> Can you please link the issue you opened in the server repo here?

https://github.com/nextcloud/deck/issues/1593

> Adding the stack would only make sense if it is editable, otherwise it is a really useless information. Where would you place the stack dropdown?

Well, yes, that's what I meant to express from the start. Sorry if I was not clear enough. I would place the stack dropdown at the top of the editable properties, because I assume this is actually the 
property that on average will be changed most frequently ...

**Comment by stefan-niedermann** [comment]
As i commented in the linked issue, we also have this way to move cards:

| Menu | Select |
| --- | --- |
| ![Screenshot_20200312-152857_Nextcloud_Deck](https://user-images.githubusercontent.com/4741199/76532028-57317900-6476-11ea-8552-bab7534f4f41.png) | ![Screenshot_20200312-152904_Nextcloud_Deck](https://user-images.githubusercontent.com/4741199/76532052-5e588700-6476-11ea-8bb0-440ebff6762f.png) |
 
Because it still belongs to *organize* cards and the edit view is to *edit* card contents. In which case isn't this sufficient?

**Comment by kbeerepoot** [comment]
I can seem to find that functionality in Deck on my Moto G6 Android phone. How do I get there ?

![Screenshot_20200312-155416](https://user-images.githubusercontent.com/28199141/76534738-2fdcab00-647a-11ea-8d8e-b40c4aea30b8.png)

**Comment by stefan-niedermann** [comment]
Which version of the android app do you have installed? This looks outdated (you can find the version information in the Sidebar -> About).

Actually it is already there, it's just a bug in this version. At the top right of each card is a three dot-menu (it is cut in half here). Just tap in thr top right corner, a little left of the cutted dots and the menu will appear - or update your version 😉

**Comment by kbeerepoot** [comment]
Version : v0.1.0

Server app version : v0.8.0

**Comment by stefan-niedermann** [comment]
yep. Please update :)

**Comment by kbeerepoot** [comment]
> yep. Please update :)

Found it. And it works now. Mea culpa, mea culpa, mea maxima culpa. I don understand how I could have overlooked this update.

Thanks for the help.

**Comment by stefan-niedermann** [comment]
Absolutely no problem :) we are happy about every feedback!
