### ISSUE TITLE
Hinzufügen von Anhängen bei neuen Karten schlägt fehl

### ISSUE THREAD

**Issue by weinic** [stefan-niedermann/nextcloud-deck#318]
Fehler beim hochladen von Anhängen.

Wenn ich eine neue Aufgabe erstelle (klick auf das plus Symbol) und dann zu den Anhängen gehe und dort etwas hochladen möchte, stürzt die APP ab.

```
App Version: 0.1.4
App Version Code: 25
Files App Version Code: 30110052

---

OS Version: 3.4.113-lineageos-g1bb760f(a9639c51c9)
OS API Level: 25
Device: hlte
Model (and Product): SM-N9005 (lineage_hlte)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'it.niedermann.nextcloud.deck.model.Card it.niedermann.nextcloud.deck.model.full.FullCard.getCard()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$addAttachmentToCard$31$SyncManager(SyncManager.java:973)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$-OqrzyG9052g6tBzto6Ud0qYSVc.run(lambda)
	at java.lang.Thread.run(Thread.java:761)

```

**Comment by stefan-niedermann** [comment]
Ich nehme an, wenn die Karte einmal gespeichert wurde klappt der upload?

**Comment by weinic** [comment]
Wow sehr schnelle Antwort,

Ja das ist richtig, erst nachdem die Karte gespeichert wurde, lässt sich
auch ein Anhang hinzufügen.

Mfg Christoph

Niedermann IT-Dienstleistungen <notifications@github.com> schrieb am Sa.,
14. März 2020, 08:21:

**Comment by stefan-niedermann** [comment]
Danke für die Info. Wir werden als Quickfix den Upload-Button bei der Neuanlage verbergen, sodass die App nicht mehr abstürzen kann und uns dann mittelfristig um ein besseres Verhalten kümmern.

Danke für das Feedback!

**Comment by desperateCoder** [comment]
Tatsache, hab ich null bedacht. Wird erledigt!

**Comment by desperateCoder** [comment]
Hab gerade Mal nachgesehen, der sync-manager tut das sogar schon. @stefan-niedermann du weißt, was zu tun ist, ich zieh mich wieder raus.

**Comment by stefan-niedermann** [comment]
Der Crash wurde inzwischen am `master`-Branch behoben und sollte nicht mehr auftreten.

Tatsächlich Anhänge bei der Neuerstellung einer Karte hinzuzufügen, erfordert allerdings noch ein wenig Arbeit. Wird demnächst angegangen.

**Comment by stefan-niedermann** [comment]
Follow-Up: #320
