### ISSUE TITLE
Donation broken?

### ISSUE THREAD

**Issue by maxammann** [stefan-niedermann/nextcloud-deck#33]
Hey Stefan,
just wanted to buy you a few beers or coffe :)
But I got this message on Liberapay: Your donation to stefan-niedermann cannot be processed right now because the account of the beneficiary isn't ready to receive money.

**Comment by stefan-niedermann** [comment]
uh? i will have a look :D thanks :)

**Comment by maxammann** [comment]
Any issues I can work on right now? Seems like you are currently working on editing.

Do you already have plans for the offline functionality?

**Comment by stefan-niedermann** [comment]
Yes. we are working on a branch to use `Room` instead of `GreenDAO` - any help is highly appreciated :)

**Comment by stefan-niedermann** [comment]
@maxammann could you please test this link? https://liberapay.com/stefan-niedermann/donate
I'm pretty sure it should work, since i receive other donations, too.

**Comment by svbergerem** [comment]
![no payment method](https://user-images.githubusercontent.com/3798614/54432626-03d4ff80-472a-11e9-90d8-16ca38b993d5.png)

**Comment by stefan-niedermann** [comment]
I just readded a payment method (it seems like it got lost when Liberapay had issues with Mangopay) - Can you please retest @svbergerem or @maxammann ? :)

**Comment by svbergerem** [comment]
It works. :+1:

**Comment by stefan-niedermann** [comment]
I have received it already :heart:  Thank you @svbergerem - the money will be spend for the current Nextcloud hackweek in Stuttgart for @desperateCoder and myself :rocket: :rocket: :rocket:

The support is very appreciated :+1: :smiley:

**Comment by desperateCoder** [comment]
@svbergerem Wow, that was quite unexpected...  :smiley:  Thank you very much! :heart:  We absolutely appreciate that, we will do our best to fulfill your donation! :rocket:
