### ISSUE TITLE
Wrong version

### ISSUE THREAD

**Issue by CarFla** [stefan-niedermann/nextcloud-deck#336]
**Describe the bug**
When start Deck on android and connect to nextcloud There is an indication for upgrade Deck. After that connect to firefox to link of nextcloud istance

**To Reproduce**
1. Donwload from Fdroid Nextcloud for deck ver. 0.4.0
2. Open Deck
3. Choose account of nextcloud existent

**Expected behavior**
I have Deck on android ver. 0.4.0, but try also with 0.3.0, Nextcloud app android ver. 3.10.1, nextcloud server ver 18.1, deck app server 0.8.0

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - Android-Version:  8

**Comment by stefan-niedermann** [comment]
Dear @CarFla,

thank you for reporting this bug.

Can you please provide a test account for your instance and send the credentials to info@niedermann.it so we can reproduce it?

Thank you in advance

**Comment by CarFla** [comment]
Hi @stefan-niedermann 
I create new user, but before to send you I test it and... all ok.
After that I retry with my user and no error.

I dont know why before creation of new user it indicates wrong version.

BUT, with new user i can view and modify board, with my user no. 

I think that the problem is the user in my nextcloud server.

thank you for your help and sorry for the inconvenience.

**Comment by stefan-niedermann** [comment]
Absolutely no problem 🙂 I am glad to hear that you eventually got the app working.

So, how exactly can we help you at this point? What do you need and where exactly are problems left which we can solve?

**Comment by stefan-niedermann** [comment]
*bump* :)

**Comment by stefan-niedermann** [comment]
Please feel free to open a new issue if you still have troubles adding an account.
