### ISSUE TITLE
Remove unwanted string from translation at Transifex

### ISSUE THREAD

**Issue by rakekniven** [stefan-niedermann/nextcloud-deck#34]
Please remove the following string. No need to translate.

https://github.com/stefan-niedermann/nextcloud-deck/blob/35a23d203efc05c978441e9c322033707c273381/app/src/main/res/values-b%2Ben%2B001/strings.xml#L12

shared_preference_last_sync

**Comment by tobiasKaminsky** [comment]
I would put such strings in setup.xml insead of strings, so that Transifex will never try to translate it.

**Comment by AndyScherzinger** [comment]
other than that they should have a `translatable="false"` too :)
