### ISSUE TITLE
Release availability and/or f-droid release

### ISSUE THREAD

**Issue by Aquariu** [stefan-niedermann/nextcloud-deck#35]
Dear developpers,
Thanks for this project, it would bring some real improvement in my Nextcloud use.

Unless I'm too lazy/blind/unaware, I can't find any released apk for this app. Search on f-droid returns nothing, neither does a Play Store search. Please tell me where I can find a release package (and close this issue as it's not a bug report).

Kind regards,
Olivier

**Comment by violoncelloCH** [comment]
see #4

**Comment by desperateCoder** [comment]
Hi Oliver, 

thank you for your interest in our work!

We are currently working on it, the current status of this project is still not really usable and unstable. As soon as we have something reliable, we will release it on both platforms. 

Please be patient, since we are doing it in our spare time.

Best regards
Artur

**Comment by Aquariu** [comment]
Sure thing, thanks for the feedback.
I just stumbled upon it so no hurry on my part. 

It seems like an interresting addition to Nextcloud Deck as it would allow less browser-loving people to use the capabilities of Deck without leaving their beloved smartphone.

**Comment by desperateCoder** [comment]
That's not even all! We plan to include offline support and maybe more! But first things first :)

> EDIT: Do you think it's a good idea to add a phrase in README.md to warn/explain that there is no release yet ?

Now that is a great idea! We absolutely should! @stefan-niedermann go for it!

**Comment by stefan-niedermann** [comment]
jup, good idea. i will add it to the `README.md` :)
