### ISSUE TITLE
Can't "Save" changes to card

### ISSUE THREAD

**Issue by dan0xii** [stefan-niedermann/nextcloud-deck#351]
**Describe the bug**
Specifically, I can't save changes and close the card.

**To Reproduce**
1. Open an existing card
2. Edit the description
_or_ add a tag
3. Tap the "tick" to save and close
4. Nothing happens. Tap "X" to close and you are warned that you have unsaved changes. If you select "Discard" the card will close and when you re-open it you will see that the changes were actually saved.
Note, selecting "Save" in the "Do you want to save your changes?" dialog appears to work and drops you back at the card view.

**Expected behavior**
You select the "tick" icon to save-and-close the card.

**Screenshots**
Will get some if it would help. Let me know.

**Smartphone (please complete the following information):**
 - Device: OP6
 - Android-Version: 9.0 / Lineage 16.0
- Server app version is 0.8.0

- App version is v0.4.0. I recently updated the app and it appeared that you'd fixed the bug but after a while it has come back.

**Stacktrace**
None but point me to the relevant calls or classes and I'll see if I can debug.

**Comment by desperateCoder** [comment]
Hi @dan0xii, thanks for your report!
Well, that's a quite weird behavior, I can't really reproduce it. But to be fair: I got the latest 0.5.2 version of the Android app from play store. 
Is your build from f-droid? 

Can you persistently reproduce this behavior on any card on any board and any stack?

**Comment by dan0xii** [comment]
Yes, it's happening on cards in all three of the boards I've got setup. I can add a card fine but the problem occurs when i go back to edit.

I've just created a new board, new stack and new card fine. I go back to change the new card and I get the issue described.

-------- Original Message --------

**Comment by stefan-niedermann** [comment]
I did quiet a lot of refactoring in the `EditActivity` since this issue was reported. Can you reproduce it still with the latest master?

**Comment by stefan-niedermann** [comment]
This should be foxed in the meantime at the latest `master`. Reopen if you are still experiencing the issue. Thank you :)

**Comment by dan0xii** [comment]
Yep, looks like it's fixed now.

**Comment by stefan-niedermann** [comment]
Thanks for the feedback 🙂
