### ISSUE TITLE
Create new Card: DueDate not saved

### ISSUE THREAD

**Issue by nidomiro** [stefan-niedermann/nextcloud-deck#354]
**Describe the bug**
When I'm creating a new card and select a DueDate it will not be saved.
Editing the card and setting the date again works as expected.

**To Reproduce**
1. Create a new card with DueDate (Date and Time)
2. Save the card
3. You can see the DueDate
4. Sync will automatically happen
5. DueDate is gone

**Expected behavior**
DueDate is still there, as configured.

**Smartphone (please complete the following information):**
```
App Version: 0.5.2
App Version Code: 5002
App ID: it.niedermann.nextcloud.deck.play
Files App Version Code: 30100190

---

OS Version: 3.4.113-lineageos-g9fc6b38(486b2fc241)
OS API Level: 28
Device: klte
Model (and Product): SM-G900F (lineage_klte)
```

**Comment by stefan-niedermann** [comment]
Thank you, this is a known issue of the server and cannot be fixed on our side.

Please see and upvote here: https://github.com/nextcloud/deck/issues/1430

**Comment by nidomiro** [comment]
Thanks for your quick reply.
I left a :+1:  on the ticket you mentioned :)

**Comment by stefan-niedermann** [comment]
Thanks for the report :) Have fun with the app and let us know if you encounter any further issues, so we can fix them :wink:
