### ISSUE TITLE
Upgrade icon

### ISSUE THREAD

**Issue by PanderMusubi** [stefan-niedermann/nextcloud-deck#355]
**Describe the bug**
Upgrade icon to use latest style artwork

The [current icon](https://f-droid.org/en/packages/it.niedermann.nextcloud.deck/) is using an old style.

**Expected behavior**
Use latest style Nextcloud in artwork

**Screenshots**
Please upgrade icon to use the latest Nextcloud style as seen in

![](https://f-droid.org/repo/it.niedermann.owncloud.notes/en-US/icon_sOQTkc5JR-7Dt0WXW7WjbRHJGMYqqVVBTfhCJ9fjQhA=.png)

![](https://f-droid.org/repo/net.eneiluj.nextcloud.phonetrack/en-US/icon_2Y3hr_vJTBENNf8nIzwDWW8obMWeYKCMKnulOpWeYkg=.png)

![](https://f-droid.org/repo/icons-640/org.schabi.nxbookmarks.6.png)

![](https://f-droid.org/repo/icons-640/fr.unix_experience.owncloud_sms.69.png)

**Comment by stefan-niedermann** [comment]
Nope, the Nextcliud guys decided that the apps will no use this background.

The evolution is like:

1. plain lightblue background
2. dotted background
3. linear gradient with blue colors background

Further information see here: https://github.com/nextcloud/talk-android/pull/695

PS.: You should update your apps, they are outdated. I know that each of the shown app has at least merged the new icons to their master and at least Notes has already been released with the new icon.
