### ISSUE TITLE
Caches for color calculations?

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#381]
Some of the `ColorUtil`-methods will be called pretty often because of the branding. While the operations are pretty small (some multiplications and divisions), i though we should maybe add a in-memory cache mechanism. The question is whether or not the access to the hashmap is cheaper than the calculation :thinking: 

I did some statistics:

```
Launching the app

getForegroundColorForBackgroundColor            0
isColorDark                                     5
getBrightness                                   5
contrastRatioIsSufficient                       3
getContrastRatio                                3
getLuminance                                    6
getSubcolorLuminance                            12


Open single card

getForegroundColorForBackgroundColor            0
isColorDark                                     2
getBrightness                                   2
contrastRatioIsSufficient                       8
getContrastRatio                                8
getLuminance                                    16
getSubcolorLuminance                            32

```

Side notes:

Given
- the brand color does not change (very likely)
- the user does not change the preferences (likely)
- the user does not change the account

the arguments to the functions as well as the return values are exactly the same.

Using a map we could solve a lot of unnecessary calculations.

CC: @desperateCoder

**Comment by desperateCoder** [comment]
Regarding to the number of calls, I guess I'll handle this. We are talking about storing 7 colors in memory, peanuts. But it won't be a map, I'll see what fits best
