### ISSUE TITLE
SyncManager and "childs" must not know Activity class

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#383]
The synchronization mechanism must not use any view related stuff. It currently needs an `Activity` as an argument only for one reason: The `callOnUiThread`-method, which executes the `onError`-block on the UI-thread.

The callers are responsible them self in the future to run the `onError`-callbacks on the UI-thread if it really needs to happen on the UI-thread.

**Comment by desperateCoder** [comment]
Assign me, as soon as the UI covers all `onError()`s. If you want, we can talk about adding the `Activity` into the callback and let the default implementation handle the most of this stuff.
