### ISSUE TITLE
Dark mode following system default

### ISSUE THREAD

**Issue by SpaceCafe** [stefan-niedermann/nextcloud-deck#392]
**Is your feature request related to a problem? Please describe.**
I occasionally switch between normal and darkmode on my android 10 phone.

**Describe the solution you'd like**
An automatic change would be nice.

**Additional context**
I assume that the following API is helpful: [Dark theme – Changing themes in-app](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#changing_themes_in-app)

**Comment by stefan-niedermann** [comment]
Jup, do you want to create a Pull Request @SpaceCafe ? 🙂🚀

**Comment by fm-sys** [comment]
I would like to work on it...

**Comment by desperateCoder** [comment]
@fm-sys great! Just create a draft pull request and you are ready to go! If there is anything we can do for you just tell us!

**Comment by stefan-niedermann** [comment]
Great, it should look like the corresponding setting in the [Notes app](https://github.com/stefan-niedermann/nextcloud-notes/issues).

Just fork the repository and start a PR where we can work together and review the progress 🙂 

Some notes:
- Following system default should be the default setting
- When migrating an user who never changed the setting, use the new default
- When migrating an user who changed the setting explicitely, keep this

Looking forward to your contribution!

**Comment by fm-sys** [comment]
Thanks for pointing to the Notes app. I think I can use some code parts from over there...

**Comment by stefan-niedermann** [comment]
Thank you @fm-sys for solving this - The change will be released in `1.13.2`.

**Comment by desperateCoder** [comment]
@fm-sys thank you! ❤️
