### ISSUE TITLE
Prebuilt version to test?

### ISSUE THREAD

**Issue by violoncelloch** [stefan-niedermann/nextcloud-deck#4]
Do there exist any prebuilt version of the app to test it?

**Comment by stefan-niedermann** [comment]
You can get it from F-Droid :)

**Comment by violoncelloch** [comment]
So you will publish it on F-Droid if there is a first usable version?

**Comment by stefan-niedermann** [comment]
It will definitely be published at f-droid, yes.

**Comment by IzzySoft** [comment]
Stefan, if you want to have a "pre-run" via [my F-Droid repo](https://apt.izzysoft.de/fdroid), just ping me. It already served many apps as "stepping stone" in the past. And would make it easier for your testers if they can have "auto updates" :wink:

And if you know someone who could lend a hand to another Android-Nextcloud app: the dev of Nextcloud Bookmarks is "Land unter" and looking for someone to take over …

**Comment by stefan-niedermann** [comment]
Great to hear, thank you :) I think we can soon go public at the official F-Droid repository.

Current state: View boards, stacks and cards.
Limitations: No edit, no creation, no offline capabilities.

As soon as the app works offline, we will publish it on F-Droid as a viewer app and extend it step by step.

> And if you know someone who could lend a hand to another Android-Nextcloud app: the dev of Nextcloud Bookmarks is "Land unter" and looking for someone to take over …

Are you talking about this https://play.google.com/store/apps/details?id=org.schabi.nxbookmarks / https://gitlab.com/derSchabi/OCBookmarks ? Please contact me directly via e-mail about this topic. And thank you for the offer :)

**Comment by IzzySoft** [comment]
OK, great – then we'll meet over there (disclosure: I'm one of the F-Droid maintainers). My offer still stands, eg when you need a beta channel (with a different package name).

And yes, I've meant Schabi's. Email coming soon :wink:

**Comment by IzzySoft** [comment]
No offense taken! If you two decided, please let derSchabi know. I'm not involved directly, I'm just a user of his app. I've sent all details to Stefan by mail.

Thanks for helping out!
