### ISSUE TITLE
Pass `Account` instance down to `EditActivity` instead of just `accountId`

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#403]
`Account` already implements `Serializable`, should be no issue. This will save us a few database queries.

**Comment by desperateCoder** [comment]
What about a more central solution? Singleton? If I have to rewrite sync and SyncManager anyways, we can also do this. I guess this is going to be a huge PR, but idk, feelin' cute and sh*t

**Comment by stefan-niedermann** [comment]
No, it has to be provided this way and not fetched from a singleton because of, you know, android stuff. One needs to provide everything an activity needs via a bundle to ensure, that it can get recovered correctly when stopped in the lifecycle, on orientation changes and so on...

This is a pure UI stuff-thingy, but thank you :)

**Comment by desperateCoder** [comment]
We hate Android. Life would be so much easier in vanilla java. /Useless complaints
