### ISSUE TITLE
Enable branding by default

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#408]
Branding works good, we should enable it by default when upgrading to `0.7.0`.

- [x] `SyncManager#synchronizeEverything` has to call `SyncManager#refreshCapabilities` for each account

**Comment by desperateCoder** [comment]
done. fyi: I implemented it as the first step of a sync, not only for `syncEverything()`. This way, if the server is in maintenance mode, the sync is not triggered, since it wouldn't work anyway.

If you are ok with this behaviour, you can close this issue.

**Comment by stefan-niedermann** [comment]
Works like a charm. thanks :)
