### ISSUE TITLE
Create cards

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#41]

**Comment by desperateCoder** [comment]
*bump* @stefan-niedermann 

next to dev pls

**Comment by CaptInsano** [comment]
Looking forward to this.

I need a kanban solution with a decent andoid app!

**Comment by desperateCoder** [comment]
C'mon @stefan-niedermann 😝

**Comment by stefan-niedermann** [comment]
@desperateCoder please have a look at `create-cards`-branch. Basically i think it might work this way, but there are two problems left:

1. When i type in a title and press back, i can see the created card for a second in the list, but then it gets deleted (maybe some problem with the sync mechansim?) -> Can you check this pls?
2. There might be a timing problem: The user-object (which is needed to create a card) is loaded asynchronous and might not be available at the time when the human user presses the back button. Unfortunately LiveData is lifecycle-aware and we can not observe the user-object in the `onStop()`-callback - observers will not get notified in lifecycle-callbacks *sigh*. Since there are no network operations on getting the user-object, i think it should be there in every case, but we have to make sure to handle the other case gracefully.

**Comment by desperateCoder** [comment]
Yep, I'll have a look at this asap. Thanks for the UI base!
