### ISSUE TITLE
Typo duedate

### ISSUE THREAD

**Issue by q-wertz** [stefan-niedermann/nextcloud-deck#412]
**Describe the bug**
When translating in transifex I saw that you use the word "duedate". As far as I know the correct spelling would be "due date"

**Comment by desperateCoder** [comment]
@q-wertz thanks for the report, we'll fix that! And big thanks for contributing the translation for our app! ❤️

**Comment by q-wertz** [comment]
Thanks you for providing this app :)

**Comment by desperateCoder** [comment]
Well, @Valdnet didn't loose any time. See: https://github.com/stefan-niedermann/nextcloud-deck/pull/413

Thanks to both of you!
