### ISSUE TITLE
Create new Access for user

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#415]
User A: Create a new board and go to access control list. Add user b.

This is what one can see now in the web interface: 

![grafik](https://user-images.githubusercontent.com/4741199/80279566-d31e1280-86fe-11ea-9034-66244dc0aac5.png)

We can also see this in the DOM of the web interface:

![grafik](https://user-images.githubusercontent.com/4741199/80279579-f2b53b00-86fe-11ea-8edb-1bd958e82531.png)

Probably we are messing around some IDs and probably we have also found a bug in the server API implementation. This should not be possible.

**Comment by desperateCoder** [comment]
I guess this is a follow-up to a server-side bug. I already told @juliushaertl, the participant of a ACL entity isn't a user anymore, but a string like "0:stefan". If I'm wrong, i'll fix that after i have updated to the next beta of the server. Blocked for now.

**Comment by stefan-niedermann** [comment]
Is this fixed in server version `1.0.0`?

**Comment by juliushaertl** [comment]
Should (tm) be fixed, yes as the primary key does no longer return the concatinated `0:uid` value. However there is a different issue with the sharing in the mobile app that it is only using known users for sharing boards.

For searching existing users the sharee api from the server https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-sharee-api.html should be used.

See https://github.com/nextcloud/deck/blob/611f9ff6a572d406e1a163f7c623c1e84451b87a/src/store/main.js#L336-L345 for the server implementation of fetching possible sharing options

The item types are defined here https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/lib/public/Share/IShare.php#L49 where currently for deck only 0 (user), 1 (group) and 7 (circle) are supported.

**Comment by stefan-niedermann** [comment]
@desperateCoder has this been fixed in the meantime? \*confused\* :confused:

**Comment by desperateCoder** [comment]
I didn't see this error after the beta, so I guess yes.
