### ISSUE TITLE
Deck as a "share to" location -> create new card

### ISSUE THREAD

**Issue by proserver1** [stefan-niedermann/nextcloud-deck#424]
**Is your feature request related to a problem? Please describe.**
no problem

**Describe the solution you'd like**
"send to" "new card" as an additional option to "send to"  "add to card"

**Comment by stefan-niedermann** [comment]
Will be in version `0.7.0` (not yet released). Thank you for the proposal and a special thanks for your donations :slightly_smiling_face: :heart:
