### ISSUE TITLE
ColorChooser occurs multiple times when editing board

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#431]
Not 100% reproducible, but i guess that the `initCustomColorChooser()`-method is called from `selectColor()` each time the LiveData in `EditBoardDialogFragment` fires.

One solution would be to change the observation to a `observeOnce`, but we should better analyse why the LiveData fires multiple time even when the Board itself does not change (maybe it fires because cards are getting updated?) and fix the `CustomColorChooser` to be able to manage multiple `selectColor`-calls.

**Comment by stefan-niedermann** [comment]
Basically the issue is solved, the `ColorChooser` can now handle many calls on `selectColor`.

Though i would like @desperateCoder to have a look at `SyncManager#getFullBoardById` and why it fires so often when synchronizing (Just post a log entry in `EditBoardDialogFragment` line `63`, you will notice it fires pretty often even nothing of the board actually changes). Can you see what i am missing here?

**Comment by desperateCoder** [comment]
This is because you have `FullBoard`s. So all the relations are tracked as well and will cause the `LiveData` to fire for any `Label`, `User,` `AccessControl` and `Stack`. You could observe the stack only, or maybe `onlyIfChanged()` might help. But at the end of the day this works as designed by Room.

**Comment by stefan-niedermann** [comment]
Ah, `onlyIfChanged` wasn't used in the `Adapter`. I added it, and **now** it works like expected :smile: 

I understand the concept of all relations firing new LiveData, but i assumed that `onlyIfChanged` was already present (which wasn't the case).
