### ISSUE TITLE
Implement ETags for Capabilities endpoint

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#435]
Depends on https://github.com/nextcloud/server/issues/20693 (issue) and https://github.com/nextcloud/server/pull/20722 (pull request).

The `capabilities` endpoint will support `ETags` in the future.

To simulate this behavior, one can change in `core/Controller/OCSController.php` the end of the `getCapabilities()`-function from

```php
return new DataResponse($result);
```
to

```php
$response = new DataResponse($result);
$response->setETag(md5(json_encode($result)));
return $response;
```

Description of how it works can be found here: https://github.com/nextcloud/server/issues/20693#issuecomment-621112646

This issue is completely independent of https://github.com/stefan-niedermann/nextcloud-deck/issues/359 and affects **only** the `capabilities` endpoint.

**Comment by desperateCoder** [comment]
uhm... i think i'm done here...

**Comment by stefan-niedermann** [comment]
I know, we are waiting for https://github.com/nextcloud/Android-SingleSignOn/pull/204 to be merged and released and then need to merge https://github.com/stefan-niedermann/nextcloud-deck/pull/490 ...
