### ISSUE TITLE
➕ Clone boards with existing stacks and labels

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#455]
- [x] Implement `SyncManager#cloneBoard` @desperateCoder 
- [x] Implement new menu item in `DrawerMenuUtil`
  - [x] Step 1: Do not display any dialog but directly use the following parameters:
    - Use `%1$s (Copy)` as new board title
    - origin board color as the target board color
    - origin accountId as the target accountId
  - [x] Step 2: Reuse `EditBoardDialog` to allow user change title and color before actual clone
  - [ ] Step 3: Allow user to select a target account *(Optional)*

Side note: It is possible that in the future we will have a flag `cloneCards: boolean`, but this out of scope for this issue and requires https://github.com/nextcloud/deck/issues/1832 to be resolved first because especially the handling of assignees is completely unclear (depending on existence and permissions of the assignees).

**Comment by desperateCoder** [comment]
SyncManager knows what to do now, but couldn't test it yet (no UI). If this fails, tell me!

**Comment by stefan-niedermann** [comment]
Just out of curiosity: why no `WrappedLivedata`? How can i catch errors?

**Comment by desperateCoder** [comment]
I don't make any errors. Thats why. Just kidding, the method signature said simply `LiveData`, I changed that.

**Comment by stefan-niedermann** [comment]
Will be shipped in `1.8.0`.
