### ISSUE TITLE
About credentials exposes markup (strong tag)

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#460]
> My language is English Canada (also English us) and here is what it looks like:

![grafik](https://user-images.githubusercontent.com/4741199/81299260-3ea89e00-9076-11ea-9a5c-f4a8a6486e45.png)

**Comment by desperateCoder** [comment]
Holy cow! Wtf is this about?! Did I screw up parsing? Or is this a display-only issue?

**Comment by stefan-niedermann** [comment]
It's a display-only issue, don't worry.

**Comment by stefan-niedermann** [comment]
Jup. Translations are outdated:

![grafik](https://user-images.githubusercontent.com/4741199/81302619-e3c57580-907a-11ea-86db-fe25132cd1a4.png)

We removed all the HTML stuff so the translations are easier, but it seems like some languages haven't been updated since then.

Affected are at least language codes `b+en+001`m `ko` and `nb-rNO` (i looked for `href` and `strong` in the translated files)

@rakekniven would you mind?

**Comment by rakekniven** [comment]
Fixed in en_GB, ko and nb-NO

**Comment by rakekniven** [comment]
Did not find other occurences

**Comment by stefan-niedermann** [comment]
Great, thank you! :)

**Comment by stefan-niedermann** [comment]
Let us know if you need some beer or so @rakekniven ! At some point in the future there *will* be a Nextcloud hackweek or conference again for sure. Would be great if we could thank you for all the transifex-stuff personal :)
