### ISSUE TITLE
How to delete labels

### ISSUE THREAD

**Issue by niccokunzmann** [stefan-niedermann/nextcloud-deck#463]
I wonder if it is possible. How can I delete Labels with this app? I would expect this in the settings.

**Comment by desperateCoder** [comment]
Since the latest version you can open the sidebar on the left, then select the three-dot menu or the desired board, then select "manage labels". Does that work for you?

**Comment by niccokunzmann** [comment]
I have version 1.0.1, latest from f-droid.

**Comment by stefan-niedermann** [comment]
Version `1.1.0` is already tagged and will be shipped by F-Droid within the next few days. Managing labels will be possible with this version, just a little patience :slightly_smiling_face:
