### ISSUE TITLE
Android NC Deck App - only ontime replication?

### ISSUE THREAD

**Issue by fds2610** [stefan-niedermann/nextcloud-deck#467]
**Describe the bug**
configuring an account results in initial downloading all deck-cards and their details quite well. unfortunately after this initial download no changes on either side are being replicated to and from the phone.

**To Reproduce**
change a deck-card
start replication
nothing changes.

**Expected behavior**
changes should be replicated to either side (app and Server)

**Smartphone (please complete the following information):**
- Device: Huawei P10 Model: VTR-L29
- Android-Version: 9
- App-Store:
  - [X] Google Play Store
  - [ ] F-Droid

**Stacktrace**
none. where ?

**Comment by stefan-niedermann** [comment]
Try to pull to refresh (swipe from top to bottom and release your finger then).
It should start to synchronize (Circle should start spinning). Does any snackbar at the bottom appear which has a "more" action on the right side?
Should look something like this:

![grafik](https://user-images.githubusercontent.com/4741199/81378676-f9cd4780-9107-11ea-8182-6b3173e80ac9.png)

If yes: Press it and post the error message which will appear.

**Comment by fds2610** [comment]
Hi Stefan,
unfortunately i do not get a "more..." displayed as the sync wheel spins forever...

**Comment by stefan-niedermann** [comment]
How many boards / lists / cards do you have and how fast is your internet connection? Is it possible that the sync simply takes up some time?

**Comment by fds2610** [comment]
hmmm... it's 4 boards with 12 cards in total - and I waited for days before i opened the bug, here.

**Comment by stefan-niedermann** [comment]
Which server version are you using exactly please? And which version of the android app?

**Comment by fds2610** [comment]
NC server: 18.0.3
NC deck: 0.8.2
app: 1.0.2

**Comment by stefan-niedermann** [comment]
Can you update the server to `1.0.0` (it has been released as a stable version a few days ago) - just we can ensure that no old version causes this.

It certainly sounds like an issue with your internet. Have you maybe enabled the "Sync only on Wifi" option?

If not: Can you provide us a test account so we can try to reproduce the issue? (Just send the credentials to info@niedermann.it)

**Comment by fds2610** [comment]
after updating to 1.0.0 it works (at least once, now).
Yes, WLAN sync only is turned on, though I AM in wlan connection and i established the initial setup with the same conditions. I will continue to monitor this topic... thank you for your patience !

**Comment by stefan-niedermann** [comment]
Absolutely no problem :slightly_smiling_face:  That's why we are here. Just let us know if you have any further problem.
