### ISSUE TITLE
Cant create new tags

### ISSUE THREAD

**Issue by deljones** [stefan-niedermann/nextcloud-deck#470]
**Not Able to create new tags**

**To Reproduce**
1. Create a board
2. Create a list and a card in the list
3. Double click the card. Info opens up on the right
4. Go to tags. Type in the new tag name. Nothing happens

**Expected behavior**

**Smartphone **
In the Andoid version of Deck YOU CAN create new tags which do appear on the desktop version. You just can't do it the other way.

**Comment by stefan-niedermann** [comment]
So you only have an issue with the web version? In this case open the issue please in this repository: https://github.com/nextcloud/deck/issues/new?template=Bug_report.md

**Comment by stefan-niedermann** [comment]
Closing because of https://github.com/nextcloud/deck/issues/1830
