### ISSUE TITLE
📦 Archived board is shown list of boards

### ISSUE THREAD

**Issue by cappuMUC** [stefan-niedermann/nextcloud-deck#471]
**Describe the bug**
I have an archived project in my  project list which is hidden in Nextcloud's web UI . In the Deck app it is presented as a normal, unarchived project.

**To Reproduce**
1. Archive a new or existing board in the web UI
2. Open Deck app on Android device

**Expected behavior**
The archived board is hidden or at least marked as archived in the list of boards.

**Smartphone (please complete the following information):**
- Device: Google Pixel 3a
- Android-Version: 10
- App-Store:
  - [ ] Google Play Store
  - [x] F-Droid

**Comment by stefan-niedermann** [comment]
@desperateCoder i think at least the following queries should hide `archived` cards:

- `getBoards`
- `getFullBoards` (Currently unused, but for consistency)
- `getBoardsWithEditPermission`

Alternatively we can add an additional argument `boolean withoutArchived` or so, but i don't see any reasons to do this effort for now.

Please add a line of Javadoc to those methods which says, that the methods will *not* return `archived` boards.

**Comment by desperateCoder** [comment]
done. no flag, since there is currently no need.

**Comment by stefan-niedermann** [comment]
Works, will be shipped with `1.3.0`.

I will open further issues for a good integration of archived boards in the future, but hiding archived boards in the first step seems to be a good quick fix to avoid confusion.
