### ISSUE TITLE
Don't preselect title when edit card

### ISSUE THREAD

**Issue by simonspa** [stefan-niedermann/nextcloud-deck#473]
When opening a card, currently the title is preselected for editing. For me, this immediately opens the keyboard which covers up half of the card.

I think it would be more fluid if the title is not selected - at least I only rarely find myself editing it anyway. This way, the whole card would be visible immediately.

![Screenshot_20200508-211537](https://user-images.githubusercontent.com/1677436/81440928-21a4c580-9171-11ea-97f3-e0c583d677b2.png)

**Comment by desperateCoder** [comment]
Do you mean in edit mode or in general? I pretty much agree with you, but in create mode, I'd like to keep this behavior.

**Comment by stefan-niedermann** [comment]
This should already be the case

- Create new card: Open keyboard and focus title
- Edit existing card: Keep keyboard closed and do not focus anything

Just tested it and works on my device. @desperateCoder can you confirm this?

Which version of the app exactly are you using @simonspa (see "About" in sidebar)

**Comment by simonspa** [comment]
@desperateCoder I agree with you, when creating a new card this of course makes sense.

@stefan-niedermann I'm on the latest offered to me by Google Play (1.0.2) which I realize is not the latest released one. Let me try to trigger Google Play, maybe it trickled through by now...

**Comment by simonspa** [comment]
I'm on version 1.2.1 now but still have the same behavior: the keyboard opens no matter whether it is a new card that is created or an existing one I just opened for viewing.

**Comment by stefan-niedermann** [comment]
This should already be included since a `0.x.x`-version, so ...

What exact device are you using?

**Comment by simonspa** [comment]
It's an Oneplus X (`onyx`) with LineageOS, i.e. Android 7.1.2

**Comment by desperateCoder** [comment]
OnePlus 3 on Colt OS  Android 10 here. Works as desired for me... That's weird, because @stefan-niedermann uses Lineage as well (Poco F1). Maybe an exotic setting in the rom options?

**Comment by simonspa** [comment]
Not that I'm aware of - it's the (pretty old) standard installation, the last one they offered for this device...

**Comment by stefan-niedermann** [comment]
I will have a look 👀  with an emulator, but i can't promise anything for old custom roms, unfortunately 🤷‍♂️

**Comment by stefan-niedermann** [comment]
Sorry @simonspa i am not able to reproduce this issue on my physical device nor on an emulator.

Are you able to try this on another device (like friends or families)? If you need a free voucher for Play Store you can contact me at info@niedermann.it or use F-Droid.

**Comment by simonspa** [comment]
Hi @stefan-niedermann - incidentally I bought a new device just last week and I can report that it works just as intended on Android 10 / Google Pixel 4. I guess we can close this ticket...

**Comment by stefan-niedermann** [comment]
Thank you for the feedback. I guess it was specific to this exact LineageOS build - keyboard handling on Android is a bitch. Glad to hear it works for you now :slightly_smiling_face:

**Comment by tamas646** [comment]
I experience the same issue on Samsung Galaxy S7 stock ROM (Android 8).

Deck app version: 1.24.5

How can I help debugging this behaviour?
