### ISSUE TITLE
Checkbox markup no longer working with update to version 1.0

### ISSUE THREAD

**Issue by motifsmedia** [stefan-niedermann/nextcloud-deck#474]
Previously checkbox markup was working by simply doing this in a card's description
`[ ] this is a checkbox. `

Now the above does not render a checkbox, but instead renders the text as the literal `[ ]`

All of my previous cards that used checkboxes are no longer working. This was a great way to add sub tasks to a single card.

I have found that a checkbox can work if it is preceded by a hyphen such as this `- [ ]`

I noticed this because I was using nested lists to have multiple levels of checkboxes for some card. 

Using the hyphen method will show the checkbox count indicator on the card itself, not the 
card details panel, as it did previously.

Here is what the checkbox markup looks like:

![checkbox-markup](https://user-images.githubusercontent.com/28070752/81458535-b991b780-914f-11ea-93f5-a5e387e8036d.png)

Here is what is displayed when previewed:

![checkbox-preview](https://user-images.githubusercontent.com/28070752/81458536-ba2a4e00-914f-11ea-8200-f3d30efa2c53.png)

Here is what is displayed on the card:

![checkbox-card](https://user-images.githubusercontent.com/28070752/81458534-b8f92100-914f-11ea-82d2-95d18aaec3ca.png)

**Comment by stefan-niedermann** [comment]
Hi, wrong repository, buddy. This is only about the Android app.

But there is already an open issue describing the problem in the correct repository: https://github.com/nextcloud/deck/issues/1828

You should upvote and subscribe to it 🙂.

Regards
