### ISSUE TITLE
Import and export decks

### ISSUE THREAD

**Issue by bugzy** [stefan-niedermann/nextcloud-deck#483]
**Is your feature request related to a problem? Please describe.**
I would like the ability to import my list of tasks into decks. However, there is no way to do that.

Possible simple solution:
An import from and export to CSV will be best. Kanboard uses CSVs with the following column format that I think will work here also: 
Title | Description | Assignee Username | Creator Username | Color Name | Column Name | Category Name | Swimlane Name | Complexity | Time Estimated | Time Spent | Start Date | Due Date | Priority | Status | Tags | External Link

Possible alternative solution
Another possibility will be to import tasks from and export to ical (ics), which will open the way for further collaboration with the tasks and calendar apps in nextcloud.

**Comment by stefan-niedermann** [comment]
I think this is something that should be implemented in the web interface. I don't see a real use case for this feature in the Android app at the moment.

https://github.com/nextcloud/deck/issues/new?template=Feature_request.md

**Comment by bugzy** [comment]
Ah. I intended this for the web interface but put it in the wrong issue tracker
