### ISSUE TITLE
cloud a deck notification open the deck app?

### ISSUE THREAD

**Issue by jakobroehrl** [stefan-niedermann/nextcloud-deck#486]
Is it possible to open the deck app (with the mentioned card) when the user clicks on a deck notification?

**Comment by stefan-niedermann** [comment]
Yes, we already support this on our side, but to make it work, this PR has to be merged first: https://github.com/nextcloud/android/pull/5825 (and the Nextcloud Android app has to be released of course).

**Comment by jakobroehrl** [comment]
Very nice, thanks!
