### ISSUE TITLE
Archiving cards is not responsive

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#488]
Archiving a card using the three-dot-menu seems to do nothing. Though the card is archived in the background which will result in the following behavior:
- "Archiving" a card a second time will result in a sync error which basically says "`500` this card is already archived"
- Completely closing and restarting the app will make those cards disappear

### Analyse

The `LiveData` fires correctly, and the card has the updated flag `archived: true`.

![grafik](https://user-images.githubusercontent.com/4741199/81788275-92960580-9502-11ea-9e1f-c311d6c9546f.png)

Currently i suspect `DataBaseAdapter#getFullCardsForStack` to not filter `archived` cards.
Before we implemented filters, we used another method, i guess, this old method filtered for `archived` cards, but the new one doesn't.

@desperateCoder Kobra, übernehmen Sie.

**Comment by desperateCoder** [comment]
@stefan-niedermann please test
