### ISSUE TITLE
Crash after moving newly created list to the left

### ISSUE THREAD

**Issue by niccokunzmann** [stefan-niedermann/nextcloud-deck#489]
I opened the app and the default board appeared. I added a new list with the plus button next to the other lists. This list was selected. Then, in the ... menu, I clicked "move to left". Then, the app showed me this:

```
App Version: 1.2.1
App Version Code: 1002001
App Flavor: fdroid

Files App Version Code: com.nextcloud.client

---

OS Version: 3.0.101-lineage-g660d639(eng.rinand.20200320.082650)
OS API Level: 28
Device: GT-I9100
Manufacturer: samsung
Model (and Product): GT-I9100 (GT-I9100)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'it.niedermann.nextcloud.deck.model.Stack it.niedermann.nextcloud.deck.model.full.FullStack.getStack()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$swapStackOrder$19$SyncManager(SyncManager.java:616)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$2z5CygK-fBR8Y6et-ZbrYpUk2ow.run(Unknown Source:8)
	at java.lang.Thread.run(Thread.java:764)

```

Apologies: I am reporting so many crashes because I have FastHub-libre installed and thus it is easy for me to report. However, FastHub-libre does not use the issue templates, yet.

**Comment by niccokunzmann** [comment]
After re-opening the app, I see that there is no card created. I guess this could be a race condition: No card was created on the server but still there this card should be moved.

**Comment by stefan-niedermann** [comment]
@niccokunzmann Are you able to reproduce this issue in the latest version?

**Comment by niccokunzmann** [comment]
My phone broke, so at the moment, I can not. I may probably do it once I transferred all to another phone.

**Comment by stefan-niedermann** [comment]
So i would suggest to simply open a new issue if you were able to reproduce the problem so we can have a deeper look - i haven't been able to force this error yet 🙂

**Comment by niccokunzmann** [comment]
Yes, this is fine. I wonder: The smartphone I had was very slow. Maybe 
this made it easier for race-conditions to appear. (no need to answer this)

Am 07.07.20 um 21:29 schrieb Niedermann IT-Dienstleistungen:

**Comment by stefan-niedermann** [comment]
Yeah, i guess so. I try to test new app versions with low-end emulated devices though (128 MB RAM, single core, Android 4.2,...)
