### ISSUE TITLE
Filter does not seem to work as expected

### ISSUE THREAD

**Issue by kbeerepoot** [stefan-niedermann/nextcloud-deck#492]
**Describe the bug**
The filter functionality does not seem to work as expected. As an admin who created the board, I have granted acces to that board to a specific user group (not the individual members of that group). I have subsequently assigned specific cards to specific users **of that group**, but when I try to apply a filter I only see the admin and the group name that the users belong to as options to filter on. This problem only appears when using the Android Deck app. Using the desktop/web version the complete list of users shows up.

**To Reproduce**
1. Log in as admin to desktop/web version
2. Create a board
3. Grant acces to a specific user group
4. Create cards
5. Assign cards to specific users of the specific user group
6. Start the Android Deck app
7. Open the specific board in the app
8. Open the filter interface
9. Notice that the specific assigned users are not available as choice options

**Expected behavior**
Self-explanatory

**Screenshots**
Not available

**Smartphone (please complete the following information):**
- Device: Motorola moto g(6) play
- Android-Version: 9
- App-Store: F-Droid

**Comment by stefan-niedermann** [comment]
@desperateCoder i think this is a direct consequence of the issue which tobi explained to us about user discoverability?

**Comment by stefan-niedermann** [comment]
Might reference https://github.com/stefan-niedermann/nextcloud-deck/issues/415#issuecomment-626688314

**Comment by kbeerepoot** [comment]
> Might reference [#415 (comment)](https://github.com/stefan-niedermann/nextcloud-deck/issues/415#issuecomment-626688314)

Sorry, I **did** run a search for related keywords before I created this issue, but I have to say that the content of '#415' is too conceptual to hit on my search.

**Comment by stefan-niedermann** [comment]
No problem. I want to make sure first, that both issues have the same cause :)

**Comment by desperateCoder** [comment]
Hi @kbeerepoot, thanks for your report!

I guess we have kind of a feature request here, since i have to admit, that i was completely unaware of groups. At the moment I don't even know how i can gather the needed group information, since the REST-API i am talking to won't tell me yet.

I'll see what i can do about this, but it might take some time, sorry.

**Comment by desperateCoder** [comment]
Ok, so I dug into the topic of users/groups and thought a bit more on this specific issue. You said, the _users_ (_not_ the groups) are assigned to the cards. This means, the app _does_ know about the users. The problem might be, that the `AccessControlList`s are written for the group, letting the App think, the users wouldn't have permissions on this card anyways, thus it hides those.

Could you please confirm this theory by doing the following?
* share the board with a random user of the mentioned group (should work from app as well)
* try filtering by that user (if share was made by the web-client, synchronize first)

If you can filter by the user then, I think I could fix this for you.

**Comment by kbeerepoot** [comment]
Artur,




Indeed, the app does know about the users. This is proven by the fact that it shows the avatar of the user on the card in the app if that card is assigned to that specific user.




If I try to assign that card to an extra user though, the choice list that shows up will only show the owner of the board and the assigned group(s) name(s). But extra names to assign that card to can be searched for manually though, and their avatar will then show up on the card also. That name or those names will still not show up on the filter list though, even if the extra name(s) is/are member(s) of the group that the board is shared with already.




Conform your suggestion I shared the board with a user that was already member of the group that the board was already shared with, and indeed, that user now shows up in the filter list in the app (already did in the web-client) and can be used to filter cards in the app.




I hope that this provides you with the necessary information.




Kees




On Sun, Jun 28, 2020 at 6:52 PM +0200, "Artur" <notifications@github.com> wrote:















Ok, so I dug into the topic of users/groups and thought a bit more on this specific issue. You said, the users (not the groups) are assigned to the cards. This means, the app does know about the users. The problem might be, that the AccessControlLists are written for the group, letting the App think, the users wouldn't have permissions on this card anyways, thus it hides those.


Could you please confirm this theory by doing the following?

share the board with a random user of the mentioned group (should work from app as well)
try filtering by that user (if share was made by the web-client, synchronize first)



If you can filter by the user then, I think I could fix this for you.

**Comment by desperateCoder** [comment]
Yep, this helps a lot! Everything you say sounds like we got the bad guy here. Thanks so far! I'll see what I can do about it now.

**Comment by desperateCoder** [comment]
@stefan-niedermann we did implement the user search including the debounce, i think for board-ACL? Could we adapt that endpoint to get valid users? I think the group-handling would be server-side, so maybe this solution would work? What do you think?

**Comment by stefan-niedermann** [comment]
Shipped in version `1.9.7`.
