### ISSUE TITLE
📦 Archive all cards of a stack

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#495]
# Backend

- [x] Implement in `SyncManager`: `public WrappedLiveData<Void> archiveCardsInStack(long accountId, long stackLocalId)`

# UI

- [ ] Add entry in column menu

**Comment by desperateCoder** [comment]
done. see ae537258366c91c183e3329673ed7ae797d877ee

`SyncManager`: `public WrappedLiveData<Void> archiveCardsInStack(long accountId, long stackLocalId)`
