### ISSUE TITLE
DueDate not saved properly

### ISSUE THREAD

**Issue by desperateCoder** [stefan-niedermann/nextcloud-deck#505]
**Describe the bug**
When you set the time at 14:00 pmand saves it get changed at 2:00 am

It is sent correctly to the server, the response is also correct, but parsing the response seems to mess up the time value of the due date.

Thanks to Edu P.G. for finding this issue!

**Comment by desperateCoder** [comment]
@stefan-niedermann please also test and close

**Comment by stefan-niedermann** [comment]
Tested and confirmed to work.

Will be shipped with `1.4.2`.
