### ISSUE TITLE
Wrong checkmark direction in RTL layout

### ISSUE THREAD

**Issue by ahangarha** [stefan-niedermann/nextcloud-deck#511]
**Describe the bug**
When the layout is RTL (due to system language being set to Persian, Arabic, Urdu,...) the checkmark in cards is shown in wrong direction. It shouldn't flip as it is used the same way it is used in LTR.

**To Reproduce**
1. Set the phone language as one of RTL languages
2. make card in Deck with checkboxes
3. the checkmark is shown while it is flipped horizontally

**Expected behavior**
 It shouldn't flip as it is used the same way it is used in LTR.

**Screenshots**
![image](https://user-images.githubusercontent.com/11241315/82923516-5649b700-9f90-11ea-906f-d616ca71ae55.png)

**Smartphone (please complete the following information):**
- Device: Moto G5s Plus
- Android-Version: 8.1.0
- App-Store: 
  - [ ] Google Play Store
  - [x] F-Droid

**Comment by stefan-niedermann** [comment]
After i read your issue at the server repository i wanted to contact and ask you to check the android app as well ;-).

Thank you very much and please open more issues if you find more left/right errors. You don't need to fill the full issue template, the screenshot and a hint what is wrong will be enough.

In case you want a free Play Store voucher (i saw you are using F-Droid), send me an email (info@niedermann.it)

**Comment by stefan-niedermann** [comment]
Will be fixed in next release.
