### ISSUE TITLE
Activities do not load deterministically

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#518]
Sometimes the activities do not load.
In the web app they are displayed, but in the app not. This is different from card to card (within one board) and seems not to depend on the internet connection (tried several times while connected to wifi).

**Comment by desperateCoder** [comment]
see https://github.com/stefan-niedermann/nextcloud-deck/commit/b4aeaa9b0868419f06ebe7374f11d4aa3a3b0ba4 

there was a new activity type missing.
