### ISSUE TITLE
Old translations are causing rendering issues

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#519]
@rakekniven i found some translations (`b+en+001` and `nb-rNO`) which are outdated.

![grafik](https://user-images.githubusercontent.com/4741199/84157186-ba797a00-aa6a-11ea-9832-169ee93889d2.png)
![grafik](https://user-images.githubusercontent.com/4741199/84157429-0a584100-aa6b-11ea-8787-f394e987786e.png)

This is mostly not a huge issue, but in this case there are some HTML fragments. We removed all the HTML stuff from the strings and do it in the code, so the translations are easier.

Unfortunately this causes rendering issues in those languages:

![Screenshot_2020-06-09-14-12-31-062_it niedermann nextcloud deck play](https://user-images.githubusercontent.com/4741199/84157514-1c39e400-aa6b-11ea-922d-e39b73e5a7a3.jpg)

Would you in general advice us to use new keys if the text changes (so we never have correct but only incomplete translations) or to change the value?

The first approach would cause a ton of more work for you, the latter would it probably make way easier to get complete translations :thinking: ?

**Comment by rakekniven** [comment]
Haven't we discussed and fixed this recently?
Just had a look at one norway string and it is ok at Transifex.
When did you search the strings?

**Comment by stefan-niedermann** [comment]
Current `master` and `transifex` branch both say that there are still HTML tags: https://github.com/stefan-niedermann/nextcloud-deck/blob/master/app/src/main/res/values-nb-rNO/strings.xml

Last changes in `nb-rNO` have been made in december: https://github.com/stefan-niedermann/nextcloud-deck/commits/master/app/src/main/res/values-nb-rNO/strings.xml

I think it was either another language or it was at the Notes app.

**Comment by rakekniven** [comment]
See here:
![grafik](https://user-images.githubusercontent.com/2069590/84165263-cb7ab900-aa73-11ea-85fa-900521966a08.png)

**Comment by stefan-niedermann** [comment]
Strange, updates from transifex are incoming on a daily basis.

Today, yesterday, ...

![grafik](https://user-images.githubusercontent.com/4741199/84165534-1d234380-aa74-11ea-824b-20dc4271f37b.png)

**Comment by rakekniven** [comment]
Puuh, think we have to ask @MorrisJobke for help

**Comment by stefan-niedermann** [comment]
@MorrisJobke is currently not available, but Joas responded with this hint:

>  So we only export languages which have I think 50% coverage
so if the package dropped it might not update anymore, and maybe the removal failes due to android repo logic

And according to https://github.com/nextcloud/docker-ci/blob/master/translations/handleAppTranslations.sh#L80 it looks like the `xml` files are not getting deleted if they have once been integrated and then fell below the 50% mark.

@rakekniven is it possible that those translations are below 5ß%? In this case it might make sense to delete them on the app side? They should be reattached as soon as they reach 50% again, i guess.... :shrug:

**Comment by stefan-niedermann** [comment]
Temporarily solved by completely removing `b+en+001` and `nb-rNO` for now.

Further tracking of this issue in https://github.com/nextcloud/docker-ci/issues/230 because all other Android apps are affected as well.

**Comment by rakekniven** [comment]
> @rakekniven is it possible that those translations are below 50%? In this case it might make sense to delete them on the app side? They should be reattached as soon as they reach 50% again, i guess.... 🤷

Hello Stefan, 

sorry for my late response. 

English is at 100%
![2020-06-17_18h19_21](https://user-images.githubusercontent.com/2069590/84923192-30af5980-b0c7-11ea-8003-5af26034da8f.png)

For norwegian see
![2020-06-17_18h18_58](https://user-images.githubusercontent.com/2069590/84923198-32791d00-b0c7-11ea-995f-5dfdb5eb4444.png)

That is mysteriuous.

**Comment by stefan-niedermann** [comment]
Huh. Strange. When i deleted those files, they were definitely below 50% in the repository.

Let's see what happens next time @nextcloud-bot comes around :man_shrugging:

**Comment by stefan-niedermann** [comment]
Just for documentation purposes: The [last pull from transifex](https://github.com/stefan-niedermann/nextcloud-deck/pull/537/files) did not contain one of the two languages.
