### ISSUE TITLE
Suggest user and labels in autocomplete when clicking on the EditText

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#52]
When clicking on the `EditText` to search for users and / or labels and the text is "" then a list of most used users / labels should be displayed until the first character has been entered.

**Comment by stefan-niedermann** [comment]
@desperateCoder see `DataBaseAdapter::validateSearchTerm` for comment hint what's missing and some ToDos for @desperateCoder. After this has been implemented, i can do the Frontend-Stuff

**Comment by desperateCoder** [comment]
@stefan-niedermann have a look at my commit linked above.
Please handle this stuff in UI as we agreed, because a search function should search and now there are proposal-functions for this purpose. if the user didn't enter anything yet, call propose, if he did, call search.

And don't forget to unsubscribe! :wink:

**Comment by stefan-niedermann** [comment]
@desperateCoder please implement `SyncManager::getLabelSuggestions` and `SyncManager::getUserSuggestions`. The UI should work out of the box as soon as this has been implemented.

**Comment by stefan-niedermann** [comment]
Sidenote: I got some inspiration for this topic here: https://stackoverflow.com/a/5783983

**Comment by desperateCoder** [comment]
Should work now, even tested it :stuck_out_tongue_closed_eyes: . But you should be aware of the fact that you wont' get any results, if there aren't any users / labels assigned on this board yet, since there is no data my query can be based on.

**Comment by stefan-niedermann** [comment]
Proposals should always be `topX` (if not enough data, just fill the list up with any other labels/users - if possible). Only valid reason for having less results than `topX` is if there are less than `topX` labels/users available at all.

**Comment by stefan-niedermann** [comment]
Note: When pressing `Enter` on the virtual keyboard after tabbing into the Labels-field the search is currently triggered which results in a

```
Version: 0.0.12

java.lang.IllegalArgumentException: please provide a proper search term! "
" doesn't seem right...
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.DataBaseAdapter.validateSearchTerm(DataBaseAdapter.java:426)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.DataBaseAdapter.searchLabelByTitle(DataBaseAdapter.java:396)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.searchLabelByTitle(SyncManager.java:657)
	at it.niedermann.nextcloud.deck.ui.card.LabelAutoCompleteAdapter$1.lambda$performFiltering$1$LabelAutoCompleteAdapter$1(LabelAutoCompleteAdapter.java:117)
	at it.niedermann.nextcloud.deck.ui.card.-$$Lambda$LabelAutoCompleteAdapter$1$Cy3cUcWeH9yubR2OGNcJHXXRoPE.run(Unknown Source:4)
```

**Comment by desperateCoder** [comment]
Uhm... What exactly can I do about it? Why is a single line input control even accepting a line feed?! I'd see this as a concern of the UI...

**Comment by stefan-niedermann** [comment]
This was a note for me, it is fault of the UI.
