### ISSUE TITLE
Add independent authentication method

### ISSUE THREAD

**Issue by varac** [stefan-niedermann/nextcloud-deck#527]
Currently, deck relies on Nextcloud Files for authentication SSO (see https://github.com/stefan-niedermann/nextcloud-deck/issues/14#issuecomment-443648978).

Installing the file apps only to authenticate deck is too much of a burden because it will grant access of my smartphone to all my files stored in nextcloud, which I don't want to because of security concerns (I use the desktop files app but don't want my smartphone access the files).
So a different authentication method would be much appreciated.

I know having one app responsible for SSO in the nextcloud cosmos, but when this is coupled with giving access to shared files it's not an option.

**Comment by varac** [comment]
See https://github.com/stefan-niedermann/nextcloud-deck/issues/14#issuecomment-644014074 as well for my comment at the closed issue.

**Comment by stefan-niedermann** [comment]
That's a pitty, but i'm afraid that this will not happen.

    only to authenticate deck

The way better UX is only a very small part of the advantages of this mechanism (and probably the only directly visible parts for users).

Other advantages are

    lock Security benefits: The Deck app does no longer store a password itself.
    electric_plug Reliability: All network activities are based on the official files app. This ensures the same support for self signed certificates, 2 factor authentication and many other edge cases
    rocket More time to implement and maintain the actual features

    it will grant access of my smartphone to all my files stored in nextcloud

This means that you either don't trust the Nextcloud app or you don't trust the security concept of Android. Every app is completely separated and can only access files if the user has granted access.

Not trusting Android is absolutely valid (i don't neither wink ), but you should probably have a look into completely open source custom ROMs without any Play Services (like i do wink ) and only install Apps which you can trust, e. g. from F-Droid. Everything else is fixing symptoms instead of really fighting the true issues.

**Comment by varac** [comment]
> Not trusting Android is absolutely valid (i don't neither wink ), but you should probably have a look into completely open source custom ROMs without any Play Services (like i do wink ) and only install Apps which you can trust, e. g. from F-Droid. Everything else is fixing symptoms instead of really fighting the true issues.

I use LineageOS, no google services and prefer apps from FDroid like you, but still I don't trust my Android smartphone less then my desktop. So I'd still like to make the destinction that I only want my laptop to access my shared files.

I can understand that you don't want to implement this. Maybe the issue is more on the Nextcloud files app side and I'll try to start there a discussion about seperating SSO from files access.

**Comment by stefan-niedermann** [comment]
> But still I don't trust my Android smartphone less then my desktop.

Absolutely valid :slightly_smiling_face:

Honestly i don't think that the SSO will be separated from the main Nextcloud app, good luck though. And i'm faithfully sorry that i can't help you here.

It's just - we are a very small development team and we have extremely limited resources and free time (which we also have to split for multiple open source projects), so we have to decide at some point whether or not the benefit is judging the effort.

**Comment by varac** [comment]
see https://github.com/nextcloud/android/issues/6294 for the feature request for the Nextcloud app to seperare SSO and file sync.

**Comment by tobiasKaminsky** [comment]
> because it will grant access of my smartphone to all my files stored in nextcloud,

You can disallow this setting. It should not be needed for SSO.

**Comment by varac** [comment]
> You can disallow this setting. It should not be needed for SSO.

Hugh, how ? I can't find any option to disable file sync/access.

**Comment by tobiasKaminsky** [comment]
Android settings -> app -> search for nextcloud -> permissions -> storage -> disable it

**Comment by varac** [comment]
> Android settings -> app -> search for nextcloud -> permissions -> storage

Well that would only disable *storing/syncing* files on my phone, but I want to disable *access* to files. NC app lets you choose which folders to sync/store and which not, but you can still access the latter ones, right ?

**Comment by tobiasKaminsky** [comment]
So you want to prevent Deck from having access to your files?
As you can add/link files to cards, this would be an artificial limitation, or?

**Comment by stefan-niedermann** [comment]
@tobiasKaminsky i think [he wants to prevent his phone from having access to his files](https://github.com/stefan-niedermann/nextcloud-deck/issues/527#issuecomment-644034924), because he doesn't trust his phone.

**Comment by tobiasKaminsky** [comment]
ah. If this this so, then you can change this in security settings on web for the token:
![image](https://user-images.githubusercontent.com/5836855/85126680-412e1400-b22e-11ea-81e9-6e11b5ca411e.png)

**Comment by stefan-niedermann** [comment]
Didn't even know that! Good to know, thanks. And maybe solves @varac issue

**Comment by varac** [comment]
@tobiasKaminsky Oh, awesome, I didn't know that neither, that's what I was looking for.
