### ISSUE TITLE
Change scroll behavior of edit mode

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#53]
When the edit mode does not fit into the screen (e. g. because of a huge description), then currently the scrollable area is only the details tab.
Instead the whole screen including the title and the tabs should be scrollable (ActionBar should stay fixed on top).

**Comment by stefan-niedermann** [comment]
Maybe useful: https://mobikul.com/viewpager/

**Comment by stefan-niedermann** [comment]
Sooo, i finally got this working (`53-change-scroll-behavior-of-edit-mode`), but i am not happy with it.

Have a look at the video:

![ezgif-1-06bba6c8fbca](https://user-images.githubusercontent.com/4741199/65781744-79477100-e14c-11e9-8bf0-969aff9a91a5.gif)

Given you have a large description (or a small screen) and you scroll down, everything looks awesome. But as soon as you swipe to the next tab, we have two possibilities:

1. (current, see video): One keeps the position, which is really confusing because one does not know where he is, because the tabs are at the top and not visible
2. every tab switch resets the position to the top, which looks buggy and flickering, because everything is so jumpy.

All in all i am not happy with either solution. Maybe something like a bottom nav would be a better pattern?

![grafik](https://user-images.githubusercontent.com/4741199/65781523-06d69100-e14c-11e9-935b-8f25b8a93ced.png)

Or just simply stacking all the contents below each other (no tabs, but simply put the attachments below the details and the activity below the attachments)?

cc @jancborchardt and @jenniferpiperek for your valuable opinion :)

**Comment by jancborchardt** [comment]
Is it possible to have the tabs sticky at the top, that is that they don’t scroll out of view?

**Comment by stefan-niedermann** [comment]
We could move the title into the details for now (and later into the blue toolbar as you suggested on the conf 2019, but that's a later step). It would make the title only editable in the details tab, but it would stay readable in the blue toolbar.

This way the tabs would always stick on the top (like in the About-section). Is this, what you suggested?

**Comment by jancborchardt** [comment]
That’s definitely a good step forward, yes. :) So the tabs would then also be blue, right?

**Comment by stefan-niedermann** [comment]
Okay, i implemented what we have discussed about previously:

![ezgif-5-a791a24eb0f6](https://user-images.githubusercontent.com/4741199/66717119-dfcbc080-edd5-11e9-845c-aa553cfcd071.gif)

**Comment by jancborchardt** [comment]
Seems very good! :) Nice one @stefan-niedermann
