### ISSUE TITLE
No due Date after creating a new Deck Entry

### ISSUE THREAD

**Issue by devz3r0** [stefan-niedermann/nextcloud-deck#535]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

No due date, even if you see the changed descriptopn field after the sync

**To Reproduce**
1. add a Deck entry.
2. fill it out
3. Add a due date

**Expected behavior**

See the due Date in the Deck app

**Screenshots**

**Versions**
 - Nextcloud: 18.0.6
 - Nextcloud Deck: 1.0.2
 - Nextcloud Android: 3.12.0
 - Nextcloud Android Deck: 1.4.4

**Smartphone (please complete the following information):**
- Device: Oneplus 7TPro
- Android-Version: 10
- App-Store:
  - [X] Google Play Store
  - [ ] F-Droid

**Stacktrace**

**Comment by desperateCoder** [comment]
Hi @devz3r0,
thanks for your report! 

Unfortunately both of us can't reproduce this behavior, creating a new card with due date, updating and deleting the due date works fine for us.

Is this a fresh server install of 1.0.2 or did you do an update?

Maybe we can reproduce this behavior on your server, could you provide us a test account? Just send the credentials to info@niedermann.it and we will have a look at it.

**Comment by devz3r0** [comment]
thanks it is working now again, it looks like it was a sync problem, so it did not get the due data at that time.
I removed the card and readded it, now it's there.
I was using blokada, perhaps that caused some interruptions too.

**Comment by stefan-niedermann** [comment]
Thank you very much for the update and let us know if you encounter any further issues which we will happily analyse :smile:
