### ISSUE TITLE
Sync doesnt work, endless loading

### ISSUE THREAD

**Issue by pilsnerbeer** [stefan-niedermann/nextcloud-deck#540]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

New cards dont get synced.

**To Reproduce**
1. I created a new card and waited for it to sync.

**Expected behavior**
cards get synced and appear in desktop instance

**Screenshots**
Notice the loading on the individual card (stuck loading forever) and the layout trying to refresh with updated data (also stuck).

![Screenshot_20200619-160727_1](https://user-images.githubusercontent.com/36133540/85142021-08029d80-b248-11ea-923d-af7fd92c593d.jpg)

**Versions**
 - Nextcloud: 18.0.4
 - Nextcloud Deck: 1.0.2
 - Nextcloud Android: 3.12
 - Nextcloud Android Deck: 1.4.4

**Smartphone (please complete the following information):**
- Device: op5t
- Android-Version: 10
- App-Store:
  - [ ] Google Play Store
  - [x] F-Droid

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Dear @pilsnerbeer,

- have you tried to clear the storage of **both** apps and then add your account again [as described here](https://github.com/stefan-niedermann/nextcloud-deck/wiki/FAQ)?
- I can see a card in your screenshot: Did the initial sync work or have you created the card locally?
- How many boards and card (estimated) do you have? The sync can take really long (even up to a minute) since the server does not support `ETags` yet which are very important for a performant synchronization

**Comment by pilsnerbeer** [comment]
1) I have reinstalled both apps.
2) No, that is a local card that is attempting to reach server (no success)
3) I have total of 3 boards. One board might have 50-100 cards but Deck server app has no problem loading it, only Android app seems to be struggling.

After reinstalling, I now can't get pass the welcome screen: (stuck again). I should also note the app worked fine a few months ago.

![Screenshot_1](https://user-images.githubusercontent.com/36133540/85157857-55890580-b25c-11ea-9925-3a88665aa210.png)

**Comment by stefan-niedermann** [comment]
Thank you for the information.

- Can you create a new test account on your server and try to synchronize with it? If the problem occurs there, too: Can you share the credentials of the test account with us for testing purposes (info@niedermann.it)
- What exactly did happen after you pressed "Choose account"? Have you seen the account pop-up and did you granted the permissions? What then? The circular spinner should have shown up then.
- Did you perform any update at the Android or Server side or was it out of all sudden?
- Are you using the boards alone or do you have some kind of shares? (If shares, please explain more how your setup is)

**Comment by pilsnerbeer** [comment]
I created a test account and everything immediately started working. I switched to my main account and there too, surprisingly, were no more issues. As if the app fixed itself somehow... The pull-to-refresh is still very slow (~20s) but creating cards is no longer stuck. I haven't changed any settings on my phone or server, it just started working ¯\_(ツ)_/¯

**Comment by stefan-niedermann** [comment]
😄 yeah... well... Let's categorize this as "server hickup". I really can't tell you anymore about it, sorry.

Would you mind notifying us if this happens again? Just reopen this issue or link this one please.

About the 20s sync: Yeah, it's a known issue and we rely on a issue at the server to support `ETags` for a better sync performance. We're working on it 😉
