### ISSUE TITLE
Add quick switch for multiple accounts

### ISSUE THREAD

**Issue by juliushaertl** [stefan-niedermann/nextcloud-deck#543]
When having multiple accounts configured it would be very helpful to have the small avatars accessible in the sidebar to switch between then without the need of another tap to get the account list.

This would basically align to how it is done in the files app:

![Screenshot_20200621-112410](https://user-images.githubusercontent.com/3404133/85221208-3ef4c280-b3b2-11ea-8756-7bab32bb15ce.png)

**Comment by stefan-niedermann** [comment]
We already have adopted the new account picker from the files app:

![Screenshot_20200621-114557_Nextcloud_Deck](https://user-images.githubusercontent.com/4741199/85221553-d5c27e80-b3b4-11ea-808e-70c4c9273a88.png)

The amount of steps to switch the account has been decreased.

It's already available at Play Store (Beta channel) and soon F-Droid.

**Comment by juliushaertl** [comment]
:see_no_evil: Sorry for the noise then, the update was pending and not yet downloaded by my phone yet. Looks nice and has the same effect requiring one tap less :+1:
