### ISSUE TITLE
Column should have card_spacing padding at the bottom

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#55]
Currently a column does not have a padding at the bottom, therefore it looks like the last card in the column is cut (when having enough columns to fill the screen). Each column should have a padding with the value `card_spacing` at the bottom. Pay attention to the scrollbar, because i tried it once and the scrollbar no longer was able to reach the top of the column.

**Comment by timkittel** [comment]
Hi Stefan,

thanks for the awesome project, I would love to see it working!

I was trying to have a look at this issue, but actually I don't even manage to see a stack/column. When connecting the Deck App to my cloud, it correctly identifies the boards, but when choosing the boards no stacks/columns are shown. Is there a trick that I am missing or is it currently not working? (:

Cheers,
Tim

**Comment by desperateCoder** [comment]
Hi @timkittel , please have a look at https://github.com/stefan-niedermann/nextcloud-deck/issues/57

The cause is the same one. If you have access to your server, then the needed steps are described in this issue (update deck webapp to dev-version)

**Comment by desperateCoder** [comment]
By the way, depending on your last pull, you should probably pull again ;)

**Comment by timkittel** [comment]
Thanks to both of you. Managed to set it up and submitted a PR (:

**Comment by desperateCoder** [comment]
@timkittel You're welcome buddy, thank you for your contribution!

**Comment by desperateCoder** [comment]
Thanks @timkittel!
