### ISSUE TITLE
Store colors as integer in database

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#556]
Current process:
----
- Validate colors retrieved from the REST API and manipulate it until something like `#abcdef` falls out
- Store it in database as String value
- After reading it, parse it again (multiple times since the account object itself does hold the string) and apply it to some elements

Problems:
----
- Each time one reads a color from the database, it needs to get parsed again
- Inconsistent backend APIs are directly mapped into the database:
  - The `capabilities` endpoint returns a color with `#` at the beginning
  - The `Board#color` is always with**out** a leading `#`
  - Those differences are stored in database and have to get managed differential every time one reads them

Suggestion:
----
- Store the values as `@ColorInt int color;` (result of `Color.parseColor()`) in the database
- This way one can directly use and apply it after reading it from the database
- One does not have to care about the exact format (with or without `#`, 3 or 4 or 6 or 8 characters, ...)
- As a result way less error prone and more performant

Disadvantages:
----
- One can not directly read which color is stored in the database if one looks at the database directly

Implementation:
----
- Account
  - [ ] Remove `textColor` (we don't need this anymore)
  - [ ] Change type of `color` to `@ColorInt int`
  - [ ] Database migration: It is necessary to [copy everything to a temporary table and back](https://stackoverflow.com/a/52237688). Each color should already be parsable via `Color.parseColor`, because we used `ColorUtil.formatColorToParsableHexString` before writing into the database. Though use a `try-catch` block and use `ContextCompat.getColor(context, R.color.defaultBrand) as fallback)
  - [ ] Keep API (use `String.format("#%06X", (0xFFFFFF & color))` to main backward compatibility)
- Board
  - [ ] Change type of `color` to `@ColorInt int` 
  - [ ] Database migration (see Account)
  - [ ] Keep API (use `String.format("#%06X", (0xFFFFFF & color))` to main backward compatibility)
- Label
  - [ ] Change type of `color` to `@ColorInt int` 
  - [ ] Database migration (see Account)
  - [ ] Keep API (use `String.format("#%06X", (0xFFFFFF & color))` to main backward compatibility)

After this has been done, we can use the new API in the UI.

**Comment by desperateCoder** [comment]
Any solution for conversion? Migration-fails incoming! I promise! We would need to add a new column, read all values in the old one, convert them (this is the error prone part), write them in the new one and delete the old column.

Since there might be quite weird values out there, I am concerned, this might fail too often, but we can try, since your arguments are pretty valid.

**Comment by stefan-niedermann** [comment]
All the cases which would fail to migrate are actually failing quite hard today - each time one reads a column :wink:

Therefore when we migrate, we should put a pretty big `try { ] catch (Throwable t) {}` around it and set a default value.
