### ISSUE TITLE
Authenticate

### ISSUE THREAD

**Issue by treuss** [stefan-niedermann/nextcloud-deck#558]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions**
 - Nextcloud: 
 - Nextcloud Deck: 
 - Nextcloud Android: 
 - Nextcloud Android Deck: 

**Smartphone (please complete the following information):**
- Device: 
- Android-Version: 
- App-Store:
  - [ ] Google Play Store
  - [ ] F-Droid

**Stacktrace**

**Comment by desperateCoder** [comment]
Uhm... Did this happen accidentally or was ist meant as a real issue? 😕 😀

**Comment by treuss** [comment]
Actually I wanted to open an issue, but thanks to my clumsy finger I hit the submit button on my mobile. 😒🤭

**Comment by desperateCoder** [comment]
😆 ok, then just try again 🤷‍♂️
