### ISSUE TITLE
Discussion: Use @WorkerThread instead of ...Directly convention

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#560]
Currently we have a convention that in `SyncManager` and the `...Adapter`s we name a method `...Directly()` if it must not be called from UI thread.

I propose to instead use the `@WorkerThread` annotation instead.

Javadoc of the annoation:

```java
/*
 * Denotes that the annotated method should only be called on a worker thread.
 * If the annotated element is a class, then all methods in the class should be called
 * on a worker thread.
 */
```

This will allow advanced benefits for the linter and better IDE support (at least in some situations) when calling this kind of method:

![grafik](https://user-images.githubusercontent.com/4741199/85921845-88945000-b87f-11ea-8ca3-18d321e8ce49.png)

Additionally we could think about explicitly use the [`@AnyThread`](https://developer.android.com/reference/androidx/annotation/AnyThread) annotation for the other methods. This indicates that the methods are thread safe (not sure if they really are?).

**Comment by desperateCoder** [comment]
I don't even care tbh. If you find this helpful, we can do this, no problem at all. Personally i don't really need this, but i understand that it would be helpful for you in some cases

**Comment by stefan-niedermann** [comment]
Okay, then i will do it. 🙂

**Comment by stefan-niedermann** [comment]
Added thread annotations.

Will keep the naming convention because linter does not show proper wanings in some situations.
