### ISSUE TITLE
Can't save note from Android app

### ISSUE THREAD

**Issue by xplosionmind** [stefan-niedermann/nextcloud-deck#576]
After clicking on the "V" to save a note in a list, I get this error message. It includes also data about my device and the version of the app.

```
App Version: 1.5.4
App Version Code: 1005004
App Flavor: fdroid

Files App Version Code: 30120090

---

OS Version: 4.9.179-perf+(2002220019)
OS API Level: 29
Device: OnePlus6T
Manufacturer: OnePlus
Model (and Product): ONEPLUS A6013 (OnePlus6T)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardPropagationDataProvider.createOnServer(CardPropagationDataProvider.java:22)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardPropagationDataProvider.createOnServer(CardPropagationDataProvider.java:12)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:96)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:80)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$updateCard$27$SyncManager(SyncManager.java:904)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$e3CkeNUm6klHgpxESZl2i8zpJuM.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by stefan-niedermann** [comment]
Have you already tried the steps i linked in your other issue?

**Comment by xplosionmind** [comment]
@stefan-niedermann I did

**Comment by stefan-niedermann** [comment]
Then please fill out the complete issue template. It is important to know the exact steps you are doing (opening an existing card? creating a new card? what did you change before submitting?...) and also the versions of the Deck server app is important. We need more information to help you.

Please try in the meantime to edit / create cards at another board and report whether this works. If not: Create a testing account at your Nextcloud and try it there (so we can fence the issue and see whether it is only related to your account).

**Comment by stefan-niedermann** [comment]
[Why this bug report has been closed](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed)

**Comment by xplosionmind** [comment]
Sorry if I didn't provide all of the necessary info. Anytime I try to both edit or create a card from the Android app, I get the error message above. From the web interface everything works fine. This issue is still happening in version 1.8.2 of the android app, and in the latest version of the online one.

**Comment by stefan-niedermann** [comment]
It seems like you don't even read what i am writing. (For example: [Did you create a test account and have you been able to reproduce the issue there?](https://github.com/stefan-niedermann/nextcloud-deck/issues/576#issuecomment-653195826)). This is quite disrespectful for a free support.

Please [open a new issue](https://github.com/stefan-niedermann/nextcloud-deck/issues/new?labels=bug&template=bug_report.md) and **fill in the complete issue template**. There is missing so much information (like server version, just to mention one) and i am honestly *too tired to ask for each and every detail*.
