### ISSUE TITLE
View Archived Cards

### ISSUE THREAD

**Issue by Sandman0984** [stefan-niedermann/nextcloud-deck#578]
Please consider adding a feature to show archived cards.  I can do it using the Nextcloud website, but not using the Android app.  Thank you!

**Comment by Sandman0984** [comment]
Duplicate issue, sorry!

**Comment by stefan-niedermann** [comment]
No problem :slightly_smiling_face: 

We plan to implement this feature but it is currently blocked because of performance concerns. Please be patient, it will definitely come at some point, as soon as we found a proper way to handle this :)
