### ISSUE TITLE
Compact view

### ISSUE THREAD

**Issue by splashote** [stefan-niedermann/nextcloud-deck#579]
Hey,

it would be great to have a compact view, where each card is shown in one line.

Imho it would facilitate working with the app.

Thanks + regards!

**Comment by stefan-niedermann** [comment]
Yeah, i'm not 100% sure about this one. I'v heard some rumors that corresponding feature of the Web UI might get removed in the long term. Maybe the server app maintainer @juliushaertl can tell us more about his future plans for the compact mode, so we can plan this feature here appropriately?

**Comment by juliushaertl** [comment]
Honestly I don't have a really strong opinion on the compact view, i can see its use case to get a quicker overview but also with the new filter possibilities we have in the web app you could also just limit the display to relevant cards so I'm not sure if it is still that important. Not sure what to do there, I'm sure that we get quite some complains when we just drop it.

**Comment by stefan-niedermann** [comment]
Will be shipped in version `1.7.0`.

**Comment by splashote** [comment]
Hey,
thanks a lot for the implementation! It's great to have it!

A comment: I'd prefer to see the button at the side of the 'Filter' button in the main view and not in the settings. The nc app puts it there, too.

**Comment by stefan-niedermann** [comment]
Depends on https://github.com/nextcloud/deck/issues/2127 - if the server changes the context, the android app will follow :)

**Comment by splashote** [comment]
Ok, thanks for the link. 

At the moment, the android app does not follow the server, right? :)

**Comment by stefan-niedermann** [comment]
We are following the context but not the position of the icon. Let's discuss this in the server repository, the android app will follow 😉
