### ISSUE TITLE
Übersetzung =/= Übersetzer

### ISSUE THREAD

**Issue by splashote** [stefan-niedermann/nextcloud-deck#580]
Moin,

ich fände es dem inklusiven Anliegen von nextcloud angemessen, wenn unter 'Credits' _Übersetzung_ anstelle von _Übersetzer_ stehen würde.

Besten Dank und viele Grüße!

Fabian

**Comment by stefan-niedermann** [comment]
Moin,

[ich bin der Meinung](https://help.nextcloud.com/t/geschlechtsneutrale-sprache-genderneutral/82200/12?u=stefan-niedermann), dass Inklusion für alle offen stehen sollte - auch Personen aus eher bildungsfernen Schichten oder Personen mit Krankheiten wie Lese- und Rechtschreibstörungen, für die diese Art der Formulierungen sehr schwer zu erfassen und zu lesen sind. Zu oft schon, habe ich im eigenen Umkreis das Gefühl von Ausgeschlossenheit wahrgenommen, das durch Formulierungen entsteht, die eben auch den Lesefluss erheblich erschweren.

Des Weiteren sehe ich in dem konkreten Beispiel kein Problem, da die Personengruppe der "Übersetzer" sowohl "weibliche Übersetzer", "männliche Übersetzter", "bisexuelle Übesetzer", "transsexuelle Übersetzer" sowie alle weiteren Personengruppen einschließt. Der Artikel "der" bezieht sich hier auf das Wort "Übersetzer" und die beschreibende Tätigkeit, nicht auf die Person/en, die diese Tätgikeit ausführen.

Leider scheint mir das Konzept der Gender-neutralen Sprache als solches nicht vollends durchdacht zu sein und mehr Probleme zu schaffen, als zu lösen. Da es abgesehen von ein paar [Privat-Projekten](https://geschicktgendern.de/) keinen offiziellen Standard dieser Sprachform gibt, führt sie derzeit zu Zersplitterung und unwichtigen Grabenkämpfen innerhalb der Personen die eigentlich den selben Gedanken verfolgen: Gleichberechtigung und Inklusion.

Ich hoffe daher inständig, dass alle Gleichgesinnten, die sich für dieses Thema interessieren, auch tatsächlich Taten im echten Leben sprechen lassen, und nicht nur Wörter verbieten und Texte ändern (dies hatten wir bei George Orwell 1984 schon einmal :wink: ). Gleichberechtigung und Inklusion beginnen letztlich beim Gedanken.

**Da dieser Begriff von den Übersetzern selbst geschrieben wurde, überlasse ich es letztlich diesen, wie sie die Sprache konkret übersetzen.**

Dennoch vielen Dank für den Beitrag - Es gibt übrigens eine Liste mit "[Good first issues](https://github.com/stefan-niedermann/nextcloud-deck/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)", falls du dich weiter in diesem Projekt einbringen möchtest :slightly_smiling_face: :rocket: 

---

Disclaimer: Nextcloud Deck Android ist komplett unabhängig von der Nextcloud GmbH und wird von anderen Personen entwickelt und vertrieben.

**Comment by stefan-niedermann** [comment]
PS.: Ich habe gerade gesehen, dass du `Übersetzung` anstelle von `Übersetzende` vorgeschlagen hast.

Der Begriff `Übersetzung` wäre zumindest semantisch einigermaßen korrekt¹, da ich aber persönlich der Begriff `Übersetzer` nach wie vor für den korrekten Terminus halte, werde ich hier nicht aktiv werden und überlasse es, wie im letzten Kommentar bereits gesagt, den Übersetzern, dies zu übernehmen oder auch nicht.

Offen gestanden baue ich lieber Features ein, von denen **alle** Menschen profitieren, als mir über die seltsamen Blüten der deutschen Sprache den Kopf zu zerbrechen :smile: .

¹`Übersetzende` beschreibt eine Gruppe von Personen, die in exakt diesem Moment eine Übersetzung anfertigen und hat daher eine semantisch andere Bedeutung, da bereits angefertigte oder noch anzufertigende Übersetzungen hierbei nicht berücksichtigt werden.

**Comment by splashote** [comment]
Moin,

erst einmal freut es mich, dass du dich der Inklusion verschrieben siehst und dir die Mühe einer langen Antwort machst.

Es mag derweil sein, dass alle Menschen mit 'Übersetzer' gemeint sind, dass Sprache aber nicht mit 'meinen' funktioniert sondern vielschichtiger wirkt ist wissenschaftlich belegt:
https://www.researchgate.net/publication/247397952_Effekte_des_generischen_Maskulinums_und_alternativer_Sprachformenauf_den_gedanklichen_Einbezug_von_Frauen

Den Link habe ich mir mal von Jan geborgt, ich finde er hat in den beiden Threads zu Inklusion gute Beiträge gemacht:
https://help.nextcloud.com/t/abstimmung-geschlechterneutrale-sprache/82855/18
https://help.nextcloud.com/t/geschlechtsneutrale-sprache-genderneutral/82200

Ich werd am Prozess der stärkeren inklusiven Prägung der Sprache in nextcloud dran bleiben, schauen wir mal, wie sich das entwickelt.
