### ISSUE TITLE
Add the option to "Collapse Cards" in the mobile version just like in the server app 

### ISSUE THREAD

**Issue by Thieum4** [stefan-niedermann/nextcloud-deck#588]
Hi, I am not sure if you are planning to add this feature on the mobile version, but I really would appreciate it.
Thanks for all the work.

**Comment by stefan-niedermann** [comment]
It is not only planned, it is already done and will be shipped in version `1.7.0`. You can already get this version at the [Play Store beta channel](https://play.google.com/apps/testing/it.niedermann.nextcloud.deck.play) and soon on F-Droid. 🙂 

Please use the search function in the future to avoid opening duplicate issues https://github.com/stefan-niedermann/nextcloud-deck/issues/579

Cheers 👋

**Comment by Thieum4** [comment]
Okay, I've downloaded the beta version, great addition :) ! Do you think it might be possible to add a "toggle compact view" entry in the board menu (i.e these 3 vertical dots right side of the lists) to quickly change view ?
Regards

**Comment by stefan-niedermann** [comment]
Technically possible: Yes.

But sorry, this is nothing i plan to implement for various reasons like the limited space, the completely different context (the state of this setting is preserved across the different boards = application wide, while the context of the location you proposed is reserved for "within one board settings"), and so on.

I thought about it for some time but came to the conclusion that this is better as a global setting (and [actually i suggested to the web ui to follow this decision](https://github.com/nextcloud/deck/issues/2108))

**Comment by stefan-niedermann** [comment]
Also this 3-dot-menu is meant for actions but not for settings. In my opinion this will lead to more confusion than the current position.

**Comment by Thieum4** [comment]
Ok i see now, thanks for the insights.
