### ISSUE TITLE
Add filter "unassigned cards"

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#590]
For feature parity with server: [issue](https://github.com/nextcloud/deck/issues/1807) and [PR](https://github.com/nextcloud/deck/pull/1926).

- [x] Add a property `boolean noAssignedUser` to `FilterInformation` model
  - [x] Update copy constructor and `toString`
- [x] Respect this property in `SyncManager#getFullCardsForStack`
  If `noAssignedUser` is `true`, the method should return cards which have no assigned user **or** any of the assigned users in the `users` list. If `noAssignedUser` is `false`, the logic is the same as today.
- [x] UI: In filter dialog, tab "users", there should always be a dummy user at the very top with the label "unassigned" and an appropriate icon as avatar.

**Comment by desperateCoder** [comment]
see draft PR https://github.com/stefan-niedermann/nextcloud-deck/pull/595

should work, but couldn't test (no UI)
