### ISSUE TITLE
"A session had already been started" log errors

### ISSUE THREAD

**Issue by pilsnerbeer** [stefan-niedermann/nextcloud-deck#593]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

I have started noticing a huge list of log errors related to deck + deck Android app. Log message sample:

`"reqId":"MDX1Frphz4iGuZhAcOGd","level":3,"time":"2020-07-13T14:31:59+00:00","remoteAddr":"162.158.92.121","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/deck/api/v1.0/boards/6/stacks/18/cards/144?","message":"session_start(): A session had already been started - ignoring at /snap/nextcloud/21796/htdocs/lib/private/Session/Internal.php#209","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.12.1","version":"19.0.0.12"}`

**To Reproduce**
unknown

**Expected behavior**
no such error expected

**Screenshots**

**Versions**
 - Nextcloud: 19snap
 - Nextcloud Deck: 1 0 4
 - Nextcloud Android:  latest
 - Nextcloud Android Deck: 1 7 0

**Smartphone (please complete the following information):**
- Device:  op5T
- Android-Version: 10 
- App-Store:
  -  Google Play Store
  - [ x] F-Droid

**Comment by pilsnerbeer** [comment]
Edit: the logs start coming as soon as the Android app is opened. "Synchronization has failed" can be seen briefly but it quickly disappears.

![Screenshot_2](https://user-images.githubusercontent.com/36133540/87320177-e33dd500-c52a-11ea-8cb2-4ef8bb5c9758.png)

**Comment by desperateCoder** [comment]
Hi @pilsnerbeer, thanks for your report!
I think we are the wrong project for this issue, i'd like to point you here: https://github.com/nextcloud/deck/issues 
This is a PHP internal thingy, we don't have any chance to affect this behavior by changing our requests or stuff, this is an internal server-app topic.

@juliushaertl will know, what to do with this (most likely not start a started session :grin:)

**Comment by pilsnerbeer** [comment]
I see , sorry about that !

**Comment by juliushaertl** [comment]
Doesn't seem deck related as well, so something from https://github.com/nextcloud/server/

**Comment by desperateCoder** [comment]
No problem, buddy! 
I'd like to add: regarding the sync issues: feel free to open a new issue and provide a stacktrace or something, I don't think the sync issues are related to the logged errors.

**Comment by desperateCoder** [comment]
Is this a fastest-response-time-battle @juliushaertl ?! 🤔

**Comment by stefan-niedermann** [comment]
![grafik](https://user-images.githubusercontent.com/4741199/87321503-99ee8500-c52c-11ea-8670-90c0158c4c52.png)
