### ISSUE TITLE
Not working on OnePlus 3T

### ISSUE THREAD

**Issue by timkrief** [stefan-niedermann/nextcloud-deck#6]
Hi, thank you for making an android app for the deck app, we really need it :+1: .

I build the app using android studio and I ran it on my phone, a OnePlus 3T.
A popup asked me to connect to my nextcloud instance, which I did, and then, nothing happened. I have a Deck on my cloud and it is not showing up here.

I'm using the deck app version 0.4.1 on my nextcloud instance version 13.0.6.

If you need more details, feel free to ask. :smiley:

**Comment by stefan-niedermann** [comment]
Hi @timkrief,

thank you for the information :) Please note that this app is **Pre-Alpha**-status and not productive usable (Most of the displayed data are mocks).

Have you installed the [Nextcloud Files](https://play.google.com/store/apps/details?id=com.nextcloud.client) app on your phone? You need to have it installed and configured. There will be a note and a redirection in the future.

**Comment by timkrief** [comment]
Hi @stefan-niedermann . Of course, I know it's pre-alpha, and I am not expecting to use it just now, it's totally okay :rofl: , I installed it to test it and give you feedback :wink: .

Yes the nextcloud files app version 3.3.2 have been installed from f-droid, and it is configured.

**Comment by desperateCoder** [comment]
Hi @timkrief,
close the app (stop process) and reopen it. Then you should see some mock-stacks and cards, and your real boards in the sidebar. Loading data right after the login  isn't implemented yet, bit no worries, we will add that.

**Comment by timkrief** [comment]
Hi, @desperateCoder (nice pseudo 😉) I followed what you said and nothing changed. Is this possibly because I'm not using Nextcloud 14? I might try to debug later.

**Comment by stefan-niedermann** [comment]
No, the server version does not make a difference. I am not sure if all the changes we need have been released in the Files app. Are you able to test with the current master of the Files app?

(Yes i know, currently a bit triggy, but until we are done with the first version of this app, the Files app will have shipped the SingleSignOn-Feature for sure)

**Comment by stefan-niedermann** [comment]
Okay, all changes we need to run this app are published in the latest version of the files app. Can you please retry the current released files app version and the master branch of this app again? :) Would be happy to hear if the problems still occur.

**Comment by timkrief** [comment]
By Files app you mean the Nextcloud main app for android, right? I have the lastest version 3.3.2. I tried to clean install this deck app again and it is still not displaying any deck.

**Comment by desperateCoder** [comment]
@timkrief thanks :D
Yes, he is talking about the main NC app.
Actually it should work, so so am sorry to ask the dumb questions: do you have any boards created in the web-app? Maybe updating to the current master of the Android deck app could do the trick too, since we are still alpha and can't tell if your version was broken... We changed quite a lot yesterday and today. Just give it a try. If the problem still consists, some logs would be quite nicely to have, since we are currently logging calls for debug purpose.

**Comment by juliushaertl** [comment]
@timkrief You will need the verson 0.5.0 of the deck app, which is scheduled this week for a final release. Feel free to give the latest prerelease a try in the meantime: https://github.com/nextcloud/deck/releases/tag/v0.5.0-rc1

**Comment by timkrief** [comment]
@desperateCoder ^^ Yes I do have boards created in the web app. I'll try and update my master of the android deck app.
@juliushaertl Thank you for this information. I'll wait for the update. I'm using version 0.4.1 right now

**Comment by timkrief** [comment]
**Update:**
I now have the version 5.0 of the deck app on nextcloud. I built the last version of this android app and ran it. I got the prompt and I was able to setup my account as expected but nothing was displayed after that. When I tried to launch the app again it closes immediately. 
I have to go in the settings and force the app to stop to be able to use it. Finally, the sample deck is then displayed, but none of my decks are. I hope this report can help you :wink:

**Comment by stefan-niedermann** [comment]
Just to make sure: did you use the very latest master branch of this repository?

> Finally, the sample deck is then displayed, but none of my decks are

This used to be the behaviour some commits ago, but in the meantime this demo-code has been replaced by real server calls which should display your real (and only your real) boards.

Which title do the demo boards and cards have?

**Comment by AndyScherzinger** [comment]
Hi @timkrief are you still experiencing this with the latest `master` and with the latest Nextcloud Android Files client v3.4.0?

If so please re-open the issue. :)
