### ISSUE TITLE
Clone lists and cards when cloning boards

### ISSUE THREAD

**Issue by skeal** [stefan-niedermann/nextcloud-deck#608]
hello,

it would be great to have the possibility to clone also the cards in the lists when cloning the board.

As we do monthly checks for our cars in the fire brigade we have the same tasks repeating any month.
i would cover the parts of the cars in cards like "car", "equipment" etc with md-based checklists as description.

Like this we could have templates for all cars that can be cloned at the beginning of each month. Or perhaps in an automated way automatically - as a next step :)

**Comment by stefan-niedermann** [comment]
So, lists are already cloned, and i implemented the UI part for also cloning the cards.

@desperateCoder please see branch `608-clone-cards-when-cloning-boards`, i left you a `TODO` in `SyncManager#cloneBoard` to respect the `boolean` flag `cloneCards`.

**Comment by desperateCoder** [comment]
@skeal Thanks for your patience! I worked on this feature these days and have to admit, that it wasn't nearly as easy as i expected. I had several issues with concurrency and stuff, but I now finally have a kind-of "does what it should do" version:

APK download: [вєωαяє, ι αм ƒαη¢у!](https://github.com/stefan-niedermann/nextcloud-deck/suites/1178100139/artifacts/17219730)

As always: this is a Dev-version and safe to install besides your actual installation of the Deck app. Even if not anything might work perfectly yet, I can confirm it didn't "break" anything for me (no data loss or something).

Would you mind testing it, if everything works as expected?

I also had a hard time figuring out what actually happens with the assigned users. The app does everything right if you ask me, I saw all the calls, but somehow in my tests there were cases where a user was assigned to a card with originally no assignees... Would be very interesting, if this also happens to you.

Quick information what you get in this feature:
- (obviously) also clone all the cards of the original board into their original stack/list
- labels are also copied  for the board
- assigned labels will also be assigned
- if you had shares on the original board, they are also copied without asking (your collegues might get push notifications that you shared the newly created board with them)
- any due dates for cards are also copied unmodified
- if you have internet connection, the changes will instantly synced to the server, after the local copy is done (incremental, no full sync to make it as fast as possible)

Would be great if you can tell us if this works for you like that and if you encounter any issues, especially regarding assigned users, thanks in advance!

CC: @stefan-niedermann

**Comment by desperateCoder** [comment]
Ping @skeal :see_no_evil:

**Comment by skeal** [comment]
Sorry for not having answered yet. I tried it and it looked really good ... Until restart of your Deck Dev version. It then duplicated the copied cards again (Before: Fahrzeugcheck, Materialcheck; After: Fahrzeugcheck, Fahrzeugcheck, Materialcheck, Materialcheck)

This also is shown then in the browser version of deck in nextcloud.

So the board itself is copied once with cards and then the cards are duplicated again.

**Comment by desperateCoder** [comment]
@skeal no worries, thanks for the reply!

Aaaw snap. I thought I had fixed that... On the other hand: the app is trying to make sure, the trucks are double-checked, **its a feature**! :smile: Just kidding, I'll see, if I can reproduce it or what else is wrong. Thanks for the feedback so far!

Your board has two lists, right? My first guess would be, that it is synced once per list...

**Comment by skeal** [comment]
Yes there are the lists "Zu erledigen" and "Erledigt" currently for testing. The board also has two cards in "Zu erledigen". "Erledigt" is empty currently.

**Comment by desperateCoder** [comment]
@skeal Ok, so I investigated this a little more and couln't find any issues. I'd suspect a server-hickup or something. If you encounter any further issues, please report! This feature will be shipped with version 1.10.0. Enjoy (in case it works :sweat_smile:)
