### ISSUE TITLE
Tags visible on unassigned cards

### ISSUE THREAD

**Issue by user655362020** [stefan-niedermann/nextcloud-deck#616]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

Tags are not visible for cards that are not assigned to a user in the lists view (Compact mode was off). 

**Describe the solution you'd like**

An option to make tags visible for unassigned cards.

**Comment by stefan-niedermann** [comment]
I don't understand what you mean? Here is a card which is not assigned to anyone and has a tag. The tag is shown:

![Screenshot_20200721-185044_Nextcloud_Deck](https://user-images.githubusercontent.com/4741199/88083364-3e06aa80-cb83-11ea-9884-9987c496816c.png)

**Comment by user655362020** [comment]
It is not visible on my end. Maybe I should reinstall. Is it safe to do so ? (Provided I sync before)
![Screenshot_20200721-223518](https://user-images.githubusercontent.com/66375825/88085062-db0e1700-cb74-11ea-9be7-2b18f370df6d.jpg)
![Screenshot_20200721-223525](https://user-images.githubusercontent.com/66375825/88085078-e4977f00-cb74-11ea-83ad-588c21505c52.jpg)

**Comment by stefan-niedermann** [comment]
Yes, given you synced, it is safe. But a @desperateCoder just told me he noticed the sane issue, so i guess it's a bug. I'll have a look.

**Comment by desperateCoder** [comment]
@user655362020 it would be safe, but I just had the same behavior, I guess you found here something... I doubt, this would bring your labels back. The good news is: this seems to be just a display bug, your data is fine.

**Comment by stefan-niedermann** [comment]
@user655362020 could you please tell us the exact version of the android app (you can find this information in the sidebar -> About) and which flavor you are using (Google Play Store or F-Droid or self-built)?

**Comment by user655362020** [comment]
Fdroid 1.8.2

I tried reinstalling. It is not visible. The tag is visible when card is assigned though. Are there any logs or config that I can provide ? (Have root access)

**Comment by stefan-niedermann** [comment]
No, no, the version info was well enough (i guess you meant `1.8.2`?) Thanks so far. I will have a look, shouldn't be that hard to find that nasty little bug 😉

**Comment by user655362020** [comment]
Yes 1.8.2

**Comment by stefan-niedermann** [comment]
Yup. Need to add check the labels here: https://github.com/stefan-niedermann/nextcloud-deck/blob/master/app/src/main/java/it/niedermann/nextcloud/deck/ui/card/CardAdapter.java#L117

@desperateCoder could you please fix? I am currently busy.

**Comment by stefan-niedermann** [comment]
Fix will be shipped in `1.9.0`.

**Comment by desperateCoder** [comment]
Oops? I was just about to fix it seconds ago. Sorry, only just read your comment...
