### ISSUE TITLE
Deck won't recognize Server App on 2nd Nextcloud

### ISSUE THREAD

**Issue by devz3r0** [stefan-niedermann/nextcloud-deck#621]
**To reproduce**
Issue is reproducible with an account from [try.nextcloud.com](https://try.nextcloud.com):
- [x] Yes
- [ ] No

1. Add Accounts from all nextcloud servers in nextcloud app
2. Add first Account from first server
3. Add Account from second server
4. See error unable to determine deck server
```
App Version: 1.8.3
App Version Code: 1008003
App Flavor: play

Deck Server Version: 0.6.4

Files App Version Code: 30120190
```
---

OS Version: 4.14.117-perf+(2005192100)
OS API Level: 29

**Expected behavior**
working account, as it is working, when you add it on a another device with only the second account on that second server

**Screenshots**

**Versions** Both Servers:
 - Nextcloud: 18.0.6
 - Nextcloud Deck: 1.0.5
 - Nextcloud Android: 3.12.1
 - Nextcloud Android Deck: 1.8.3

**Smartphone (please complete the following information):**
- Device: Oneplus 7, Samsung Galaxy S8
- Android-Version:  9, 10
- App-Store:
  - [x] Google Play Store
  - [ ] F-Droid

**Stacktrace**

```
OS Version: 4.14.117-perf+(2005192100)
OS API Level: 29
Device: OnePlus7TPro
Manufacturer: OnePlus
Model (and Product): HD1913 (OnePlus7TPro_EEA)

---

it.niedermann.nextcloud.deck.exceptions.DeckException: deck node is missing in capabilities endpoint!
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseCapabilities(JsonToEntityParser.java:403)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseJsonObject(JsonToEntityParser.java:54)
	at it.niedermann.nextcloud.deck.api.NextcloudDeserializer.deserialize(NextcloudDeserializer.java:30)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:101)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:86)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

**Comment by desperateCoder** [comment]
Your server deck version seems to be quite outdated, please try  upgrading it. There is a missing node in a special endpoint we need

**Comment by stefan-niedermann** [comment]
No @desperateCoder , he said he has installed `1.0.5` of the deck server app. `0.6.4` is the default value.

@devz3r0 please create a test account at your instance which is **not** working and send the credentials to info@niedermann.it, so we can analyze the issue

**Comment by devz3r0** [comment]
So, using 2 seperate Nextcloud instances on the same time is working for you?

**Comment by desperateCoder** [comment]
Uhm... The app is supposed to to do so. 
I'd suggest trying what @stefan-niedermann said

**Comment by stefan-niedermann** [comment]
> So, using 2 seperate Nextcloud instances on the same time is working for you?

Yes of course :) It's either a bug that it doesn't work in your scenaruo (which we'd like to fix) or it's some weird setup of your instance (in this case i'd like to find out which, so we can better handle it).

So yeah, gimme a test account 😆

**Comment by devz3r0** [comment]
As the other one is a corporate instance, I am not permitted to create accounts for external users, but I have access to some more NC instances and can check what is happening if i mix with them.

**Comment by desperateCoder** [comment]
If you need even more, we each got an instance as well. So just ask

**Comment by stefan-niedermann** [comment]
That's a pitty but totally understandable.

I can offer you another test account (just need an eMail adress to send the credentials) to check whether this is related to the instance itself or to the multi-account setup of the android app.

If you want to give the administrator technical hints, then you can tell him that the `capabilities` endpoint does not contain any information about the Deck app and the android app therefore cannot connect. Usually there should be information like the currently installed server app version available.

**Comment by desperateCoder** [comment]
@juliushaertl could you tell us, under which conditions the `deck` node int the `capabilities` endpoint is available? Is there anything we can check?

**Comment by juliushaertl** [comment]
@desperateCoder Are you issuing the capabilities request anonymously or logged in as a user? If the first is the case, it might be that the admin has limited the deck app to certain groups, which means that it is not loaded for anonymous requests and therefore not showing up.

**Comment by stefan-niedermann** [comment]
Actually each request is performed authenticated (thanks to SSO thr main Nextcloud android app is doing the actual network request and it **should** always be authenticated).

We are never doing unauthenticated requests.

A authenticated user will always see the deck node in the `capabilities`, no matter whether or not the app is limited to a group where the user is member or not?

**Comment by juliushaertl** [comment]
No, if the app is only enabled for specific groups it is not loaded on the server for other users and therefore the deck app capabilites code is never executed for those users.

**Comment by juliushaertl** [comment]
@devz3r0 Please try running the following request against your non working server:

```
curl --request GET \           
  --url 'https://yournextclouddomain.com/ocs/v2.php/cloud/capabilities?format=json' \
  -u username:password -v \
  --header 'content-type: application/json' \
  --header 'ocs-apirequest: true'
```

**Comment by devz3r0** [comment]
Hi,

I did that, piped it trough jq, and removed the domain name:

```
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 200,
      "message": "OK"
    },
    "data": {
      "version": {
        "major": 18,
        "minor": 0,
        "micro": 7,
        "string": "18.0.7",
        "edition": "",
        "extendedSupport": false
      },
      "capabilities": {
        "core": {
          "pollinterval": 60,
          "webdav-root": "remote.php/webdav"
        },
        "bruteforce": {
          "delay": 0
        },
        "files": {
          "bigfilechunking": true,
          "blacklisted_files": [
            ".htaccess"
          ],
          "directEditing": {
            "url": "https://DOMAIN/ocs/v2.php/apps/files/api/v1/directEditing",
            "etag": "ee0876b2186ee85ea7e85723ff6de5b6"
          },
          "versioning": true,
          "undelete": true
        },
        "activity": {
          "apiv2": [
            "filters",
            "filters-api",
            "previews",
            "rich-strings"
          ]
        },
        "ocm": {
          "enabled": true,
          "apiVersion": "1.0-proposal1",
          "endPoint": "https://DOMAIN/index.php/ocm",
          "resourceTypes": [
            {
              "name": "file",
              "shareTypes": [
                "user",
                "group"
              ],
              "protocols": {
                "webdav": "/public.php/webdav/"
              }
            }
          ]
        },
        "deck": {
          "version": "1.0.5"
        },
        "dav": {
          "chunking": "1.0"
        },
        "files_sharing": {
          "api_enabled": true,
          "public": {
            "enabled": true,
            "password": {
              "enforced": true,
              "askForOptionalPassword": false
            },
            "expire_date": {
              "enabled": true,
              "days": "7",
              "enforced": false
            },
            "multiple_links": true,
            "expire_date_internal": {
              "enabled": true,
              "days": "7",
              "enforced": false
            },
            "send_mail": false,
            "upload": true,
            "upload_files_drop": true
          },
          "resharing": false,
          "user": {
            "send_mail": false,
            "expire_date": {
              "enabled": true
            }
          },
          "group_sharing": true,
          "group": {
            "enabled": true,
            "expire_date": {
              "enabled": true
            }
          },
          "default_permissions": 15,
          "federation": {
            "outgoing": false,
            "incoming": false,
            "expire_date": {
              "enabled": true
            }
          },
          "sharee": {
            "query_lookup_default": false
          },
          "sharebymail": {
            "enabled": true,
            "upload_files_drop": {
              "enabled": true
            },
            "password": {
              "enabled": true
            },
            "expire_date": {
              "enabled": true
            }
          }
        },
        "notifications": {
          "ocs-endpoints": [
            "list",
            "get",
            "delete",
            "delete-all",
            "icons",
            "rich-strings",
            "action-web"
          ],
          "push": [
            "devices",
            "object-data",
            "delete"
          ],
          "admin-notifications": [
            "ocs",
            "cli"
          ]
        },
        "password_policy": {
          "minLength": 8,
          "enforceNonCommonPassword": true,
          "enforceNumericCharacters": false,
          "enforceSpecialCharacters": false,
          "enforceUpperLowerCase": false,
          "api": {
            "generate": "https://DOMAIN/ocs/v2.php/apps/password_policy/api/v1/generate",
            "validate": "https://DOMAIN/ocs/v2.php/apps/password_policy/api/v1/validate"
          }
        },
        "theming": {
          "name": "Share@DOMAIN",
          "url": "https://share.kapschsc.at",
          "slogan": "",
          "color": "#F2EAC2",
          "color-text": "#000000",
          "color-element": "#aaaaaa",
          "logo": "https://DOMAIN/index.php/apps/theming/image/logo?useSvg=1&v=7",
          "background": "#F2EAC2",
          "background-plain": true,
          "background-default": true,
          "logoheader": "https://DOMAIN/index.php/apps/theming/image/logo?useSvg=1&v=7",
          "favicon": "https://DOMAIN/index.php/apps/theming/image/logo?useSvg=1&v=7"
        }
      }
    }
  }
}
```

**Comment by desperateCoder** [comment]
oooook. what the actual hell... all we need is actually there...

uhm, sounds dumb, but maybe delete the app data of the deck app and try adding the non-working account first? There is no reason, why this server souldn't work tbh...

**Comment by devz3r0** [comment]
I already mentioned that if I only use this instance alone, it works.

**Comment by stefan-niedermann** [comment]
> If the result is not as above, it would not work at all, correct?

Correct

**Comment by devz3r0** [comment]
As I read again over your authorisation part, I checked the nextcloud app itself, and it got deauthorized, on the second instance.
So i could see the file list for a short time, but got kicked out to the login screen.
After i reauthorized it, it started to work.
So it would help if you add a hint to recheck the nextcloud app on the issuing account.

**Comment by desperateCoder** [comment]
We'll, nice research @devz3r0! Thanks for sharing! 

@stefan-niedermann is that a new `hint`?

**Comment by stefan-niedermann** [comment]
Thank you @devz3r0 for the update! I added a hint in this case, so other users will get notified that the account might no longer be authorized.
