### ISSUE TITLE
🔍 Search

### ISSUE THREAD

**Issue by silmaril42** [stefan-niedermann/nextcloud-deck#630]
I am missing a possibility to enter some text and see a filtered list of only the cards containing the entered text, similar to the magnifying glass in the web app.

This is a very helpful feature if you are working with long lists of cards.

This might be implemented as an additional tab in the current filter dialog, but there might be better ways to implement this in a user friendly way.

In the web app the search takes titles and descriptions into account. If this is implemented in the filter dialogue, there is so much empty space that we might just as well add the possibility to select, which fields should be searched.

**Comment by stefan-niedermann** [comment]
Yep, will definitely come at some point. My idea was to have a similar UI like the Notes app has (and the future Nextcloud app will have).

When searching, i think we will hide the tab/column layout and only provide a list of the results, because this will provide a better overview. The concept of a search is different from the filter use case.

Let's ser what we will end up with. 🙂

**Comment by silmaril42** [comment]
I agree that search is different from filter - so ideally we would have both :smile:

A text filter should behave just like the current filter, only with full text matching.

The search function should list all results. Getting the tab/column layout out of the way would probably be a good idea in this case. Maybe we could also have an option to limit the results to the current list or search all cards in all lists.

**Comment by stefan-niedermann** [comment]
Step by step, we have limited free time 😉. We should start with a global search and can add filters later.

**Comment by neerro** [comment]
Have you any understanding about the date when the feature will be implemented?

**Comment by stefan-niedermann** [comment]
I will comment here if i have any news. Please *only* use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Asking will not make me have more free time but limit the time i can work on the Deck app. Contributions are welcome of course.

**Comment by stefan-niedermann** [comment]
Will be shipped in version `1.15.8`

**Comment by neerro** [comment]
> 
> 
> Will be shipped in version `1.15.8`

Perfect! I'm already downloaded and it works good. Thanks))
