### ISSUE TITLE
User profile photo not shown

### ISSUE THREAD

**Issue by Aspire1Inspire2** [stefan-niedermann/nextcloud-deck#632]
Hi, I have users in my nextcloud server with their profile photos configured. And my nextcloud Android client is showing their profile photos correctly. However, the deck and notes apps are not showing the profile photos at all.
Is there anything I can do to help you figure out where the issue is coming from?

**Comment by stefan-niedermann** [comment]
Hi @Aspire1Inspire2, first of all please fill out [the issue template](https://github.com/stefan-niedermann/nextcloud-deck/issues/new?labels=bug&template=bug_report.md), it is there [for a reason](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed) :slightly_smiling_face:.

**Comment by stefan-niedermann** [comment]
[Read why this issue has been closed](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed). Please feel free to open a new issue filling in the complete issue template.
