### ISSUE TITLE
List widget blacked out in dark theme

### ISSUE THREAD

**Issue by shgysk8zer0** [stefan-niedermann/nextcloud-deck#636]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

List widget completely blacked out in dark mode

**To reproduce**
Issue is reproducible with an account from [try.nextcloud.com](https://try.nextcloud.com):
- [x] Yes
- [ ] No

1. Add list widget to home screen
2. Enable dark theme if not already enabled

**Expected behavior**

Dark background with black boxes that I assume contain text

**Screenshots**

![Screenshot_20200731-213625.png](https://user-images.githubusercontent.com/1627459/89094297-4a56e880-d377-11ea-9631-8846d688a58f.png)

**Versions**
 - Nextcloud: 19.1
 - Nextcloud Deck: 
 - Nextcloud Android: 3.13.0 RC2
 - Nextcloud Android Deck: 1.9.4 (also previous version)

**Smartphone (please complete the following information):**
- Device: Pixel 2XL
- Android-Version: 10
- App-Store:
  - [ ] Google Play Store
  - [x] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Are you using LDAP?**
- [ ] Yes
- [x] No

**Stacktrace**
NA

**Comment by stefan-niedermann** [comment]
Thank you for the report @shgysk8zer0 and thank you for the fix @dan0xii !

Fix will be shipped with version `1.9.5`.
