### ISSUE TITLE
Add Push Up Notification

### ISSUE THREAD

**Issue by JohannesStroebel** [stefan-niedermann/nextcloud-deck#642]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**
 Adding a time or date to a card is useless, if you don't look into the app everyday. Therefore a notification would be good.

**Describe the solution you'd like**

If I add a date or time as e.g. a timeline, when it should  be done, to a card, then I should also get a push notification, before the time is reached or at least, at the moment the time and date is reached.

**Describe alternatives you've considered**

**Additional context**

**Comment by desperateCoder** [comment]
Hi @JohannesStroebel, thanks for your report!

I'm not sure, but I get notifications... But not in our app, but in the nextcloud files app.. have you disabled the notifications there? @stefan-niedermann is there a need to install or activate some Server-Side app or setting for this?

**Comment by stefan-niedermann** [comment]
Nah, @desperateCoder this issue is about getting notifications for a near **due date**. It's a request for a specific, new notification type.

Basically Push Notifications are already working (e. g. when someone assigns you or mentiones you in a comment).

Those notifications are sent from the Deck Server app, so you should reopen the issue there @JohannesStroebel 

I think the closest existing issue is this (https://github.com/nextcloud/deck/issues/1549) where i already mentioned that a push notification should be sent.

Personally i think, a Push Notification for the due date itself is useless, because when you get the notification, it would already be due. So i suggest to vote up the linked issue if you agree. Otherwise you should just open a new issue (in the linked repository).

Hope i could clearify things 🙂 

Regards

**Comment by stefan-niedermann** [comment]
Also please see [this issue](https://github.com/stefan-niedermann/nextcloud-deck/issues/160) from our repository. The server app plans a calendar integration, so you should get due date notifications as soon as this has been implemented from your calendar once this has been implemented (though i don't know the current state of this plan as it also has to be done by the server app)

**Comment by desperateCoder** [comment]
> or at least, at the moment the time and date is reached. 


![Screenshot_20200804-133043](https://user-images.githubusercontent.com/6911132/89289102-fbe76980-d656-11ea-9ef9-086f51ea34ea.jpg)

**Comment by JohannesStroebel** [comment]
> Hi @JohannesStroebel, thanks for your report!
> 
> I'm not sure, but I get notifications... But not in our app, but in the nextcloud files app.. have you disabled the notifications there?

No, Notifications are all allowed. The nextcloud files app doesn't have any deck related notifications. I do also get notifications in the files app, but only about e.g. autouploads, errors etc. which aren't related to the deck app.

**Comment by JohannesStroebel** [comment]
> > or at least, at the moment the time and date is reached. 
> 
> 
> ![Screenshot_20200804-133043](https://user-images.githubusercontent.com/6911132/89289102-fbe76980-d656-11ea-9ef9-086f51ea34ea.jpg)
> 

Genau das hier fehlt mir. Das ist über die Deck App?

**Comment by desperateCoder** [comment]
Ja nee, eben nicht... Der Spaß kommt bei mir immer via Files App... 

![Screenshot_20200804-134502](https://user-images.githubusercontent.com/6911132/89290181-bfb50880-d658-11ea-9c02-841579ef093c.jpg)


Weiß nicht Mal so richtig wie ich mich dagegen wehren kann, wenn @stefan-niedermann Mal wieder due-date testet... Daher auch die Frage an ihn.

Hinweis an der Stelle: das kommt nur auf die Minute genau, sobald die Zeit erreicht ist, nicht vorher.

**Comment by stefan-niedermann** [comment]
Nein, über die Files App - Alle Push Notifications kommen über die Files App rein. Mach mal bitte nen Screenshot von deinen Benachrichtigungseinstellungen im Web UI?

**Comment by stefan-niedermann** [comment]
Im Web UI oben rechts auf deinen Avatar, dann links auf "Aktuvutäten".

Sollte ungefähr so aussehen:

![Screenshot_20200804-134705_Firefox_Preview](https://user-images.githubusercontent.com/4741199/89290318-ff7bf000-d658-11ea-8a77-d2f0cb0a38af.png)

**Comment by stefan-niedermann** [comment]
Doe Push Benachrichtigungen kommen zwar technisch über die Files App rein (sollten zumindest 😉 ), bei einem Klick darauf öffnet sich aber Deck (sofern du von Files App und Deck App aktuelle Versionen hast, ist noch relativ neu)

**Comment by JohannesStroebel** [comment]
> Doe Push Benachrichtigungen kommen zwar technisch über die Files App rein (sollten zumindest 😉 ), bei einem Klick darauf öffnet sich aber Deck (sofern du von Files App und Deck App aktuelle Versionen hast, ist noch relativ neu)

Ah habe ich bei mir aus, da mir die Auto-Upload Benachrichtigungen auf den Geist gehen

**Comment by stefan-niedermann** [comment]
Verstehe, dann ist das das Problem. Könntest du sie testweise mal einknipsen?

Ggfls wäre dann ein Issue in der Files App zu öffnen, dass die Notifications über unterschiedliche Kanäle getrennt ein- und ausschaltbar sind.

**Comment by JohannesStroebel** [comment]
> Verstehe, dann ist das das Problem. Könntest du sie testweise mal einknipsen?
> 
> Ggfls wäre dann ein Issue in der Files App zu öffnen, dass die Notifications über unterschiedliche Kanäle getrennt ein- und ausschaltbar sind.

Mir fällt gerade auf, dass ich tatsächlich nur die Hochlade-Benachrichtgung ausgeschalten hatte. Das von dir vorgeschlagene Features gibt es somit schon und die Benachrichtigungen sollten mir eigentlich angezeigt werden.

**Comment by desperateCoder** [comment]
Vllt in Android? Also app-settings? Oder halt in der Files App selbst, was anderes würde mir auf die schnelle nicht einfallen...

**Comment by stefan-niedermann** [comment]
Welche Versionen exakt von der Files und der Deck App verwendest du?

**Comment by JohannesStroebel** [comment]
> Welche Versionen exakt von der Files und der Deck App verwendest du?

Deck: 1.9.3.

Files (Dev): 20200730

**Comment by stefan-niedermann** [comment]
Verrückt. Und du erhälst keinerlei Push-Notifications über die Files App? Hast du mal im Web UI überall ein Häkchen gesetzt und versucht, dir selbst eine Datei zu teilen oder so?

Und nur um sicher zu gehen: Hat dein Gerät Google Play Services?

Alles was die Deck Android App tut ist, den Klick auf eine Benachrichtigung abzufangen und in der Deck-App zu öffnen (sofern die Benachrichtigung von der Deck-Server-App kam). Wir setzen also ziemlich spät ein.

Du scheinst eher ein allgemeines Problem mit den Nextcloud Push-Notifications zu haben, wenn diese dir gar nicht erst angezeigt werden.
