### ISSUE TITLE
public links to boards

### ISSUE THREAD

**Issue by dberardo** [stefan-niedermann/nextcloud-deck#650]
it would be amazing if boards could be shared both in read only and edit node via a public link to anonymous users.

optionally those users could add temporary names and use them to comment or sign cards to themselves, etc.

**Comment by stefan-niedermann** [comment]
Yup. This has to be implemented by the server app first though.

The Android app will follow once this feature is available, of course 😉 

See https://github.com/nextcloud/deck/issues/14
