### ISSUE TITLE
List widget: List not loaded

### ISSUE THREAD

**Issue by splashote** [stefan-niedermann/nextcloud-deck#656]
After selecting a list to be shown in the widget, the entries don't appear.

The widget shows the right colored circle, and the name of the list, nothing else.

Deck Android App version 1.9.7
Deck version on server: 1.0.5
Nextcloud version on server 18.0.7

**Comment by splashote** [comment]
Will add further information based on template later, lousy internet connection on the train...

**Comment by splashote** [comment]
now it loaded.

no idea why.

**Comment by stefan-niedermann** [comment]
Well, main thing it works. Might be everything (for example a slow database connection which had to be initialized first).

Let us know if this happens more often!

Cheers
