### ISSUE TITLE
Shortcuts for create operation

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#66]
Sample implementation in Nextcloud Notes: https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/AndroidManifest.xml#L26-L28

![Shortcuts](https://images.techhive.com/images/article/2016/11/android-71-app-shortcuts-100693489-large.jpg)

**Comment by stefan-niedermann** [comment]
While implementing this i saw some problems design-wise: We could simply use the latest board and latest stack, but maybe some kind of dialog to choose the destination of the created card would be more useful.

cc @jancborchardt @juliushaertl @AndyScherzinger

**Comment by jancborchardt** [comment]
In the view that opens where you fill out the card, it could simply have a header with board color, board name and stack name? Then you can tap on the header to change it. And that way there’s not an intermediary step but just an element of the normal flow.

**Comment by stefan-niedermann** [comment]
You mean the choose board/stack dropdowns should **always* be present when editing/creating a card or only when using the shortcut?

I think it might clutter the UI for the "normal" creation/edit workflow from within the app and would only display it when using the shortcut.

**Comment by jancborchardt** [comment]
Yes, exactly, they are only relevant when using that shortcut. :)
