### ISSUE TITLE
Allow archiving cards from filtered results only 

### ISSUE THREAD

**Issue by aproposnix** [stefan-niedermann/nextcloud-deck#663]
**Describe the solution you'd like**
I would like to be able to filter my cards based on tags and to archive only the cards in that filtered view. 

1. User applies filter for Tag X 
2. User Sees filtered Results with only cards containing the tag 'X'. 
3. User selects "Archive Cards" from the menu 
4. All cards with the tag 'X' in that column are archived
5. user removes filter
6. All cards without the tag 'X' are still visible in the column 

**Describe alternatives you've considered**
I would have to manually archive each individual card

**Additional context**

I use the archiving feature quite a bit. I find it useful esp., for sleeping backlog items as well as finished items. This would just make the management of cards a little easier.

**Comment by stefan-niedermann** [comment]
> archiving all cards in all stacks - would be a little bit more complicated, but also not that ha

No, this action is always in the context of the current list. It should never archive cards from other lists.

When we "Archive cards", we know in the UI the current `Filterinformation`. We should pass it down to the archive method of the `SyncManager` - no need to iterate the visible cards.

@desperateCoder you can already prepare the called method (just copy it and add the`Filterinformation` to the arguments list). I will then adjust the UI.

**Comment by desperateCoder** [comment]
@stefan-niedermann To get this straight: you'll give me `FilterInformation` and a `stackId`, and I am supposed to delete alle filter results for the specified stack, not all matches of the 'FilterInformation', right? 

Thumb up for "thats right", otherwise correct me.

**Comment by stefan-niedermann** [comment]
Yes, except one detail:

> delete alle filter results

Not `delete` but `archive`.

**Comment by stefan-niedermann** [comment]
@desperateCoder see `SyncManager#archiveCardsInStack` - it now gets the `FilterInformation` object. Do something with it :)

**Comment by stefan-niedermann** [comment]
Fixed & will be shipped with `1.11.0`.

Only the visible cards of the list will be archived now (If you have an active filter, only those cards which are left will get archived instead of *all*).

**Comment by aproposnix** [comment]
@stefan-niedermann I was offered an updated version on play today (it says version 1.10 but it's from the beta channel). After installing it, the filtering is broken as I am not able to select them from the list. I'm not sure if it's caused by this ticket or not.

**Comment by desperateCoder** [comment]
@aproposnix sorry if that's a dumb question, but as I was testing the feature it took me a few seconds to realize, that the labels aren't clickable, I needed to tab on the row, but right to the label. Is that maybe your problem? @stefan-niedermann is this as-designed?

**Comment by desperateCoder** [comment]
Ok, so apparently sometimes it's the little things 😅 

> Should I create a ticket?

That'd be great, thanks!

**Comment by stefan-niedermann** [comment]
Yeah, please open a separate issue - i already noticed it (it was also the case in the last version), but with an issue it's easier to keep it in mind :)

**Comment by aproposnix** [comment]
Just one more thing... just to be clear, does the current beta from the play store have this fix applied already?

**Comment by desperateCoder** [comment]
I just looked up the commit history of the 1.10 tag and nope, sorry, tagged is tagged. But it will be shipped at 1.11, just as @stefan-niedermann promised. Maybe he's a generous guy and tag it soon 😉

**Comment by aproposnix** [comment]
> Oh wow, you already got an update?! Thought fdroid takes quite a while... man_shrugging
> 


No, I'm still on the Google Play version mostly because it want the latest ASAP :)

**Comment by desperateCoder** [comment]
@aproposnix oh, you mean the buggy ones? 🤣 

Thanks for your patience and contributions, and for not just bragging about everything, but helping to get it fixed. You deserve a damn medal for that!
