### ISSUE TITLE
Recreate database completely onUpgrade

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#67]
Since we are not downward-compatible yet, we should completely recreate the database on an app upgrade and trigger a sync.

This is a requirement for a first F-Droid beta release (#65).

**Comment by tobiasKaminsky** [comment]
Is this really needed? If you publish the app on Fdroid and an user that already manually installed the app, tries to install it via Fdroid it will fail, as the app id is the same, but the signing key is different.

**Comment by stefan-niedermann** [comment]
What does recreating the database have to do with an different app signature?

Database will change often. Every time we will publish a new version on F-Droid probably will crash. Therefore we would need to be downward compatible or - as it is more easy for now - just drop and recreate database and perform a sync?

**Comment by tobiasKaminsky** [comment]
I was just triggered by Fdroid release…

On Files app we have a DatabaseHelper that supports a callback on Database upgrade.
As you use LiveData/Room, I am sure there is something similar, which can migrate data and table structure from one db version to the next.

**Comment by stefan-niedermann** [comment]
Yes, there is. the problem is, that we would have to implement it fully and as we do not want to have this work at this time, a recreation should be enough for a alpha release - for a stable version we would maintain a proper upgrad instead of a recreation of course ;)

**Comment by tobiasKaminsky** [comment]
Ah. Ok. Then sorry for my noise ;-)
