### ISSUE TITLE
The UI isn't scrollable using a smartphone on the second time.

### ISSUE THREAD

**Issue by piiskop** [stefan-niedermann/nextcloud-deck#670]
**Describe the bug**
If I go to deck using a smartphone, I can scroll the cards for the first time but after I remove my finger, the view isn't scrollable anymore, so I can't see the cards that don't fit to the list unless I refresh the page.

**To reproduce**
Issue is reproducible with an account from [try.nextcloud.com](https://try.nextcloud.com):
- [x] Yes
- [ ] No

1. Go to 'Deck'!
2. Insert as many items to a list as the list will be longer than it fits to the screen!
3. Scroll up-down!
4. Raise the fingers!
5. Try to scroll up-down! Realize that you can't do that anymore!

**Expected behavior**
Scrolling up-down works always.

**Versions**
 - Nextcloud: 19.0.1
 - Nextcloud Deck: 1.0.5
 - Nextcloud Android: "Deck" isn't available there anyway, only files are.
 - Nextcloud Android Deck: I don't use it as it's paid and I'm only willing to use FOSS.

**Smartphone (please complete the following information):**
- Device: "Xiaomi Redmi Note 9 Pro"
- Android-Version: "10 QKQ1.191215.002"
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Are you using LDAP?**
- [ ] Yes
- [x] No

**Comment by stefan-niedermann** [comment]
Hi, this repository is only about the native Android App, not about the web app.

There is already an open issue in the correct repository, please check out this: https://github.com/nextcloud/deck/issues/1960

**Comment by stefan-niedermann** [comment]
> I don't use it as it's paid and I'm only willing to use FOSS

This app **is** **F**ree and **O**pen **S**ource **S**oftware.

You can [build it yourself](https://github.com/stefan-niedermann/nextcloud-deck) or use it from [F-Droid](https://f-droid.org/de/packages/it.niedermann.nextcloud.deck/). The Play Store version is identical and build from exact this source code. It is paid as we see it as a donation for the further development.

Seems like you confound "free" as in the definition of GNU with "free" as in "free beer".

**Comment by piiskop** [comment]
I didn't know that, just saw 2.99 euros or something.

The app seems to function well regarding to scrolling, just tried it from F-Droid.
