### ISSUE TITLE
Parse colors with alpha channel

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#674]
For reference: https://github.com/nextcloud/deck/pull/1545#discussion_r481067417

It might be *possible* to receive color with a format `#rgba` and `#rrggbbaa`. We need to make sure that our `ColorUtil` is capable of parsing a correct color in this cases (+ extend the UnitTests).

**Comment by juliushaertl** [comment]
We will just drop those for now in deck and apply the rgb values there, since both the frontend and database of deck currently only support plain colors without an alpha channel. However for the future it might make sense to already have this available in the app :wink:
