### ISSUE TITLE
show more than 7 assigned users

### ISSUE THREAD

**Issue by jakobroehrl** [stefan-niedermann/nextcloud-deck#679]
It's not possible to see more then 7 assigned users:
![Screenshot_20200904-193443](https://user-images.githubusercontent.com/24530680/92276144-bdacc680-eef0-11ea-997c-a4019060481e.jpg)

**Comment by stefan-niedermann** [comment]
Wrapping the `LinearLayout` in a `HorizontScrollView` should be a quickwin.

**Comment by stefan-niedermann** [comment]
Seems to be not that trivial. If we use an `HorizontalScrollView`, this are cannot be used anymore for swiping between the tabs.

I guess we need some kind of `GridView` therefore, like in the attachments fragment. This had also the benefit of all avatars being visible directly without scrolling.

**Comment by stefan-niedermann** [comment]
Fixed. Will be shipped with `1.10.0`.

![grafik](https://user-images.githubusercontent.com/4741199/95000323-28b8ee00-05c0-11eb-9a95-4d317ea67ecc.png)
