### ISSUE TITLE
Make strings with hyperlinks better translateable

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#68]
To make strings with links more easily translatable we should built those strings at runtime like

`text` + `&lt;href="` + `url` + `">` + `Name` + `&lt;/a>`

while the "technical" parts should be marked as not-translatable strings and the actual URLs and texts are separate strings.

Follow-up to #31 
CC: @rakekniven @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Nice idea.
I would even extract this into a static buildTranslatedLink(…) method.

**Comment by tobiasKaminsky** [comment]
Seems we did this already, so for reference:

https://github.com/nextcloud/android/blob/24c0092d742f1d9dcad0c64e787cba5af7d2f250/src/main/java/com/owncloud/android/ui/activity/ParticipateActivity.java#L71-L76

https://github.com/nextcloud/android/blob/92bbcfb973594f9f0aafa16def97d9f003dcbe54/src/main/res/values/strings.xml#L548-L550
