### ISSUE TITLE
Spelling errors in Russian

### ISSUE THREAD

**Issue by kstlv** [stefan-niedermann/nextcloud-deck#684]
The file contains spelling errors. File path: `nextcloud-deck/app/src/main/res/values-ru/strings.xml`

**Wrong strings**

```
<string name="simple_clear">Отчистить</string>
<string name="simple_comment">Коментарий</string>
```

**Right strings**

```
<string name="simple_clear">Очистить</string>
<string name="simple_comment">Комментарий</string>
```

**Comment by desperateCoder** [comment]
Hi @kstlv, 

thanks for the report! My (russian) girlfriend approved it, we'll fix that!

**Comment by stefan-niedermann** [comment]
cc @rakekniven

**Comment by stefan-niedermann** [comment]
Thank you very much @rakekniven !

@kstlv this will be fixed in the next released version.
