### ISSUE TITLE
Shard board not shown in the app.

### ISSUE THREAD

**Issue by tacruc** [stefan-niedermann/nextcloud-deck#694]
First of all thanks for the nice app.

**Describe the bug**
I have an minor issue with it. On my web interface there are two boards.
One is owned by an other user, on my app I only see my personal board.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/402891/95015242-2e5c1580-064c-11eb-9887-61b67f040f1b.png)
![grafik](https://user-images.githubusercontent.com/402891/95015536-b68eea80-064d-11eb-89e8-9a28b02ef5eb.png)

**Versions**
 - Nextcloud: 20.0.0
 - Nextcloud Deck: 1.0.5
 - Nextcloud Android: 
 - Nextcloud Android Deck: 1.9.7

**Smartphone (please complete the following information):**
- Device: Samsung A5 2017
- Android-Version: Lineage OS 17.1
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Are you using LDAP?**
- [ ] Yes
- [x] No

**Comment by stefan-niedermann** [comment]
@tacruc have you tried to perform a full sync (pull to refresh)?

And can you also try to ask your friend to create a new board and share it with you? So we can get an idea of whether this is an issue with this specific board or with the sharing itself?

**Comment by tacruc** [comment]
I removed and readded my account, now every board is there.
So I don't know what went wrong before.

**Comment by desperateCoder** [comment]
@tacruc :smile: those are my favourite bugs! Sorry for your inconveniences, i guess there has been a kind of network- or server hickup or something, that lead to a "hanging" state. If you have any more trouble with our app, open an issue any time! :smiley:

**Comment by tacruc** [comment]
Don't be sorry. I'm happy you programmed the app.

**Comment by desperateCoder** [comment]
Aaaaaw :heart: 

Having grateful users like you is unlikely motivating, pays of for all the work instantly!  Thanks, and stay tuned and safe!

**Comment by q-wertz** [comment]
I'm having the same issue...

A new board was shared with me this afternoon, but still not visible in the Deck app.
Pulling down the sidebar does not help, neither pulling down in one of the boards...

Tried to switch to other account an back, but stumbled into https://github.com/stefan-niedermann/nextcloud-deck/issues/933. Maybe they are related…?

**Comment by stefan-niedermann** [comment]
@q-wertz please see https://github.com/stefan-niedermann/nextcloud-deck/issues/930#issuecomment-818025817
