### ISSUE TITLE
Filtering: Clicking on the tag label does not select the tag

### ISSUE THREAD

**Issue by aproposnix** [stefan-niedermann/nextcloud-deck#696]
**Describe the bug**
When a user is in the tag filter, they cannot click on the tag label but they must click to the right side of the label. 
This is problematic for left handed people. 

**To reproduce**
1. Open tag filter
2. Click on the tag label (the bubble)
3. Nothing happens - it is not selected 

**Expected behavior**
Clicking on the label will select the tag

**Smartphone (please complete the following information):**
- Device: 
- Android-Version: 
- App-Store:
  - [ ] Google Play Store
  - [X] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

Mentioned in issue #663

**Comment by stefan-niedermann** [comment]
Fix will be shipped in `1.11.0`, thanks for reporting!
