### ISSUE TITLE
Exclude "Done" cards from upcoming view

### ISSUE THREAD

**Issue by varac** [stefan-niedermann/nextcloud-deck#704]
**Is your feature request related to a problem? Please describe.**

I really like the "upcoming cards" view - however when you move a card to a "Done" column they still show up in the upcoming cards view, which is counter-intuitive to what this view is meant.
This can be solved by archiving "Done" cards but with a lot of boards this task is tedious.

**Describe the solution you'd like**

Cards from lists called "Done" should be excluded from the upcoming cards view.

**Describe alternatives you've considered**

None.

**Comment by stefan-niedermann** [comment]
Thank you for your request.

This repository is *only* for the Android app. Since we don't have this kind of view, i guess you wanted to open the issue in the server apps repository, which you can find here: https://github.com/nextcloud/deck/issues/new/choose

Regards
