### ISSUE TITLE
LDAP avatars not displayed on cards. 

### ISSUE THREAD

**Issue by Mangleuz** [stefan-niedermann/nextcloud-deck#706]
LDAP avatars not displayed on cards. (Unlike in the Talk app). Instead there are gray identical avatars, demanding that one first must open the card and then click on all the gray avatars under 'assigned users', one by one, to know who is who. (Which with about 15 users makes the app close to unusable).

**Comment by stefan-niedermann** [comment]
Dear @Mangleuz, thank you for the report. Can you please check whether or not this is related to #644 (-> Is your cloud located directly at the domain like `cloud.example.com` or is it accessed via a subfolder like `example.com/my-cloud/`?

Do you have local users (non-LDAP) where it works? I am wondering because you have been very specific about LDAP.

**Comment by Mangleuz** [comment]
Thank you for the reply!

Yes, the cloud is accessed as `example.com/my-cloud/` and no, we have no local users, only LDAP ones. One can one do?

**Comment by stefan-niedermann** [comment]
@Mangleuz I am pretty sure it's the same issue as #644. Is it possible that you create temporarily a local test user and see whether or not his avatar will show up? (just login as the test user, create a private board and card and assign yourself - completely unrelated to all the other users).

**Comment by stefan-niedermann** [comment]
@Mangleuz are you also affected by #754 ?

**Comment by Mangleuz** [comment]
> 
> 
> @Mangleuz are you also affected by #754 ?

Because of the not being able to use Deck on Android (no avatars) our team stopped using it. Therefore I do not know. We would love to use it on Android though! 

Our Nextcloud instance is a bit sensitive/fragile so we did not want to create any local users outside LDAP since these users previously has turned into "ghost-users" that lingers around in the system after we have (in numerous ways) have had them removed (creating odd complexities and some confusion for team-members when using the platform). If i remember correctly i even think one of our techies blocked the function of creating local users, i can not remember clearly.

**Comment by stefan-niedermann** [comment]
Good news, we believe that we have been able to solve this issue completely. If you want, you can safely try the solution, installing the [latest `APK` directly from here](https://github.com/stefan-niedermann/nextcloud-deck/suites/1700393111/artifacts/31998649) - it will be installed parallel to your default Deck Android app.

It will be released with the next version `1.13.5`.

Please don't hesitate to open a new issue if the described problems are still present at the linked `APK` or in the released version `1.13.5` or higher! Thank you for reporting! :slightly_smiling_face:
