### ISSUE TITLE
Cannot add stack widget

### ISSUE THREAD

**Issue by heikar** [stefan-niedermann/nextcloud-deck#711]
**Describe the bug**
If i try to add the stack widget, then the app opens with a sreen with title "Add stack widget" and i can choose a user, a board and a status. When i click to "Add", the app closes and no widget is added.

**To reproduce**
1. Open widget dialog on android
2. Click on 'Nextcloud Deck' and then choose the stack widget
3. Choose a user, a board and a status and click to 'Add'
4. The app closes and no widget is added

**Versions**
 - Nextcloud: 20
 - Nextcloud Deck: 1.1.2
 - Nextcloud Android: 3.13.1
 - Nextcloud Android Deck: 1.11.1

**Comment by stefan-niedermann** [comment]
Dear @heikar please fill out the *complete* issue template. From which source have you got the App? Play Store? F-Droid? Beta channel? Huawei?
Does it work with an account from try.nextcloud.com?
The template [is there for a reason](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed), please use it.

I can not reproduce this issue. Does this happen only on a specific list or does it fail also on a list from another board? How many accounts do you have configured?

**Comment by stefan-niedermann** [comment]
[Why this issue has been closed](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed).
