### ISSUE TITLE
Option to show deadlines from cards in the calendar

### ISSUE THREAD

**Issue by ReleaseTheKnowledge** [stefan-niedermann/nextcloud-deck#712]
**Is your feature request related to a problem? Please describe.**
The deadlines from the deck cards don't show on my calendar app (which they do on Nextcloud in web browser).

**Describe the solution you'd like**
I would like an option to get the deadlines from Deck to also be visible on the calendar on my android phone.

**Describe alternatives you've considered**
I considered if this should be handled with caldav from nextcloud (which i thought it would). _But_ I think it's more important that it works through the app, because if you want to have information about Deck on the phone then you have the app (but not necessarily a caldav solution).

**Comment by stefan-niedermann** [comment]
No need to reinvent the wheel 🙂 

There is a solution to synchronize calendars which works flawlessly, as you already mentioned yourself: CalDAV. I propose to use DAVx5.

1. We are a little crew itht very limited resources, and we would never get that kind of great CalDAV support as those guys.
2. It might be confusing for users that the Deck calendars are there multiple times (one time from the Deck app, another time from DAVx5)
3. We would like to focus on improving the app with its widgets. Maintaining also a calendar integration is out of scope for this project for now.
