### ISSUE TITLE
"Upcoming" Overview, inspired by NC Deck

### ISSUE THREAD

**Issue by Torenga** [stefan-niedermann/nextcloud-deck#732]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**
I want to get an overview of cards with upcoming due dates akin to NC-Decks "Upcoming Cards" feature

**Describe the solution you'd like**
A separate entry in the pull-out list over the individual decks, with "Overdue/Current, Today, Tomorrow, This Week, Later" etc.

**Describe alternatives you've considered**
Using the web-interface on NC-Deck (Not a good interface on mobile compared to Android Deck)

**Additional context**
Inspired by NC-Deck's already implemented time overview interface.

**Comment by stefan-niedermann** [comment]
Please see here: https://github.com/stefan-niedermann/nextcloud-deck/issues/690#issuecomment-702124737

**Comment by Torenga** [comment]
> Please see here: [#690 (comment)](https://github.com/stefan-niedermann/nextcloud-deck/issues/690#issuecomment-702124737)

My bad - I tried searching for similar issues but missed this one.

**Comment by Torenga** [comment]
Duplicate of #690

**Comment by stefan-niedermann** [comment]
All good - the GitHub search isn't that good after all...
