### ISSUE TITLE
Add comments to your source strings to help translators with useful context

### ISSUE THREAD

**Issue by rakekniven** [stefan-niedermann/nextcloud-deck#733]
Hello @stefan-niedermann ,

continuing to our discussion in the community chat I kindly ask you to improve/overwork the comments for your app.

What I found out today:

Following line contains a xml comment
https://github.com/stefan-niedermann/nextcloud-deck/blob/559681f7c58380d2e4aeeabcfa03a2b8940503c9/app/src/main/res/values/strings.xml#L13

From my understanding the comment is not related with L14.
https://github.com/stefan-niedermann/nextcloud-deck/blob/559681f7c58380d2e4aeeabcfa03a2b8940503c9/app/src/main/res/values/strings.xml#L14
It is more like a section header.

Actually it results at Transifex like this:

![2020-11-18_09h55_43](https://user-images.githubusercontent.com/2069590/99507912-454c9200-2984-11eb-89ab-eb66a19faf94.png)

Goals from my view are

- [x] Remove such header sections. Does adding a blank line between help?
- [ ] Complete docs at https://github.com/nextcloud/documentation/issues/5422

Question as Android noob:
How to add comments to the strings? Directly editing strings.xml? Or editing another file?

**Comment by stefan-niedermann** [comment]
Thanks :)
You were right: Those kind of comments were section headers - i removed them all in https://github.com/stefan-niedermann/nextcloud-deck/commit/8e72fa374cf71406bcc081b046187f615a38054b

What do you expect form comments?
- A description *where* in the UI they are used?
- Information like "uppercase / lowercase" or "this sentence should not have a `.` at its end"?

I will happily add a comment to each string, but i am unsure about the expectations. Alternatively i can just keep the strings without comments and add them on demand?

**Comment by rakekniven** [comment]
You are fast as my Abarth :-)

> What do you expect form comments?

Often we have very short strings like "Move item". Translator is asking "Where do I move the entry to?" To another list? Up or down in the list?
Right now you do not need to spend time to add comments. Questions will come and me or others can file PRs :-)

One answer I need to finish the Android thing:

> How to add comments to the strings? Directly editing strings.xml? Or editing another file?

**Comment by stefan-niedermann** [comment]
> How to add comments to the strings? Directly editing strings.xml? Or editing another file?

Yep.

Usually you will find a `strings.xml` file at

```
myfancyapp/app/src/main/res/values/strings.xml
```

Just put a comment directly above an `xml` tag to make it appear in Transifex like:

```xml
1 <resources>
2     <!-- Key is a string just for demonstration purposes -->
3     <string name="example_key">Key</string>
4 </resources>
```

The string in line `3` will be the term which will be translated and the content of line `2` in this example (`Key is a string just for demonstration purposes`) will be visible as descriptive text in Transifex.

**Comment by rakekniven** [comment]
Ok, thanks for explaining. 

With Qt you do this in your c++, qml, or js files and the command lupdate is creating the TS file. I thought maybe the Strings.xml is generated as well. But hey sometimes it is easier than you think :-)

**Comment by stefan-niedermann** [comment]
:slightly_smiling_face: There is some tooling support from Android Studio for the `strings.xml`, but for this kind of comments i am not aware of any tools.

Just putting the comment above the `xml` items should be easy enought, though. Even for beginners :)
