### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by markushub** [stefan-niedermann/nextcloud-deck#738]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

after start app deck and switch to another list app full crash

**To reproduce**
Issue is reproducible with an account from [try.nextcloud.com](https://try.nextcloud.com):
- [ ] Yes
- [X] No

Not reproduceable only stacktrace available.

**Expected behavior**

no crash and no terminate

**Screenshots**

**Versions**
 - Nextcloud: 20.0.1
 - Nextcloud Deck: 1.2.1
 - Nextcloud Android: 3.13.1
 - Nextcloud Android Deck: 1.12.1

**Smartphone (please complete the following information):**
- Device: 
- Android-Version: 
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [X] F-Droid
  - [ ] Huawei AppGallery

**Are you using LDAP?**
- [ ] Yes
- [X] No

**Stacktrace**

```
Full Crash:

App Version: 1.12.1
App Version Code: 1012001
App Flavor: fdroid

Files App Version Code: 30130190

---

OS Version: 3.18.120-perf-Arrow(2048)
OS API Level: 29
Device: potter
Manufacturer: motorola
Model (and Product): Moto G5 Plus (XT1685) (Moto G5 Plus)

---

java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at it.niedermann.nextcloud.deck.ui.stack.StackAdapter.getItem(StackAdapter.java:27)
	at it.niedermann.nextcloud.deck.ui.MainActivity$2.lambda$onPageSelected$0$MainActivity$2(MainActivity.java:365)
	at it.niedermann.nextcloud.deck.ui.-$$Lambda$MainActivity$2$gVXVsKBteblzVi3hq493mMui3p8.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```

**Comment by desperateCoder** [comment]
Oops? Probably my bad. Thanks for reporting! I'll have a look! Thanks!

**Comment by stefan-niedermann** [comment]
@desperateCoder sure? looks more like an issue with the UI...

@markushub are you able to reproduce this issue or did it only happen one single time?

**Comment by desperateCoder** [comment]
@stefan-niedermann u're right... I misread StackAdapter... Probably your bad. 😄

**Comment by markushub** [comment]
currently no to reproduce. It happens only once.
Maybe you can catch the exception direct from source.

**Comment by stefan-niedermann** [comment]
@markushub i am also not able to reproduce the issue...? We did quite some work since `1.12.x`, chances are high that this was just a one-shot-dirty state or some other hick-up.

If you also didn't see it in the past, would you mind closing this issue until one can reproduce it / if it happens again?

**Comment by markushub** [comment]
It never occoured in latest versions. Thank you for diagnostic. Closing
