### ISSUE TITLE
Translation typo

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#739]
@rakekniven i don't have the resource ID in mind right now (i'm on my phone), but i noticed this typo and wanted to let you know:

"Keine Schlagwort**e** zuweisen"?
"Keine Schlag**wörter** zuweisen"?

![Screenshot_20201121-145307_Nextcloud_Deck](https://user-images.githubusercontent.com/4741199/99878971-6d005c00-2c09-11eb-92af-e338ac7b5167.png)

Edit: It's in the Deck Android App.

**Comment by rakekniven** [comment]
English string is: "No assigned tag"

So changed it to "Kein Schlagwort zugewiesen".

Your german suggestion would bring me to english string "Do not assign tags". Am I wrong?

**Comment by desperateCoder** [comment]
@rakekniven nope, you're right! But the trailing 'e' of "keine" shouldn't be there like it is in Stefans screenshot (no plural)

**Comment by stefan-niedermann** [comment]
> "Kein Schlagwort zugewiesen"

Sounds good 👍

**Comment by rakekniven** [comment]
Ok, feel free to close it.

**Comment by stefan-niedermann** [comment]
🙏  thank you :)
