### ISSUE TITLE
Actionbar has wrong text color on Android 4

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#74]
**Describe the bug**
On Android 4 the text color of the
- [x] board titles
- [x] the stacks is black on a blue background.
- [ ] Icons in MainActivity

**Expected behavior**
It should be white on blue background, just like the toolbar in the about activity

**Screenshots**
![device-2019-05-09-172927](https://user-images.githubusercontent.com/4741199/57466069-314cae00-7280-11e9-8e41-a0faafb86125.png)

**Smartphone (please complete the following information):**
 - Device: every
 - Android-Version: 4

For sure has something to do with the `styles.xml`, but i have no clue what... @AndyScherzinger any idea? You chose the `Bridge`-theme, maybe this has some issues?

**Comment by AndyScherzinger** [comment]
Hard to say, I can have a look at it but it might take some time... Just started a new project gig at work...

**Comment by stefan-niedermann** [comment]
Thsi issue has been solved in the meantime.
