### ISSUE TITLE
iOS app

### ISSUE THREAD

**Issue by ctr49** [stefan-niedermann/nextcloud-deck#750]
**Is your feature request related to a problem? Please describe.**
I would like to use Nextcloud Deck on iOS but this app is only for Android.

**Describe the solution you'd like**
Either port the app to iOS or refactor the app to be platform-agnostic (i.e. through Flutter?)

**Describe alternatives you've considered**
An alternative is to use the online web interface to Nextcloud in the browser. The shortcomings of this approach led to the very existence of this app, so it is not really an option.
Another one would be a complete new iOS app. But why waste resources and do everything from scratch and have two code bases that need to be maintained?

**Comment by desperateCoder** [comment]
Hi @ctr49,

thanks for the interest in our app! have a look at this one: 
https://github.com/cbackas/iOS-Deck

@cbackas is surely happy, if the iOS users show some interest in his repo as well.

For us, we dont't have Macs, we don't have Apple Developer accounts which are ridiculously expensive, and we have zero skills in Swift or Objective C. Our app itself is completely Android native, porting that would be just insane. So i'd suggest to share some love to @cbackas to get that working. 

Sorry, but I have to say it as clearly as I can: Would be nice, indeed, but we're not the droids you're looking for.
