### ISSUE TITLE
Not showing attached files in mobile app

### ISSUE THREAD

**Issue by neerro** [stefan-niedermann/nextcloud-deck#754]
**Describe the bug**
When I attached the image (.jpg) to the Deck task I couldn't saw the image preview and full image when I tried to open it. Attached screenshots is self explanatory of the issue.  

**To reproduce**
Issue is reproducible with an account from [try.nextcloud.com](https://try.nextcloud.com):
- [ ] Yes
- [x] No (Because the issue is on the app)

**Expected behavior**
I would to see the preview and full size of the image (in the frame of screen) when I open it.

**Screenshots**
![Screenshot_20201211_110406_it niedermann nextcloud deck play](https://user-images.githubusercontent.com/75830569/101879305-2e274b80-3ba2-11eb-95b2-dfe6dc2cd914.jpg)
![Screenshot_20201211_110418_it niedermann nextcloud deck play](https://user-images.githubusercontent.com/75830569/101879309-2f587880-3ba2-11eb-9303-73b072e5f5fc.jpg)

**Versions**
 - Nextcloud: 20.0.3
 - Nextcloud Deck: 1.2.2
 - Nextcloud Android: 3.14.1
 - Nextcloud Android Deck: 1.12.1

**Smartphone (please complete the following information):**
- Device: Honor 10 Lite
- Android-Version: 10
- App-Store:
  - [x] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Are you using LDAP?**
- [ ] Yes
- [x] No

**Comment by desperateCoder** [comment]
Hi @neerro,
thanks for your report and sorry for the inconveniences. 

Is your nextcloud server installed on the root of your domain? By that I mean is it something like `my-nextcloud-domain.ru` or is it `my-nextcloud-domain.ru/nextcloud`?

In the card list view, is your user-avatar shown in the top right corner? Or is it a generic user-icon?

**Comment by neerro** [comment]
Hi Artur, 
The nextcloud domain has a view as: my-nextcloud-domain.ru/nextcloud
Avatar is shown as a generic user-icon as I didn't put my personal user-icon.

**Comment by desperateCoder** [comment]
Ok, I think this is related to this issue: https://github.com/stefan-niedermann/nextcloud-deck/issues/664

I guess your avatar in the looks like this?
![grafik](https://user-images.githubusercontent.com/6911132/101884940-b523f600-3b99-11eb-9f02-f9c25316f8d1.png)
and not like this:
![grafik](https://user-images.githubusercontent.com/6911132/101885115-fb795500-3b99-11eb-8861-428c6dd25f94.png)
(this is my default avatar in nextcloud web-client, ignore the black borders, shitty screenshot :laughing:)
Can you confirm this?

The mechanism how we fetch the avatars and the attachments is the same, so i guess we have some problems with Nextcloud instances running in a subfolder.

**Comment by neerro** [comment]
"I guess your avatar in the Android app looks like this?" - definitely Yes.
Now I checked and found that I have approximate the same issue (image view) with Deck on web application (I haven't capability to see images in preview).

**Comment by desperateCoder** [comment]
> Now I checked and found that I have approximate the same issue (image view) with Deck in web-client

Well, that's very interesting! Thanks for sharing this information with us!
@MelBourbon, @jvlker can you confirm this behaviour on your instances?

**Comment by stefan-niedermann** [comment]
Stop. @desperateCoder in the Web UI it is **no** bug but a not yet implemented feature (see https://github.com/nextcloud/deck/issues/2645). Please focus only on the Android app here.

**Comment by Mangleuz** [comment]
I (in retrospect stupidly enough) replied and also updated my reply to this here: #706

**Comment by stefan-niedermann** [comment]
Good news, we believe that we have been able to solve this issue completely. If you want, you can safely try the solution, installing the [latest `APK` directly from here](https://github.com/stefan-niedermann/nextcloud-deck/suites/1700393111/artifacts/31998649) - it will be installed parallel to your default Deck Android app.

It will be released with the next version `1.13.5`.

Please don't hesitate to open a new issue if the described problems are still present at the linked `APK` or in the released version `1.13.5` or higher! Thank you for reporting! :slightly_smiling_face:

**Comment by neerro** [comment]
Pleased to hear it from you Stefan. Really that's good news. Thank you for your nicely collaboration and hard work. I'll be waiting  with impatience for a new release (and while I'll try the latest APK). Would you tell an approximate date for it?

**Comment by stefan-niedermann** [comment]
We are currently releasing `1.13.4` in a staged rollout (currently ~ 10%). We aim to get it to 100% until Dec 24.

I will publish `1.13.5` at the [Play Store beta channel](https://play.google.com/apps/testing/it.niedermann.nextcloud.deck.play) later today. It will take a few weeks though until we can roll out it completely at the production channel for all users finally (which is only partially our fault, because Google currently needs a few weeks for each release because of Corona).

**Comment by dtcg** [comment]
Issue is still happening: attachments are not showing in the mobile app.

**Context**:
F.droid version 1.14.6
Attachments are docx files, showing on desktop and stored on Nextcloud.

**Comment by stefan-niedermann** [comment]
There are no previews for non-image files but only generic icons.

If the attachments aren't shown at all please open a new issue filling the complete issue template including a screenshot. This issue was about something different (generic icons were displayed instead of previews).
