### ISSUE TITLE
Nextcloud files app (dev)  from fdroid not recognised 

### ISSUE THREAD

**Issue by lachmanfrantisek** [stefan-niedermann/nextcloud-deck#78]
**Describe the bug**
The app (fdroid 0.0.2) shows the pop-up, that the Nextcloud files app is not installed. I am already using dev version of files app from the fdroid (20190502 version).

**To Reproduce**
1. Start the app
2. See the pop-up, that the Nextcloud files app is not installed.
3. Try to add a new account from the side menu. (what was weird, I'll fill a new issue for that.)
4. See the pop-up, that the Nextcloud files app is not installed.
5. Try clicking on :heavy_plus_sign: , but it raises an error: `... Account.getId()` on a null object reference.` (Should I need to create a new issue for this one?)

**Expected behavior**

- It would be nice if the app can recognise dev version of Nextcloud from fdroid. (Is the problem here, or on the site of the Nextcloud app.)
- Or at least allow adding a new account by hand.
- Handle the actions like :heavy_plus_sign: without error, when there is no account.

**Screenshots**

(Sorry for the czech version.)

![Screenshot_2019-05-16-07-09-30-203_it niedermann nextcloud deck](https://user-images.githubusercontent.com/20214043/57828167-db5d9600-77aa-11e9-9614-6434415c9a60.png)

![Screenshot_2019-05-16-07-09-10-413_it niedermann nextcloud deck](https://user-images.githubusercontent.com/20214043/57828166-db5d9600-77aa-11e9-8611-aea7f10737bd.png)

**Smartphone (please complete the following information):**
 - Device: Xiami Mi4c
 - Android-Version: 7

**Stacktrace**

```
Attempt to invoke virtual method `.....ck.model.Account.getId()` on a null object reference.
```

-----

Thanks for your work! Looking forward to using it!

**Comment by stefan-niedermann** [comment]
Thank you for the report. We are currently talking to the authors of the Single-Sign-On about how this issue can be fixed. :)

**Comment by tobiasKaminsky** [comment]
As far as I know SSO currently requires the official app installed, and cannot be used with dev version of files app.

**Comment by lachmanfrantisek** [comment]
Thank you for the response!

> As far as I know SSO currently requires the official app installed, and cannot be used with dev version of files app.

OK, so it is a "problem" with the main app?
Is it possible to support basic login or we would like to use Single-Sign-On only?

Thank you!

**Comment by violoncelloCH** [comment]
I've got something similar... With the normal Nextcloud Files app from F-Droid, when I open Deck, it shows a prompt to select the the account from the files app or "add an account"... When selecting my account (default) and clicking ok Deck shows an error with "you have to allow access to single-sign-on", however there was no promt or anything...

**Comment by stefan-niedermann** [comment]
For reference: https://github.com/nextcloud/Android-SingleSignOn/pull/63

**Comment by desperateCoder** [comment]
Hi @lachmanfrantisek, violoncelloCH, 
The SSO guys @David-Development  and @tobiasKaminsky have released a new version supporting the Dev-App (see https://github.com/nextcloud/Android-SingleSignOn/pull/63).

Feel free to test the latest master (i bumped the version) and if it works, get those guys a beer already! :grin:

**Comment by stefan-niedermann** [comment]
The latest version of this app (0.0.5) supports the dev app of files. Please wait a few days until it gets released on F-Droid or compile it from the master branch.
