### ISSUE TITLE
Archiving cards isnt synced to Android App

### ISSUE THREAD

**Issue by morbificagent** [stefan-niedermann/nextcloud-deck#787]
If i archive a card in ne nextcloud deck webinterface this state isnt reflected to the Android-App.
If i mark the card as archived in the android app i get the errormessage: 

"Status 500 Operation not allowed. This card is archived."

Which make sense, because it is already ;-)

Now i get the Sync-error on every sync of the android app :-(

The Server is Nextcloud 20.0.4 and the deck app on both sides is from today...

**Comment by desperateCoder** [comment]
Hi @morbificagent, 

Thanks for your report! We'll have a look at this.

As a quick fix for your syncing errors, just clear the app data storage in the Android app settings. Then just reconnect in the deck app and you should be fine, until we fix this.

Stay safe!

**Comment by morbificagent** [comment]
Hi together,

wow, that was a fast reply and i was it home already..
I have reinstalled the Android-App yesterday and at the moment i cant reproduce the problem.
So eventually it was a "bad timing" as i have marked the card as archived in the Webinterface, hadnt synced the android app and tried to mark it as "archive it" in the app... If i sync now it would repot this error as the app doesnt know that the card is marked as archived already.

I think it would be great if there would be a routine to catch this scenario as the user shouldnt get such errormessages...

**Comment by stefan-niedermann** [comment]
Ah, so you marked it as archived in both, the web UI *and* the android app and **then** performed a sync? this might explain the clash indeed... 🤔

**Comment by morbificagent** [comment]
Yes, right.

Eventually it would be possible to catch in any way like that a "last change time"of the editing card could be checked or something like that. And if the last change time of that specific card is after the last sync -> force a sync before make changes

**Comment by stefan-niedermann** [comment]
Well... hello there conflict handling 😆 We will find a solution :)

**Comment by morbificagent** [comment]
;-) Perfect

**Comment by desperateCoder** [comment]
> I think it would be great if there would be a routine to catch this scenario as the user shouldnt get such errormessages...

I absolutely agree. Isn't even that hard. **But:**

> Eventually it would be possible to catch in any way like that a "last change time"of the editing card could be checked or something like that. And if the last change time of that specific card is after the last sync -> force a sync before make changes

This takes this whole thing to another level. Conflict handling is a very complex thing to accomplish, without messing up any data of our users (e.g. yours). Might work in a couple of scenarios, but could go very, **very** wrong. For now, I'd go for the small solution catching the archived-scenario and see, if we can get full conflict handling to work. But this will take quite a while, sorry. I'm damn scared of the imagination to decide what happens to our users data, without knowing and understanding the exact content. One little inaccuracy could lead to a complete disaster, so please be patient on this. We have way more uncritical, but very useful stuff to get done for now. 

Thanks for reporting by the way, we'll keep this issue open and see, how we can get this work more flawlessly.
