### ISSUE TITLE
Upgrade colorpickerview

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#790]
Follow-Up issue to https://github.com/stefan-niedermann/nextcloud-deck/pull/788

> `2.1.9` has a breaking change I'm unsure of how to fix

[Changelog](https://github.com/skydoves/ColorPickerView/releases)

**Comment by TacoTheDank** [comment]
@stefan-niedermann The specific breakage is that the `@drawable/wheel` resource called [here](https://github.com/stefan-niedermann/nextcloud-deck/blob/e94355ebf47cc345c5e455f7b9803e5f7f8e9d2a/app/src/main/res/layout/widget_color_chooser.xml#L41) no longer exists, and I think you now have to create one manually using one of the [color palettes](https://github.com/skydoves/ColorPickerView/releases/tag/2.1.9).
