### ISSUE TITLE
Set up transifex

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#8]
Maybe @MorrisJobke can help out and set up the same automization like at the [Nextcloud Notes App](https://github.com/stefan-niedermann/nextcloud-notes/issues/14#issuecomment-274211294)?

:heart: :smiley:

**Comment by MorrisJobke** [comment]
@stefan-niedermann Sure - give @nextcloud-bot push permissions to this repo and we are in the game. BTW I documented the way on how to setup this: https://docs.nextcloud.com/server/14/developer_manual/app/l10n.html#setup-of-the-transifex-sync but let me do this quickly :)

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/docker-ci/commit/1ceb9d38f88205b3f71a2933b1a3826539ed6533

**Comment by MorrisJobke** [comment]
Once #11 is merged and @nextcloud-bot has push access it will show up in the `transifex` branch.
