### ISSUE TITLE
📆 Upcoming cards widget

### ISSUE THREAD

**Issue by jakobroehrl** [stefan-niedermann/nextcloud-deck#800]
Thanks for this nice improvement 👍 
On my test it doesn't update the view.
Is this already implemented?

**Comment by stefan-niedermann** [comment]
Yes this has been implemented. Please be more verbose about the issue:
- Have you tried a pull to refresh to perform a sync?
- Does it work for local changes or also not for local changes?
- What kind of actions did you perform? Move / Create / Edit, ...

**Comment by jakobroehrl** [comment]
Tested and found the problem. 
Due cards are only shown if I'm one of the assignees. This is good for shared board but not for private boards, I think.
At least so it is implemented on the server app

**Comment by stefan-niedermann** [comment]
I asked @juliushaertl a few weeks ago whether he can explain me how the "Upcoming cards" view of the Web UI works, but he seems to be a bit busy right now. Maybe you have more insights about this view in the Web UI?

Did we miss any other rule?

What we have right now:
- Display each card where `current user` is assigned, sorted and grouped by the `due date`

What we missed according to your comment:
- Display also each card where the card is on a board which is *not* shared with anybody else

Is this correct @jakobroehrl ?

**Comment by jakobroehrl** [comment]
This is right.

**Comment by stefan-niedermann** [comment]
@jakobroehrl would you please test [this apk](https://github.com/stefan-niedermann/nextcloud-deck/suites/1936029170/artifacts/38210062)? It should also show all cards of not-shared boards with a due date.

Thanks to @desperateCoder who implemented the missing feature!

**Comment by jakobroehrl** [comment]
Tested it, it works much better, thanks!
Found nevertheless a bug, I think. 
To me assigned cards are twice in the widget list.

**Comment by stefan-niedermann** [comment]
Will be tracked in #818
