### ISSUE TITLE
Single Sign-on not working with Android 7

### ISSUE THREAD

**Issue by croulibri** [stefan-niedermann/nextcloud-deck#81]
Nextcloud deck 0.6.2 on Nextcloud 15.0.5.
Android 7.1.2. with

- Android Nextcloud 3.6.0 (from f-Droid)
- Adroid Nextcloud Deck 0.0.2 (from f-Droid) 

---- 

When I first open Nextcloud Deck on my Android device, I have to choose a Nextcloud account on the account chooser dialogue. I select an existing one and immediately I have a pop-up "_Error : You have to accept the requested permissions to use the single sign-on feature_" (see 2 first pictures at https://github.com/nextcloud/Android-SingleSignOn/issues/60#issuecomment-490122872)

So I can't log in to my existing Nextcloud account.
Android Nextcloud Deck doesn't crash but is unable to open my Nextcloud account.

According to https://github.com/nextcloud/Android-SingleSignOn/issues/60 it seems to be a known issue, but I am not clear if the fix has been implemented yet and if Nextcloud Deck need to integrate a fix.

**Comment by David-Development** [comment]
@croulibri It has been fixed, but it is not published yet ([PR](https://github.com/nextcloud/Android-SingleSignOn/pull/62)). I will release an update of the SingleSignOn library soon!

There are some changes required in this app as well.. not sure when @stefan-niedermann and @desperateCoder are planning on doing another release.
Or are you guys waiting for me?

**Comment by stefan-niedermann** [comment]
We are waiting for the next stable release of the sso lib and then publish a new version on F-Droid :)

**Comment by David-Development** [comment]
@stefan-niedermann 0.3.1 is out ;) https://github.com/nextcloud/Android-SingleSignOn/releases/tag/0.3.1

**Comment by stefan-niedermann** [comment]
Great news, thank you :)

**Comment by stefan-niedermann** [comment]
@croulibri can you retest the login with the current master please?

**Comment by stefan-niedermann** [comment]
@croulibri forget it, i see there is still some work left. Tracking in https://github.com/stefan-niedermann/nextcloud-deck/tree/android-7-permissions

**Comment by stefan-niedermann** [comment]
Login is now possible with android 6 and 7 (master-branch) - Please note, that there are still some problems left with multi account setup

**Comment by croulibri** [comment]
Yes, login is now possible with Android Nextcloud Deck 0.0.3 (from f-Droid)

Thanks !

**Comment by AlmightyFrog** [comment]
Is there any further action needed? It still does not work on on devices (Android 7 and 8).
The versions I have installed are from F-Droid: Nextcloud 3.7.0 RC and Nextcloud Deck 0.0.3

**Comment by desperateCoder** [comment]
Hi @AlmightyFrog,
Dis you try to un- and reinstall the whole app?
Sometimes the local database needs to be wiped, that's the simplest way.

**Comment by stefan-niedermann** [comment]
Also: Does the login itself work or are just no boards displayed? There is another bug with the server app version 0.6.4 which will soon be fixed in the android version 0.0.4 :)

**Comment by AlmightyFrog** [comment]
Yes, I did full reinstall, clearing cache. Didn't help at all. It was like i was presented my account to select but when i clicked on it I got message like shown in this issue. I saw the permission request for accessing contacts, but not the one to find accounts on my device (in german "Konten auf dem Gerät suchen"). looks like that was missing.

Had to enable this manually on the LineageOS built in permissions manager and now it works. Maybe could you check if you request this specific permission?
