### ISSUE TITLE
Filter Widget issue with Multiple Assignees

### ISSUE THREAD

**Issue by tilllt** [stefan-niedermann/nextcloud-deck#813]
Thanks for the phantastic App.
There is a minor issue with the "Filter by Username" functionality. As far as i can see, the Filter needs an exact match to show Cards that are assigned to you. That maybe a desired behaviour for some people, in our context, we have tasks which are assigned to multiple people in the Team.

I may have a Task to complete, it may be assigned to
- John Doe
**AND**
- Jane Doe

Whoever has time first to complete it. should take care of it. But if i filter for all Tickets assigned to John Doe, Tickets assigned to multiple Users will not show up. I think they SHOULD show up, if my user is assigned, regardless if other users are assigned as well. Or the filter needs to be configurable, which (as far as i could see) it is not.

So in filter lingo, the filter by username should work by "Contains", not "Matches" logic, imho.

Thanks

**Comment by desperateCoder** [comment]
Hi, thanks for your report!

I absolutely agree with your point, but I thought I built it just that way... Tested the filter and got this:

https://user-images.githubusercontent.com/6911132/106133846-13b32c80-6166-11eb-9a68-80f438e73fbf.mp4

Did I understand something wrong? You mentioned a Widget, but it is work in progress and not yet released afaik. Do you mean the stuff in the video above?

**Comment by stefan-niedermann** [comment]
@desperateCoder the "Upcoming cards" widget is released on F-Droid and at the Play Store beta channel. He means that.

**Comment by tilllt** [comment]
No, sorry for the confusion. I think I used the term "Widget" while I mean the app. I am checking right now if there is a different problem that causes the mentioned behaviour.

**Comment by tilllt** [comment]
There was a totally unrelated problem with the Sync of the Cards, so i couldnt find them since they were not already synced. Sorry for the confusion. Thanks again for the great app.

**Comment by desperateCoder** [comment]
😅 never mind, you're welcome! Glad, it worked out for you!
