### ISSUE TITLE
📆 Upcoming cards widget - assigned cards duplicates

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#818]
Origin: https://github.com/stefan-niedermann/nextcloud-deck/issues/800#issuecomment-770611171

Cards from boards which are not shared which areassigned to one self will be in the Card widget doubled.

**Maybe we should simply use as `Set` instead of a `List` here?**

**Comment by desperateCoder** [comment]
fixed on `master`

**Comment by stefan-niedermann** [comment]
@jakobroehrl In case you want to test & confirm: [Here is the `.apk`](https://github.com/stefan-niedermann/nextcloud-deck/suites/1941453844/artifacts/38354532) which should fix the duplicates :slightly_smiling_face: - thx @desperateCoder

**Comment by jakobroehrl** [comment]
Working fine.
The cards in the category "no due" are on the server version only shown if they are on a shared board and assigned to me.

**Comment by stefan-niedermann** [comment]
@jakobroehrl please open a separate issue for that :) We can enhance the widget step by step, but now we will roll out it first, before we are getting lost in fine tuning - i heard some people are waiting for it :smile:
