### ISSUE TITLE
📆 Upcoming cards widget - "no due" cards

### ISSUE THREAD

**Issue by jakobroehrl** [stefan-niedermann/nextcloud-deck#819]
Origin: https://github.com/stefan-niedermann/nextcloud-deck/issues/818#issuecomment-770824058

Cards in the category "no due" are on the server version only shown if they are on a shared board and assigned to me.

**Comment by desperateCoder** [comment]
Hi @jakobroehrl, 
try [this](https://github.com/stefan-niedermann/nextcloud-deck/suites/1949752262/artifacts/38588190) please and let us know what you think.
 
![image](https://user-images.githubusercontent.com/6911132/106592703-2061c700-6550-11eb-8125-40803262c616.png)

**Comment by stefan-niedermann** [comment]
Released in `1.14.5`.

**Comment by yellowapple2018** [comment]
Hi, how can I get version 1.14.5 ?
