### ISSUE TITLE
After adding second account list of boards dont refresh

### ISSUE THREAD

**Issue by kai11** [stefan-niedermann/nextcloud-deck#82]
**Describe the bug**
After adding second account list of boards dont refresh

**To Reproduce**
1. Add one account
2. Left sidebar display correct boards for this account now
3. Add another account
4. Select it from accounts menu
5. Left sidebar still shows boards from old account
6. Switching accounts and refresh gesture don't help - lost of boards have only boards from first account.

**Expected behavior**
I expect list of boards from second account in left sidebar.

**Smartphone (please complete the following information):**
 - Device: Moto Z Play
 - Android-Version: 8

App version: 0.0.2 from fdroid

**Comment by desperateCoder** [comment]
Hello again @kai11 :D

Thanks for the report, we will have a look at this.

Just wondering: if you restart the app, does something happen? As I remember from the last time I tried, they should suddenly appear..

And a dummy-question: is the server-deck-app version of your second account or instance  up to date?

**Comment by kai11** [comment]
Closing, swiping app left and reopening dont help.
Force stop dont help either.
They appear after some time - few hours or so.

**Comment by DCSH82** [comment]
Can confirm this behaviour. Server side deck app is up-to-date, deck 0.6.2 on nextcloud 16.0.1. No ability to refresh or list boards on second account.

**Comment by desperateCoder** [comment]
Maybe related to SSO? Didn't @david-development or @tobiasKaminsky mention something about multi account handling not working properly? It worked well before the refactoring of the SSO, do you guys have further information or might this really be a bug in deck?

**Comment by tobiasKaminsky** [comment]
Hm. SSO should now work with multi accounts.
(the only problem right now is multi apps (official files app vs. dev files app)

**Comment by desperateCoder** [comment]
Thanks, I'll have a look at it as soon as I can

**Comment by desperateCoder** [comment]
Hi @Aquariu ,
thanks for the report! We will fix this as soon as possible!

@stefan-niedermann this one is getting out of hand, please give it a look before 0.0.3!

**Comment by Aquariu** [comment]
Please note that there was no urgency in my report :) I realise this is not production ready and that's fine.

Congratulation on you for working on this. I will keep on testing releases until it's ready for my use case.

Kind regards,

Olivier

**Comment by desperateCoder** [comment]
@Aquariu since you are the third one reporting this, I would like to solve this asap, but thanks for comforting us :laugh: 

Thank you for your support, we hope you guys like our work and are proud of having that much reactions and users for a pre-alpha, buggy app :sweat: 

Stay tuned! The next release will hopefully come soon!

**Comment by stefan-niedermann** [comment]
I think this might be solved in the meantime on master (with 8a197a3c29b029319f82703cc461b1ebff54a88c)

@kai11 can you retest with master and tell us if the second account is still not synchronizing when creating it initially?

**Comment by Nils160988** [comment]
I can also confirm the bug for 0.0.2.

Retest with current master works fine :)

**Comment by stefan-niedermann** [comment]
Great to hear :) I will close this issue.

And thanks for testing and reporting!

**Comment by Aquariu** [comment]
Just came here to confirm bug closure: second account via Single Sign On works like a charm, switching back and forth between both works great to.

Thanks :)

**Comment by desperateCoder** [comment]
Great! Thanks for testing! Stay tuned!

**Comment by stefan-niedermann** [comment]
:rocket: :rocket: :rocket:
