### ISSUE TITLE
Upcoming cards widget - cards of deleted/archived boards are shown

### ISSUE THREAD

**Issue by jakobroehrl** [stefan-niedermann/nextcloud-deck#822]
I see some cards of deleted and/or archived boards in my overview widget

**Comment by desperateCoder** [comment]
Very good point! Thanks! I am currently filtering only deleted, cards, my bad. I'll fix that asap

**Comment by desperateCoder** [comment]
I just fixed this in 9891fc39ffff0ab67d63c38037435e2746c05558 . Unfortunately i messed up the commit message (wrong ticket id), but yeah, no problem at all.

@jakobroehrl if you like, you can give it a try: [Download APK](https://github.com/stefan-niedermann/nextcloud-deck/suites/2037061654/artifacts/40961899)

**Comment by desperateCoder** [comment]
ping @jakobroehrl :sweat_smile:

**Comment by jakobroehrl** [comment]
Working fine, good job!

**Comment by stefan-niedermann** [comment]
@desperateCoder already in `master`?

**Comment by desperateCoder** [comment]
✅

**Comment by stefan-niedermann** [comment]
Great! Will be released with `1.14.6` then :slightly_smiling_face:
