### ISSUE TITLE
Attach a file to a card,or add text to a card through the android Intent system

### ISSUE THREAD

**Issue by Aquariu** [stefan-niedermann/nextcloud-deck#83]
**Is your feature request related to a problem? Please describe.**

Not really.

**Describe the solution you'd like**

As proposed recently in [here](https://github.com/nextcloud/deck/issues/1060), the Files app could share to a Deck card (avoiding the need to download the file first, or sharing a link only). 

If ever that gets done, there could be the same kind of attachment process on the android versions of both apps.
The Deck android app could register an android sharing intent so that Nextcloud android apps (or any app!!) could share a file directly to a Deck Card. The intent could also be for text, to share a piece of text directly to a new or existing Card.

**Describe alternatives you've considered**

The Android Intent system is supposed to be a very easy way to share between apps. So I haven't really thought about alternative.

**Additional context**

Apps register to the android system to be in the list of apps that can recieve "Share to..." actions. Deck could use that if and when we get card creation and edition. As an intermediate step, any sharing action could just result in a new card creation (instead of a more complex addition to an existing card).

**Comment by tobiasKaminsky** [comment]
Talk app is doing something similar…
Maybe it is worth to take a look?

**Comment by Aquariu** [comment]
Addition:

I juste realised that tapping on a Notification in the Nextcloud android app would open the Browser.
And there are notifications when a shared card is updated by someone !
The Intent mentionned above should also be able to propose the user to open the Deck app when tapping on this Notification.

Kind regards,

Olivier

**Comment by tobiasKaminsky** [comment]
Hm. Ideally Deck app should handle those push notifications directly, like Talk is doing it.
If the "specialized" apps are not installed / do not handle it, it is ok that Nextcloud Files app is showing it and then redirects to web UI.

**Comment by Aquariu** [comment]
OK. I am not familiar with how 2 apps will sort-of fight over which get the right to handle push notifications. Your way is better if it's feasible. It will require additionnal settings in the app itself to turn On/Off notifications (not everybody likes to be bothered this way).

**Comment by tobiasKaminsky** [comment]
Each app is registering on server for push notification and as far as I understood it, there is then a predefined order, so that first NC Talk will get the message, and only if it not installed it will go to NC Files app.
But this is logic done on server side.



> It will require additionnal settings in the app itself to turn On/Off notifications (not everybody likes to be bothered this way).

True, but e.g. on Talk or Files there is also (not yet) such a config, or?

**Comment by stefan-niedermann** [comment]
Of course, all the intents to handle files and text are welcome features. The only problem i see it receiving push notifications directly, as the deck android app does not and will never rely on a proprietary service like the Google services (greetings to huawei ;) ). Therefore: If we can find a way to handle this (of course without polling), then i appreciate to build it in, under the permission that no proprietary services are used. It is also not planned to provide different flavors.

**Comment by Aquariu** [comment]
I was under the impression that the f-droid versions of Nextcloud, Talk, .... were built without GCM. (Google Cloud Messaging). How do they manage to get notifications to the users ? (or maybe I'm totally wrong).

**Comment by Spartachetto** [comment]
As far as I understand Nextcloud Talk (fdroid version) doesn't.

For your reference: https://github.com/nextcloud/talk-android/issues/257 

@mario could eventually give some useful information.

**Comment by tobiasKaminsky** [comment]
None of our fdroid versions (Talk, Files, …) can have push notifications via Google Cloud Messaging as this is not allowed by FDroid (after all that is the idea of true open source, to not use proprietary software).
Talk & Files installed via Gplay do have Push Notification.

**Comment by Aquariu** [comment]
Thank you all for your replies.

My original intent (no pun intended :) ) was about the file upload and inclusion into the Cards. Let's not waste energy on messaging and notification as it's a difficult topic.

**Comment by desperateCoder** [comment]
Hi @Aquariu, please be patient on this, we do our best getting everything to work, i guess as soon as the more critical topics are done, we can focus in card editing and anything belonging there like attachments.

**Comment by Aquariu** [comment]
I'm not in any particular hurry :)
I jus thought that the topic had diverged on notification which was not  (in my opinion) a good thing.

**Comment by stefan-niedermann** [comment]
Closing in favor of #248 (basically a duplicate but with better descriptions about how it might look in the future)
