### ISSUE TITLE
Not showing upcoming cards tab ?

### ISSUE THREAD

**Issue by yellowapple2018** [stefan-niedermann/nextcloud-deck#838]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

**To reproduce**
Issue is reproducible with an account from [try.nextcloud.com](https://try.nextcloud.com):
- [ ] Yes
- [ ] No

**Expected behavior**

**Screenshots**

**Versions**
 - Nextcloud: 
 - Nextcloud Deck: 
 - Nextcloud Android: 
 - Nextcloud Android Deck: 

**Smartphone (please complete the following information):**
- Device: 
- Android-Version: 
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Are you using LDAP?**
- [ ] Yes
- [ ] No

**Stacktrace**

**Comment by desperateCoder** [comment]
There is no "tab", but we have a Widget for your home screen.

You can add it just like any other widget by pressing and holding on a free space of your home screen.

**Comment by stefan-niedermann** [comment]
https://help.nextcloud.com/t/deck-android-1-14-upcoming-cards-widget/106402
