### ISSUE TITLE
App crashes when clicking on "Due date"

### ISSUE THREAD

**Issue by rouvenvolkmann** [stefan-niedermann/nextcloud-deck#84]
**Description**

When creating a new card: clicking on "Due date" or "00:00" next to it, the app always crashes.

**Smartphone:**
 - Device: LG G6
 - Android-Version: Lineage OS 15.1 / Android 8.1.0

**Stacktrace**

```
it.niedermann.nextcloud.deck.ui.card.CardDetailsFragment.lambda$setupView$1$CardDetailsFragment(CardDetailsFragment.java:162)
it.niedermann.nextcloud.deck.ui.card.-$$Lambda$CardDetailsFragment$eflKU6En24sokkOy8LhQho9dbXo.onClick(Unknown Source:2)
android.view.View.performClick(View.java:6294)
android.view.View$PerformClick.run(View.java:24770)
android.os.Handler.handleCallback(Handler.java:790)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loop(Looper.java:164)
android.app.ActivityThread.main(ActivityThread.java:6494)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by desperateCoder** [comment]
Hi @rouvenvolkmann,
thanks for your report!

We will have a look at this, even though it works on my machine (best excuse ever! :smile:)

@stefan-niedermann or @AndyScherzinger feel free to hunt this bug!

Btw: future stacktraces will get a little more detailed: 4d7f5e6dae86b2481f8cbae1d3b5c3fd4ecf9e34

**Comment by AndyScherzinger** [comment]
Can reproduce it on master:
```java.lang.NullPointerException: Attempt to invoke virtual method 'it.niedermann.nextcloud.deck.model.Card it.niedermann.nextcloud.deck.model.full.FullCard.getCard()' on a null object reference```

Latest master should now be fixed :)
