### ISSUE TITLE
Searching feature in decks

### ISSUE THREAD

**Issue by neerro** [stefan-niedermann/nextcloud-deck#847]
It would be great if you'll add to Android  Deck app a searching feature whether in deck itself or in all decks in common.

**Comment by stefan-niedermann** [comment]
Please use the search function before opening new issues.

Duplicate of https://github.com/stefan-niedermann/nextcloud-deck/issues/630

**Comment by neerro** [comment]
Of course I tried search the issue/enhancement before I've created the topic but unfortunately I found nothing. I think that I incorrect used the GitHub search.
