### ISSUE TITLE
Sharing cards through different Android apps whether photo or text. 

### ISSUE THREAD

**Issue by neerro** [stefan-niedermann/nextcloud-deck#854]
Would be nice to implement cards  sharing feature through Android apps whether photo or text. As minimum we could get the information from header and description field, but if it possible better will be taken all card information as date, tags, appointment. 

For example if I wanna share cards with someone from deck app to WhatsApp, Telegram, SMS, cloud app or another available apps installed on my Android device without copy/paste function.

**Comment by stefan-niedermann** [comment]
Starting with version `1.15.1` there will be a menu item on each card to "Share content" - This will contain the description, due date and tags.

Dealing with attachments is way more complicated and therefore out of scope for this issue - We don't store all attachments locally, which would consume too much traffic and storage. Also sending all the stuff (there might be dozens of attachments at a card, or even a 2 GB video file??) might not exactly what users expect in each situation :wink: 
I see the usecase though and i think it makes more sense to make attachments shareable from the attachments (where you currently only can copy the URL)

**Comment by stefan-niedermann** [comment]
(see #836)
