### ISSUE TITLE
Show DisplayName instead of UID attribute for LDAP users 

### ISSUE THREAD

**Issue by ke-lin** [stefan-niedermann/nextcloud-deck#864]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**

The Deck App shows the uid attribute of LDAP users, which is a long cryptic string. This makes switching between different accounts difficult and does not look so nice.

**Describe the solution you'd like**

It would be nice to use the DisplayName attribute for LDAP user for the app "username" attribute in the Account switcher View, instead of the uid.

![Screenshot_20210307-173021](https://user-images.githubusercontent.com/36854855/110247318-f3983980-7f6b-11eb-9337-1d54e7b137b6.jpg)

**Comment by desperateCoder** [comment]
Hi @ke-lin, thanks for your report!

You mentioned the notes app, are you sure this is the right repository for your report? @stefan-niedermann is also the owner of the nextcloud deck app for Android, the repository we are in right now. 

If you accidentally mixed it up, please close this issue and open one here: https://github.com/stefan-niedermann/nextcloud-notes

If you actually refer to the deck app, please explain further, where exactly you want so see the display name.

**Comment by desperateCoder** [comment]
Oh, I just saw you already created one there. Never mind! I'm gonna close this one in favour of https://github.com/stefan-niedermann/nextcloud-notes/issues/1079

**Comment by ke-lin** [comment]
> Hi @ke-lin, thanks for your report!
> 
> You mentioned the notes app, are you sure this is the right repository for your report? @stefan-niedermann is also the owner of the nextcloud deck app for Android, the repository we are in right now.
> 
> If you accidentally mixed it up, please close this issue and open one here: https://github.com/stefan-niedermann/nextcloud-notes
> 
> If you actually refer to the deck app, please explain further, where exactly you want so see the display name.

It is valid for both apps. I just updated the description.

**Comment by ke-lin** [comment]
The DisplayName should be displayed in the Account switcher View.

**Comment by desperateCoder** [comment]
Ok, thanks for the update, and sorry for being hastily :sweat_smile: 

We'll have a look!

**Comment by ke-lin** [comment]
> Ok, thanks for the update, and sorry for being hastily 😅
> 
> We'll have a look!

No worries. It was my fault, since i messed up the issue description.
Thanks for having a look.
I have added a screenshot to the description.

**Comment by stefan-niedermann** [comment]
@ke-lin we need some help from you: Could you please test [this `.apk` file](https://github.com/stefan-niedermann/nextcloud-deck/suites/2464447316/artifacts/52958352) and tell us whether it displays the actual displayName for your accounts? (You can safely install it parallel to your published Deck version). I don't have a LDAP setup, so i implemented it blindly and rely on some feedback :slightly_smiling_face:

**Comment by ke-lin** [comment]
@stefan-niedermann sorry for my late response. I have now installed the "test" apk and it is perfect. The Display Name is now shown in the Account switcher View, instead of the UID. 
![Screenshot_20210415-085241](https://user-images.githubusercontent.com/36854855/114827218-b3c53d00-9dc8-11eb-8961-6ff1b50a83bc.jpg)

**Comment by stefan-niedermann** [comment]
Thank you very much! We are currently busy with a series of errors that made it into published versions, but i will bring this change in as soon as possible.

Just as a hint: The same for the Notes app will take more time because we had here already some prerequisites (user information linked to account information) which is not yet available there.

**Comment by stefan-niedermann** [comment]
Will be fixed in `1.18.0`
