### ISSUE TITLE
Allow to delete "file" attachments

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#871]
A quick test showed, that deleting the new "file" attachments via the Android app doesn't do anything on the server side.
[I therefore temporarily hid the delete button](https://github.com/stefan-niedermann/nextcloud-deck/pull/870/commits/ef8a18f3f5ff2b2f83dfa0b6d201fc7b2a7b0ff4).

- [ ] Reenable the delete button
- [ ] Make sync great again

**Comment by desperateCoder** [comment]
(Documentation for later implementation, need to leave now)

Looks like the ID of the file is kind of different. I tracked the Web-UI call and saw this:

`DELETE | https://nextcloud.niedermann.it/index.php/apps/deck/cards/611/attachment/file:55`

I guess the prefix for the ID has to be `file:`, tho I can't tell why the path is different to [the official documentation](https://deck.readthedocs.io/en/latest/API/#attachments). 

Worth a try!

**Comment by stefan-niedermann** [comment]
Did some work on the `871-delete-attachments-for-1-3` branch. Though i think reverse engineering the Web UI isn't really a good idea. The URL starts with `/apps/deck` for example, instead of `/api/deck`.
I differentiate on the branch so we can easily add the `file:` if necessary, but simply adding `file:` to the old API doesn't work (`HTTP 405`) unfortunately.

**Comment by stefan-niedermann** [comment]
Issue in the server app: https://github.com/nextcloud/deck/issues/2904

**Comment by stefan-niedermann** [comment]
Fixed shipped in Deck Android `1.24.0`.
