### ISSUE TITLE
Listen und Karten 

### ISSUE THREAD

**Issue by Eknatz** [stefan-niedermann/nextcloud-deck#878]
Es wäre toll, wenn Listen und Karten zu kopieren wären. 
Es gibt Strukturen bei denen man Grundgerüste entwickelt, die dann einfach zur Weiterentwicklung in die nächste Liste kopiert werden.
Bei Karten ist es genau so. 

Beste Grüße und vielen Dank für eure. Entwicklerarbeit. 

Matthias

**Comment by desperateCoder** [comment]
Hi @Eknatz, danke  für deine Nachricht!

Wir haben aktuell eine Funktion, die es dir aktuell schon ermöglicht ein ganzes Board zu klonen. Ist dir das als Grundgerüst zu viel? Würdest du dir das feingranularer wünschen? 

Bitte führe etwas genauer aus, wir genau die optimale Lösung für dich aussehen sollte.

**Comment by stefan-niedermann** [comment]
Im Sinne der Funktions-Gleichheit mit der Deck Server-App und um die Oberfläche einigermaßen klar und konsistent zu halten, würde ich dich bitten, **das Issue im [Deck server Repository](https://github.com/nextcloud/deck/issues/new?assignees=&labels=&template=Feature_request.md)** zu **öffnen** (englisch). Sollte dieses dort akzeptiert werden, können wir sehen, ob und wie wir das elegant auch in der Android-App unterbringen können ohne mit 300 Menü-Einträgen zu enden - damit wäre ja schließlich auch keinem geholfen :wink: 

Bis dahin empfehle ich dir als **Workaround** die Funktion "**Inhalt teilen**" im Drei-Punkte-Menü der Karte und im Anschluss "Nextcloud Deck - Neue Karte hinzufügen" zu wählen. Dabei wird die Beschreibung (erweitert um Labels sowie Fälligkeitsdatum) übernommen.

PS.: Auch hier im Issue-Tracker würde ich dich bitten, auf englisch zu schreiben - Nicht jeder Freiwillige Mithelfer hier spricht deutsch (somit können weniger Leute bei Problemen oder Fragen helfen) und Leute, die ähnliche Fragen haben können nicht erkennen, dass diese Frage hier schon einmal gestellt wurde.

**Comment by Eknatz** [comment]
Hallo.

Bei deiner vorgeschlagenen Vorgehensweise wird lediglich die Überschrift übernommen und nicht der Beschreibungstext.

Wir planen mit dem Tool sehr viel und daher ist das kopieren von ganzen Listen, aber auch einzelnen Karten ein sehr wichtiger Bestandteil.
Zum Beispiel planen wir damit ganze Sendungen mit einzelnen Beiträgen. Es gibt immer eine Grundstruktur, die dann zur Planung der nächsten Ausgabe als Grundlage kopiert wird - somit braucht nur das Grundgerüst gepflegt werden.
Wir haben praktisch keine Anwendung bei der das kopieren von Listen und Blocken nicht ein wesentlicher Bestandteil der Planung ist.

Bisher arbeiten wir mit Trello. Da wir jedoch mit der Firma mit allen anderen Bereichen komplett auf Nextcloud umgestiegen sind, möchten wir das auch wirklich komplett in Gänze umsetzen.
Dabei ist uns schon lange klar, das vieles eine Krückenlösung darstellt - insbesondere wenn es um Teamarbeit geht. Das betrifft zum Beispiel ganz besonders Nextcloud Notizen.

Zu dem Thema Deutsch-Englisch. Meine Muttersprache ist deutsch und da kann ich mich am besten Ausdrücken. Ich könnte das Ganze natürlich durch einen Übersetzer jagen - das kann aber auch jeder für sich machen. Dabei geht aber vieles verloren oder wird entsinnt.

Ich kenne sehr viele Geschäftsleute, die sehr gerne bei der Entwicklung von Open Source mitwirken würden, aber genau an dem sprachlichen Hindernis scheitern.
Ich selbst bin unter anderem Dipl. Grafikdesigner, Mitinhaber zweier Firmen und wundere mich immer über den generellen Ausschluß kompetenter Menschen, wegen dieser Sprachbarriere.
Das ist meiner Meinung nach auch der Grund, warum so manches Open Source Projekt nicht wirklich professionell auf die Beine kommt und oft nutzerunfreundlich ist. Programmieren ist eine Sache, ein nutzerfreundliches und modernes Interface eine Andere.
Ein weiterer Grund, warum die meisten zu Mainstream-Produkten greifen und Open Source liegen lassen.
Wie es scheint ist dann an dieser Stelle auch meine Mitarbeit beendet, bevor sie überhaupt richtig begonnen hat.

Ich wünsche euch mit eurem Projekt viel Glück.

Mit freundlichen Grüßen
Matthias Stanke
___

Matthias Stanke
Neustadt 21
29225 Celle

MOBIL  +49 170 8485105
EMAIL ***@***.***
WEB http://matthiasstanke.de


20.03.2021 18:56:21 Niedermann IT-Dienstleistungen ***@***.***>:

**Comment by desperateCoder** [comment]
Hallo Matthias,

> Bei deiner vorgeschlagenen Vorgehensweise wird lediglich die Überschrift übernommen und nicht der Beschreibungstext.

Funktioniert das bei dir wohl nicht? Oder sprichst du über die Web-Variante der App? Schau Mal hier:


https://user-images.githubusercontent.com/6911132/111897106-41a64600-8a1e-11eb-8055-5aeb10608fc2.mp4

Wir übernehmen an dieser Stelle alles, was aus unserer Sicht Sinn macht bzw. technisch möglich ist. Selbst Labels und zugewiesene Personen werden übernommen. Selbst wenn Du jetzt abgeschreckt zu sein scheinst, rein aus Interesse - würde dir das in dieser Form ausreichen?

> Wie es scheint ist dann an dieser Stelle auch meine Mitarbeit beendet, bevor sie überhaupt richtig begonnen hat.

Ich verstehe Deinen Standpunkt durchaus, eine direkte Email-Kommunikation wäre an dieser Stelle vermutlich geschickter gewesen. 

Das soll keine Ausrede sein, nur eine Erklärung: Wir haben hier "nur" eine auf Android angepasste Oberfläche für eine (Nextcloud-Server-)App, die internationale mitarbeit erfährt. Viele der Entwickler sind auch hier unterwegs und wir müssen uns hier irgendwie verständigen. Ich glaube nicht, dass Stefan dich mit seiner Nachricht "disqualifizieren" wollte, ihm ging es mehr um Aufklärung, woher sollst Du als neuer Benutzer das sonst auch wissen? 

Schade, dass das scheinbar so rüberkam und Schade, dass die Reaktion dann doch so heftig ausfiel - dennoch ist es Dein gutes Recht.

> Ich wünsche euch mit eurem Projekt viel Glück.

Danke sehr, wir wünschen dir auch viel Erfolg, auch bezüglich der Suche nach geeigneten Trello-Alternativen. Über eine kurze Rückmeldung zu obiger Frage (unter dem Video) würde ich mich persönlich dennoch freuen :relaxed: 

Schönes Rest-Wochenende und beste Grüße
Artur

**Comment by stefan-niedermann** [comment]
Hallo @desperateCoder 

> Funktioniert das bei dir wohl nicht? Oder sprichst du über die Web-Variante der App?

Nein, es ging @Eknatz um das Kopieren von Listen und Karten (nicht von ganzen Boards).

Hallo @Eknatz 

Es ging mir im wesentlichen darum, zu verdeutlichen, dass wir zwischen der von uns entwickelten Android-App und der Server-App eine gewisse Feature-Gleichheit benötigen, um die Erwartungen aller Benutzer zu erfüllen. Da die Server-App nicht von uns entwickelt wird sondern von der Nextcloud GmbH ist hier ein wenig Kommunikation erforderlich - da wir ein Team aus Freiwilligen sind, sind wir schließlich nicht bei den Sitzungen & Meetings der Nextcloud GmbH anwesend und können uns daher nur auf diesem Wege austauschen. Aus diesem Grund die Bitte, zunächst deinen Feature-Wunsch dort zu stellen - sonst wedelt der Schwanz (wir) mit dem Hund (Nextcloud GmbH / Server-App).

Würden wir jedes Feature ohne uns vorher Gedanken zu machen einplanen oder den Anwendungsfall zu hinterfragen, [würde die Oberfläche in Kürze so aussehen](https://user-images.githubusercontent.com/4741199/111898640-a87c2d00-8a27-11eb-98ae-ecf46f46d607.png). Diese mag dann zwar für jeden Einzelnen ein Feature parat haben, gleichzeitig wäre die App allerdings für niemanden sinnvoll benutzbar. Wie gesagt - ich sperre mich nicht gegen das Feature, ein wenig Kommunikation und vorherige Abklärung muss allerdings aus unserer Sicht aus den oben genannten Gründen sein.

> Bei deiner vorgeschlagenen Vorgehensweise wird lediglich die Überschrift übernommen und nicht der Beschreibungstext.

Tatsächlich. Intention ist natürlich, dass sowohl Titel als auch Beschreibung übernommen werden. Ich konnte den Fall reproduzieren und werde das Problem in einer künftigen Version beheben. (https://github.com/stefan-niedermann/nextcloud-deck/issues/883)

Zum Thema sprachliche Barriere: Ich traue einem kompetenten Mitinhaber zweier Firmen  und Dipl. Grafikdesigner durchaus zu, 3 Zeilen englisch zu schreiben, insbesondere, wenn der fachliche Kontext so simpel ist wie dieser. Dass wir darum bitten ist keine Willkür oder Schikane, auch wir wollen schlicht die Barrieren senken - und zwar für alle. Es ist nunmal leichter von / zu englisch von der eigenen Sprache aus zu übersetzen als von / zu einer völlig anderen Sprache. Wir sind, wie @desperateCoder sowohl im Team als auch bei den Usern international aufgestellt und möchten Mitarbeit von allen Seiten ermöglichen. Hier von einem "Scheitern" von Open Source zu sprechen finde ich ein wenig weit hergeholt.

> Das betrifft zum Beispiel ganz besonders Nextcloud Notizen.

Ich schlage als Alternative den Nextcloud Text Editor vor, der auch kollaboratives Arbeiten ermöglicht und in Kombination mit Notes einsetzbar ist.

> Wie es scheint ist dann an dieser Stelle auch meine Mitarbeit beendet, bevor sie überhaupt richtig begonnen hat.

Wenn du das so sehen willst finde ich das zwar sehr schade, es ist aber natürlich, wie @desperateCoder bereits geschrieben hatte, dein gutes Recht. Auch wir wünschen dir weiterhin Glück und Erfolg beim Einsatz von Nextcloud.

Viele Grüße
