### ISSUE TITLE
Deleted Stack still shown

### ISSUE THREAD

**Issue by dupondje** [stefan-niedermann/nextcloud-deck#88]
**Describe the bug**
When a stack is removed, it is still shown in the App.

**To Reproduce**
1. Create a stack
2. Now its correctly visible in the app
3. Remove the stack via a browser
4. The stack is still visible inside the app

**Expected behavior**
The stack should be hidden (as its removed).

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - Android-Version: 8

**Comment by desperateCoder** [comment]
Hi @dupondje,
thanks for your report!

As it would possibly drain your mobile data, we don't automatically synchronize the state unless you tell the app to do so. Handling WiFi-connections is not implemented yet like this, but it might be one day. Remember: we are still pre-alpha :sweat_smile: 

So this leads me to the following question: Did you try to swipe down to refresh or restart the app? Or did you do so but it doesn't change anything at all? 

I just tried it, for me it worked, even though i found an edge case where the view doesn't refresh properly.

Could you just play around a little, changing boards and refreshing / restarting and tell us, if the board is really still there?

Thanks in advance! 

###############

@stefan-niedermann the mentioned edge case: create board via app, select it. now delete via browser, restart app. sync works well and removes the board as expected, but the view still displays the deleted board. swipe right to open the sidenav, board is gone, but still displayed. I think some pixel-magic is needed here, go for it!

**Comment by dupondje** [comment]
Hi @desperateCoder 

That was a quick response :)
Even trying a force sync, stopping the app, removing the cache didn't fix it :(

The stack was still visible.

Then I debugged the API call's it does, but there the stack was not passed anymore. So it seems like it was stuck somewhere in the GUI of the app.

I did remove all data for the app, and did setup again, and now its really gone :)

**Comment by desperateCoder** [comment]
> That was a quick response :)
So was yours! Getting that much attention kind of forces us to stand behind our community, thanks to all of you for your interest in our project! Your feedback is quite important to us, since we can't have a million devices with another million of ROMs, so yeah, thats the least we can do for you guys!

> So it seems like it was stuck somewhere in the GUI of the app.
Thats all i wanted to hear! I am the backend-guy responsible for the sync, so i guess this is just another ticket for @stefan-niedermann! :smile: 

> I did remove all data for the app, and did setup again, and now its really gone :)
Yep, most likely UI, even though i wouldn't bet on it. Thank you so far, we will have a look at it as soon as we can!

**Comment by sunjam** [comment]
fwiw, I tried to refresh by swiping down.  I noticed that force quitting and restarting the app will show the correct state, whether those changes were made on the Android app or in 16.1.1 webui.

**Comment by jgrete** [comment]
Hi,
I've got the same behaviour. 
The same happens when I changed to a different account.
I'm always getting the very first stack...
I'm looking forward to see further development. Thanks for your work!
Jürgen
