### ISSUE TITLE
Make debug-logs accessable

### ISSUE THREAD

**Issue by desperateCoder** [stefan-niedermann/nextcloud-deck#880]
In order to enable users to provide some useful information about sync and stuff, we want to add the possibility to activate log-capturing inside our app.

See: https://github.com/stefan-niedermann/nextcloud-deck/issues/877#issuecomment-803167422

It could look something like this:
* in the settings, the user can enable log-capturing
* this sets a (static) flag in `DeckLog`, so it stores the logs in RAM
* this could be extended later on, so it writes to a File for persistence
* at the next startup, the flag is resetted, so the RAM won't be wasted
* the user can go to the same settings page then to get the log-content

This is my proposal for @stefan-niedermann, but the final solution could be different, as long as it serves its purpose.

Special thanks to @pmprog, who came up with this idea!

**Comment by stefan-niedermann** [comment]
`880-debug-logs` has already implemented a setting to turn persisten debug logs off and on.
@desperateCoder could you implement the part in `DeckLog`?

The question is: How should we make them accessible in the end? We could show them when an error occurs? Or add a new button in the settings activity, when it is enabled to copy it?

**Comment by desperateCoder** [comment]
> @desperateCoder could you implement the part in DeckLog?

Yep, sure.

> The question is: How should we make them accessible in the end?

I'd say both. 

``` JAVA
if (DeckLog.isDebugLogEnabled()) {
   stringToCopy.append(DeckLog.getDebugLog())
}
```
This would work in case an exception is thrown. In case the log is enabled, the user will most probably want to have it in the copied message. I'll push that in a couple of minutes.

In case no exception is thrown, the user might be aware of the fact, the log is there, where he toggled it. The UI should make that obvious, maybe by showing a disabled TextArea below with a hint, what will be inside, and maybe an additional, also disabled button (unless there's some logs to copy of course).

:heavy_check_mark: :grey_question:
