### ISSUE TITLE
Multi account support

### ISSUE THREAD

**Issue by juliushaertl** [stefan-niedermann/nextcloud-deck#9]
Not sure if you already have that in mind, but it would be awesome if users could set up and use multiple accounts at once.

**Comment by juliushaertl** [comment]
@desperateCoder @stefan-niedermann Btw. we have another hackweek in Stuttgart from November 26th to 30th, 2018. https://nextcloud.com/blog/join-us-at-our-next-contributor-week/ It would be awesome if you could join, so we can work on the app and I can make sure to buy you some beers :wink:

**Comment by stefan-niedermann** [comment]
Yes, we know, but it has been announced too late, we have both no time at this week :-/

3 weeks from announcment are unfortunately too little time.

**Comment by AndyScherzinger** [comment]
Work on master has been started by @stefan-niedermann regarding this feature

**Comment by stefan-niedermann** [comment]
Implemented in acd5c5b634eccd1d3579581a66cab01ab54ac00d 5d817140f22d3885e044ae4206fe6770cd9601ed 849ef214cbd289bf11878fa5b900c1ea2f9e0927 7619146110449059c99af90fa5968b6ef2d9fe57 0ba17e72fbc2865cb48b319b7115d6a70077fa92 a5aa4891a9edb68903659500d18f60a28248fb26
