### ISSUE TITLE
Dark-mode looks a bit strange in v1.15.8

### ISSUE THREAD

**Issue by szaimen** [stefan-niedermann/nextcloud-deck#905]
**Describe the bug**
Dark-mode looks a bit strange in v1.15.8

1. Install v1.15.8
2. Open the app
3. See screenshot

![Screenshot_20210328-213102_Nextcloud Deck](https://user-images.githubusercontent.com/42591237/112765391-47e38600-900d-11eb-8503-27154e2a6a03.png)
Edit: the field in the top right corner has an a bit other grey tone than the whole background.

**Comment by stefan-niedermann** [comment]
Thanks for the report :rocket: :slightly_smiling_face:  Will be fixed in `1.15.9` then.
