### ISSUE TITLE
Number of tasks in a checklist is not shown unless there is a comment on the card too

### ISSUE THREAD

**Issue by torkelsson** [stefan-niedermann/nextcloud-deck#910]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
In the list view the number of tasks (unchecked/checked) in a checklist of the card is not shown unless the card also has a comment.

1. Add a card to a list
2. Open the card and add a checklist with a couple of tasks:
 - [ ] A
 - [ ] B
 - [ ] C
3. "Save" the card and return to the list view
4. The number of tasks are not shown
5. Open the card again
6. Add a comment, "save" and return to the list view
7. A comment-symbol and the number of completed/uncompleted tasks are shown on the card

**Expected behavior**
The number of tasks should be shown even if there are no comments on the card.

**Screenshots**

**Versions**
 - Nextcloud: 20.0.8
 - Nextcloud Deck: 1.2.5
 - Nextcloud Android: 3.16.0 RC2
 - Nextcloud Android Deck: 1.16.0

**Smartphone (please complete the following information):**
- Device: Huawei Mate 10 Pro
- Android-Version: 10
- App-Store:
  - [ ] Google Play Store
  - [X] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Comment by stefan-niedermann** [comment]
Good catch and well described steps to reproduce, thanks for that! :slightly_smiling_face: 

Will be fixed in `1.16.1`.
