### ISSUE TITLE
Hiding of completed tasks

### ISSUE THREAD

**Issue by torkelsson** [stefan-niedermann/nextcloud-deck#911]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**
When having a checklist with many tasks, it is sometimes very easy to miss an unchecked task in the middle of checked tasks, therefore a nice addition would be to hide checked tasks, in rendered "preview mode". 

**Describe the solution you'd like**
An option to hide completed/checked tasks of a checklist when in markdown rendered mode ("preview mode").

**Describe alternatives you've considered**
An option would be to move the completed tasks to another checklist. That would require a lot more manual work though and doing that also changes to order of the original tasks (if that matters).

**Comment by stefan-niedermann** [comment]
Sorry, this is nothing which we currently have on our roadmap. We assume that most people will want to see all items (also for orientation and submission purposes) making this feature request a quite edge case.
We want to keep the edit and preview mode as similar as possible and introducing a setting for this kind of edge case seems a bit arbitrary.

**Comment by torkelsson** [comment]
As you probably understand I disagree. I think that is a killer feature, especially when you have really long lists with only a few items not checked. Trying to migrate from the Trello to Nextcloud Deck it is a feature I'm really missing, especially when on the phone.

I respect your decision, though I was hoping that it could be added to the roadmap as a low priority task. 

I assume that a similar request to  the (server) Deck app also will be closed with a "wontfix"?

**Comment by stefan-niedermann** [comment]
> I assume that a similar request to the (server) Deck app also will be closed with a "wontfix"?

I don't know that because we are an independent developer team. I will probably also post my recommendation (to not implement it), but i am not the decision maker there.

On the other hand: If the maintainer of the server app accept your feature request, chances are high that we will adapt it in the Android app for the sake of feature parity, so feel free to ask 🙂
