### ISSUE TITLE
Markdown Table not shown in Android Deck Client

### ISSUE THREAD

**Issue by nextexplorer** [stefan-niedermann/nextcloud-deck#916]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

In the deck app in the nextcloud web interface I can use markdown tables, which are displayed very nicely. Unfortunately there is no visualization in the android deck client.  

1. Add in the description i.e.
| Syntax      | Description | Test Text     |
| :---        |    :----:   |          ---: |
| Header      | Title       | Here's this   |
| Paragraph   | Text        | And more      |

2. The visualization in the web interface shows the rendered table.
3. The android deck client unfortunately just shows the code.

**Expected behavior**

It would be great if the android deck client could also render the markdown table.

**Screenshots**

**Versions**
 - Nextcloud: 20.0.8
 - Nextcloud Deck: 1.2.5
 - Nextcloud Android: 3.15.1
 - Nextcloud Android Deck: 1.16.0

**Smartphone (please complete the following information):**
- Device: Samsung Galaxy S20 Ultra 5G
- Android-Version: 11
- App-Store:
  - [x] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Have you pressed the eye icon to enable the preview mode?

**Comment by nextexplorer** [comment]
Thank you for your very fast replay and sorry that I had not tested the explicit bug description. I just thought that the feature is not yet implemented, but it seems to be more complicated. Here now the real life case:

If I just add this table the android deck client visualizes the table perfectly:
>
Route | Entfernung | Tourenlänge | Kommentar |
:---: | :---: | :---: | :---: |
 [Cap Formentor zur Badebucht](https://www.outdooractive.com/en/route/hiking-route/mallorca/am-cap-formentor-auf-alten-steinwegen-zur-badebucht/120617942/)| 16 km - 0:18 h  | 8,6 km - 3:00 h | |
[Alcudia Platja Des Coll Baix](https://www.outdooractive.com/de/route/wanderung/mallorca/alcudia-platja-des-coll-baix-circular/148042948/) | 16 km - 0:18 h | 8,6 km - 3:00 h | Küsten-, Strand- und Bergwanderung mit Abstecher zu Sa Teula - Mittel: |

However, If I extend it to

**Top 5 Favoriten in der Nähe (< 20 km):**
Route | Entfernung | Tourenlänge | Kommentar |
:---: | :---: | :---: | :---: |
 [Cap Formentor zur Badebucht](https://www.outdooractive.com/en/route/hiking-route/mallorca/am-cap-formentor-auf-alten-steinwegen-zur-badebucht/120617942/)| 16 km - 0:18 h  | 8,6 km - 3:00 h | |
[Alcudia Platja Des Coll Baix](https://www.outdooractive.com/de/route/wanderung/mallorca/alcudia-platja-des-coll-baix-circular/148042948/) | 16 km - 0:18 h | 8,6 km - 3:00 h | Küsten-, Strand- und Bergwanderung mit Abstecher zu Sa Teula - Mittel: |

it does not work anymore. The solution here just was to add an additional new line after the bold header. The additional line is only needed for the android client...

While testing the tables I had another issue: It seems that you can't click on a link in a table (again only in the android client). Outside a table, this works. Do you have an advise for me?

However, thank you very much for your awesome work!

**Comment by stefan-niedermann** [comment]
So we have two issues here:

1. **Links in tables do not work.**
  I analyzed the issue and i think i know how this can be fixed. I [opened an issue](https://github.com/stefan-niedermann/nextcloud-notes/issues/1115) to keep tracking of this particular issue (don't be confused, it is in another repository, but fixing it there will also fix it in the Deck app.). I suggest to subscribe to the linked issue to get notified when something happens. As a workaround, obviously just keep a blank line before the table.

2. **Tables do not render if there is no blank line before it**
  This bug¹ is reproducible with the sample app of the [upstream markdown library](https://noties.io/Markwon/). I therefore [opened an issue upstream](https://github.com/noties/Markwon/issues/350) as we are not able to fix this within the Deck app. You should subscribe to this one as well.

¹ There is no dedicated paragraph which describes the desired behavior in this case in the [commonmark specification](https://spec.commonmark.org/0.28/), so one could argue this is not a bug but an enhancement.

Thanks for the clarification and happy easter :v:
