### ISSUE TITLE
Missing comment indicator

### ISSUE THREAD

**Issue by christianlupus** [stefan-niedermann/nextcloud-deck#928]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

There is a small indicator for each card that has comments attached to it. Unfortunately, this is not shown all the time.

1. Prepare a board with a few cards, some with some comments and some without
2. Take a vanilla installation of the android app and create/setup an account within
3. After sync look at the various cards on the board
4. Close the app, wait a bit of time, do a few more comments
5. Reopen the app and trigger sync
6. Repeat step 3

**Expected behavior**

All cards having comments attached are showing a small icon both in steps 3 + 6.

**Actual behavior**
The cards with comments are showing the icon in step 3 as expected.
In step 6 no icon is shown. I have to manually iterate over all cards to see if there are any important comments.

**Versions**
 - Nextcloud: 21.0.1
 - Nextcloud Deck: 1.3.2
 - Nextcloud Android: 3.16.0RC2
 - Nextcloud Android Deck: 1.16.1

**Smartphone (please complete the following information):**
- Device: Xiaomi Mi A2 Lite
- Android-Version: 10
- App-Store:
  - [x] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

I am unsure about the beta channel of the google play store. I think the NC main app is in beta version.

**Stacktrace**
No error is visible so no strack trace

**Comment by stefan-niedermann** [comment]
Hi @christianlupus 

just to make sure i understand you correctly: The comments indicator
- is missing on **all** cards
- is missing on **one** card
- is not up to date (e. g. shows the wrong number) on one or all cards?

Further questions:
- Can you observe the described behavior also for the attachments indicator?
- When do the icons reappear? After closing the app and restarting it? Performing a synchronization? ...?

**Comment by stefan-niedermann** [comment]
Might be related to (or even caused by) https://github.com/nextcloud/deck/issues/2952 - can you please check whether you are able to see the comment indicators in the Web UI in those cases?

**Comment by stefan-niedermann** [comment]
ping @christianlupus

**Comment by christianlupus** [comment]
Hi, @stefan-niedermann. Sorry for the late answer, had some pressing issues in my day job (and BTW my phone was broken).

The comment indicator was once shown (but I did not check it there, was just glad the cards were marked). Now, no cards show any marks regarding comments.
Just to make sure: The marking should be persistent if there are any comments or should it only show *new* comments?

Regarding attachments: I have not yet tried. I need to set up a test board and play with it (I do not want to clutter the production board).

The icons were there (again?) after I had to reconnect the app (removing the app's account and reapplying) as of #829.

The issue nextcloud/deck#2952 was opened by me. In fact, I found the issue in the web app, and soon after, I saw that the Android app seemed not to be affected as far as I remember.
Nevertheless, the next day (not 100% sure how long) the icons in the Android app were invisible as well. Therefore I asked above if this is a feature instead of a bug (if the icon just signals new/unread comments).

If this helps, I could give you temporary access to the board that caused the problems. Ping me if you want this.

**Comment by stefan-niedermann** [comment]
> The marking should be persistent if there are any comments or should it only show new comments?

The indicator should *always* be there

It would be awesome if you could check whether the comments are actually in thr android apps database: If the indicator is not shown again, please go completely offline and open a card - Check if the full comments are visible there or also missing.

A test account with a shared play board would be awesome, so we can try to reproduce this issue :) (credentials to info@niedermann.it) - thanks for the offer!

**Comment by stefan-niedermann** [comment]
@christianlupus did you already had some time to test

> [...] if you could check whether the comments are actually in the android apps database: If the indicator is not shown again, please go completely offline and open a card - Check if the full comments are visible there or also missing.

**Comment by christianlupus** [comment]
@stefan-niedermann I tried to reproduce but was no longer able to do so. I had updated both the server app and (I think) the android app in the meantime, the issue might well be gone in the current release.

If you do not mind, I will close here as I can no longer reproduce it. If it reappears, I will reopen/comment again.

**Comment by stefan-niedermann** [comment]
Sure, sounds good :) Thank you for the feedback.

**Comment by mortee** [comment]
I can reproduce this in app version 1.20.0. Apparently, the indicator icons are only shown when at least two are available of 
- description
- attachments
- comments
- assignee

**Comment by stefan-niedermann** [comment]
@mortee this behavior is by intention. The icon would cause the app to need a second line (for a consistent) for each card which wastes space for quite a little benefit.

**Comment by mortee** [comment]
I see, my bad. I'm fine with this, just didn't know it wasn't a bug.
