### ISSUE TITLE
Link to Board-view from Widget

### ISSUE THREAD

**Issue by aryasenna** [stefan-niedermann/nextcloud-deck#932]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**
No, not exactly a problem. 
However in your other app "Notes", the widget has a link to open the full app, in addition to individual entry.

**Describe the solution you'd like**

A link to Deck's board view from the widget.

**Describe alternatives you've considered**

I just put the Deck icon launcher next to widget, but this takes space.

**Additional context**

**Comment by desperateCoder** [comment]
Hi @aryasenna l, thanks for your request!

What type of Widget are you using? Stack? Card? Upcoming cards?

I guess you won't like to loose the possibility to enter an entry directly, where should one tap to get to to the boards view?

**Comment by aryasenna** [comment]
I'm using Upcoming cards.
> I guess you won't like to loose the possibility to enter an entry directly, where should one tap to get to to the boards view?

Absolutely, please don't remove the current access.
Ideally like in the Notes app widget, on the widget header there clickable element that open the App main activity.

**Comment by stefan-niedermann** [comment]
I think it makes most sense to open the Upcoming cards view of the app (available on version `1.17.4`) when clicking on one of the sections ("today", "tomorrow", "next week", ...) of the Upcoming cards widget.

**Comment by aryasenna** [comment]
That could also work, the point is I can access the full app from widget.

I see there is no apk yet for 1.17.4 on Gplay nor F-droid, I'd like to try it once it's available.

Btw, Your app is well-polished, especially for an OSS. The gplay purchase is well-worth it. :)

**Comment by stefan-niedermann** [comment]
Fixed in `1.18.0`. I experimented a bit with directly open the Upcoming cards view, but i had issues with the backstack (pressing the back button should navigate to the main view), so i decided to just open the main view for now when clicking on a separator.
