### ISSUE TITLE
Show version of app installed on server

### ISSUE THREAD

**Issue by gerhardbeck** [stefan-niedermann/nextcloud-deck#95]
I have quite some problems and think it might be, that the server app ist old.
As the server app is maintained in a big company I got no idea which version it is and feel unsure to open some issues if I don't know the version of the server app.
Therefore: is there a possibility to show the version number of the server app in "about"?

**Comment by desperateCoder** [comment]
Hi @gerhardbeck 
thanks for your report!
Please have a look at https://github.com/stefan-niedermann/nextcloud-deck/issues/75

Currently the server doesn't propagate the version of the deck app to the clients, but we are already working on it. The next Deck version will support this. We would only have a gap of like 2 versions, where we can't tell, if the installed server app verision is compatible. In this case we plan to display a warning to the user.

I hope this helps!

**Comment by gerhardbeck** [comment]
Hi @desperateCoder #75 inspired my issue :-)

**Comment by stefan-niedermann** [comment]
Indeed, this should be displayed in the `AboutFragmentCreditsTab` below of `TextView#about_version`.

![grafik](https://user-images.githubusercontent.com/4741199/59779587-d06db800-92b8-11e9-84e9-d144d763cb7f.png)

**Comment by desperateCoder** [comment]
Don't you want to show nextcloud version as well @stefan-niedermann ?

**Comment by stefan-niedermann** [comment]
no need, since the deck server app itself has a minimum requirement for the nextcloud app itself.
All APIs we are using from NC directly (like capabilities) are there since NC 1

**Comment by desperateCoder** [comment]
Ok, nevermind then. *Shrug*
