### ISSUE TITLE
Change default display mode with discriptions (edit/preview/last selected)

### ISSUE THREAD

**Issue by molivier-fcms** [stefan-niedermann/nextcloud-deck#971]
Hello there. 

**Is your feature request related to a problem? Please describe.**
When I open cards, description is **always** in edit mode. However I use a lot checkboxes with markdown syntax. Checking requires to switch description area in preview mode, then I can check the boxes. If I come and go between cards, I must switch from edit to preview mode all the time.

**Describe the solution you'd like**
I would like having the possibility to display descriptions in preview mode by default.

**Describe alternatives you've considered**
As in notes application, we could have a parameter that allow us to have 3 defaults modes when we open a card:

* Always in preview
* Always in edition
* Remember the last selection

**Comment by stefan-niedermann** [comment]
Deck will starting with version `1.9.0` remember the last selected mode (edit or preview). You can try this already by installing [this `.apk` file](https://github.com/stefan-niedermann/nextcloud-deck/suites/2837356024/artifacts/63279876) (It can safely be installed parallel to the released version).

We have currently no plans to implement all three options as in the Notes app. Maintaining this is already quite a big mess with many edge cases. I think, remembering the last state will cover most of the cases, especially if you are only viewing existing cards.

Some of the edge cases explained:
- Creating a new card will always show the edit mode, regardless what was the last used mode. Toggling between editing and preview will not affect the last remembered state.
- Opening an existing card with an empty description will switch to edit mode automatically and save this as new mode.
  - We will try to improve this behavior: Ideally we should show the edit mode in this case but remember the new mode *only* when it has been toggled at least once. However this is quite tricky, so no promises yet.

**Comment by molivier-fcms** [comment]
Hi Stefan,

Everything works as you say. These behaviors look logic.
You can merge it for the next release.

Thank you for this enhancement.

Matthieu
