### ISSUE TITLE
Swimlanes 

### ISSUE THREAD

**Issue by rolpro** [stefan-niedermann/nextcloud-deck#985]
**Is your feature request related to a problem? Please describe.**

In comlex projects with many "sub-projects" i love to sort tasks that belong together. As i use lists "inbox", "backlog", "To-Do" and "done" in every sub project, i have to start a new board for every new sub project. There is no way to get a overview except sorting by tags. I have to switch through all the boards to see whats going on.

**Describe the solution you'd like**

Kanboard offers a feature called "swimlanes" where any board can have sub boards with the same lists. 
Its like stacking boards in one board.

**Describe alternatives you've considered**

Maybe a view could do it, where i can filter, which boards i want to see at the same screen. Stacked vertically.

**Additional context**
The feature must not work on a smartphone. It inly makes sense on a big screen.

**Comment by stefan-niedermann** [comment]
Blocked by server app (which is not developed by us): https://github.com/nextcloud/deck/issues/32

**Comment by stefan-niedermann** [comment]
> The feature must not work on a smartphone. It inly makes sense on a big screen.

Since this issue tracker is only for the Android app, i'll close it here.
As mentioned in my previous comment, it is blocked by the server app, and if they support it, we will implement it in the Android app anyway.

**Comment by stefan-niedermann** [comment]
I recommend you to upvote :+1:  the linked issue to signalize your support for it :wink:
